# Generated by Django 4.1.3 on 2022-11-21 10:47

import contracts_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number',
                 models.CharField(blank=True, default='', max_length=50, verbose_name='Номер договора')),
                ('date_conclusion', models.DateField(verbose_name='Дата заключения договора')),
                ('subject_contract', models.TextField(blank=True, verbose_name='Предмет договора')),
                ('cost', models.FloatField(blank=True, default=0, null=True, verbose_name='Стоимость')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Дата закрытия договора')),
                ('prolongation',
                 models.CharField(blank=True, choices=[('auto', 'Автоматическая пролонгация'), ('ag', 'Оформление ДС')],
                                  default='', max_length=40, verbose_name='Пролонгация')),
                ('comment', models.TextField(blank=True, verbose_name='Примечание')),
                ('date_entry', models.DateField(auto_now_add=True, verbose_name='Дата ввода информации')),
                ('doc_file', models.FileField(blank=True, upload_to=contracts_app.models.contract_directory_path,
                                              verbose_name='Файл документа')),
                ('allowed_placed', models.BooleanField(default=False, verbose_name='Разрешение на публикацию')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='Номер машины')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('factory_number',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='Заводской номер')),
                ('exploits',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='Баркол эксплуатирует')),
                ('gtd', models.CharField(blank=True, default='', max_length=100, verbose_name='GTD')),
                ('passport', models.CharField(blank=True, default='', max_length=100, verbose_name='Паспорт')),
                ('ownership_right',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='Право владения')),
                ('year_of_manufacture',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='Год выпуска авто')),
            ],
            options={
                'verbose_name': 'Имущество',
                'verbose_name_plural': 'Имущество',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('post_description', models.TextField(blank=True, verbose_name='Текст заметки')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
        migrations.CreateModel(
            name='TypeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contract', models.CharField(max_length=50, verbose_name='Тип договора')),
            ],
            options={
                'verbose_name': 'Тип договора',
                'verbose_name_plural': 'Тип договоров',
            },
        ),
        migrations.CreateModel(
            name='TypeDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(max_length=50, verbose_name='Тип документа')),
                ('short_name', models.CharField(default='', max_length=3, verbose_name='Краткое наименование')),
                ('file_name_prefix', models.CharField(max_length=3, verbose_name='Префикс файла')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Тип документов',
            },
        ),
        migrations.CreateModel(
            name='TypeProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                'type_property', models.CharField(blank=True, default='', max_length=50, verbose_name='Тип имущества')),
            ],
            options={
                'verbose_name': 'Тип имущества',
                'verbose_name_plural': 'Тип имущества',
            },
        ),
    ]
