# Generated by Django 4.1.3 on 2022-11-19 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts_app', '0001_initial'),
        ('customers_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='typecontract',
            name='authorized_person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Авторизованное лицо'),
        ),
        migrations.AddField(
            model_name='posts',
            name='contract_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts_app.contract', verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='posts',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо'),
        ),
        migrations.AddField(
            model_name='estate',
            name='type_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts_app.typeproperty'),
        ),
        migrations.AddField(
            model_name='contract',
            name='access',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.accesslevel', verbose_name='Уровень доступа к документу'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_counteragent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.counteragent', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='contract',
            name='divisions',
            field=models.ManyToManyField(blank=True, to='customers_app.division', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо'),
        ),
        migrations.AddField(
            model_name='contract',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='contract',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts_app.contract', verbose_name='Главный документ'),
        ),
        migrations.AddField(
            model_name='contract',
            name='type_of_contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts_app.typecontract', verbose_name='Тип договора'),
        ),
        migrations.AddField(
            model_name='contract',
            name='type_of_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts_app.typedocuments', verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='contract',
            name='type_property',
            field=models.ManyToManyField(blank=True, to='contracts_app.typeproperty', verbose_name='Тип имущества'),
        ),
    ]
