# Generated by Django 4.0.6 on 2022-07-17 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('customers_app', '0014_delete_tasks'),
        ('contracts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Договор', 'verbose_name_plural': 'Договора'},
        ),
        migrations.AlterModelOptions(
            name='estate',
            options={'verbose_name': 'Имущество', 'verbose_name_plural': 'Имущество'},
        ),
        migrations.AlterModelOptions(
            name='typecontract',
            options={'verbose_name': 'Тип договора', 'verbose_name_plural': 'Тип договоров'},
        ),
        migrations.AlterModelOptions(
            name='typeproperty',
            options={'verbose_name': 'Тип имущества', 'verbose_name_plural': 'Тип имущества'},
        ),
        migrations.AddField(
            model_name='contract',
            name='access',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='customers_app.accesslevel', verbose_name='Уровень доступа к документу'),
        ),
    ]
