# Generated by Django 4.2 on 2023-05-11 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0037_alter_officialmemo_official_memo_type'),
        ('contracts_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Наименование')),
                ('address', models.CharField(blank=True, default='', max_length=250, verbose_name='Адрес')),
                ('container', models.BigIntegerField(default=0, verbose_name='Количество мест')),
                ('contract_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts_app.contract', verbose_name='Номер договора')),
                ('place_production_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_production', to='hrdepartment_app.placeproductionactivity', verbose_name='Наименование точки')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
    ]
