# Generated by Django 4.0.6 on 2022-07-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0014_delete_tasks'),
        ('contracts_app', '0002_alter_contract_options_alter_estate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='divisions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.division', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts_app.typeproperty', verbose_name='Тип имущества'),
        ),
    ]
