# Generated by Django 4.2 on 2023-05-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0003_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='actuality',
            field=models.BooleanField(default=False, verbose_name='Актуальность'),
        ),
    ]
