# Generated by Django 5.0.3 on 2024-03-20 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0005_alter_estate_type_property"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Наименование")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracts_app.typeproperty",
                        verbose_name="Тип имущества",
                    ),
                ),
            ],
            options={
                "verbose_name": "Имущество компании",
                "verbose_name_plural": "Имущество компании",
                "ordering": ["name"],
            },
        ),
    ]
