# Generated by Django 5.0.3 on 2024-03-20 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0006_companyproperty"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hotel",
        ),
    ]
