# Generated by Django 5.0.3 on 2024-03-27 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0007_delete_hotel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyproperty",
            options={
                "ordering": ["name"],
                "verbose_name": "УДАЛЕНО",
                "verbose_name_plural": "УДАЛЕНО",
            },
        ),
    ]
