# Generated by Django 4.0.6 on 2022-07-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0008_alter_contract_closing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts_app.contract'),
        ),
    ]
