# Generated by Django 5.0.6 on 2024-06-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0009_contract_official_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="date_conclusion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата заключения договора"
            ),
        ),
    ]
