# Generated by Django 4.0.5 on 2022-07-18 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contracts_app', '0009_contract_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='contracts_app.contract', verbose_name='Главный документ'),
        ),
    ]
