# Generated by Django 4.0.5 on 2022-07-18 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts_app', '0010_alter_contract_parent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_created=True, verbose_name='Дата создания')),
                ('post_description', models.TextField(blank=True, verbose_name='Текст заметки')),
                ('contract_number',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts_app.contract',
                                   verbose_name='Номер контракта')),
                ('responsible_person',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
