# Generated by Django 5.0.6 on 2024-06-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0011_alter_contract_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="date_entry",
            field=models.DateField(auto_now=True, verbose_name="Дата ввода информации"),
        ),
    ]
