# Generated by Django 5.0.6 on 2024-06-20 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0012_alter_contract_date_entry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="typecontract",
            options={
                "ordering": ["type_contract"],
                "verbose_name": "Тип договора",
                "verbose_name_plural": "Тип договоров",
            },
        ),
        migrations.AlterModelOptions(
            name="typedocuments",
            options={
                "ordering": ["type_document"],
                "verbose_name": "Тип документа",
                "verbose_name_plural": "Тип документов",
            },
        ),
        migrations.AlterModelOptions(
            name="typeproperty",
            options={
                "ordering": ["type_property"],
                "verbose_name": "Тип имущества",
                "verbose_name_plural": "Тип имущества",
            },
        ),
    ]
