# Generated by Django 4.0.6 on 2022-07-18 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts_app', '0013_alter_contract_divisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_executor', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо'),
        ),
    ]
