# Generated by Django 5.0.6 on 2024-06-20 13:07

import contracts_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0013_alter_typecontract_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="doc_file",
            field=models.FileField(
                blank=True,
                max_length=150,
                upload_to=contracts_app.models.contract_directory_path,
                verbose_name="Файл документа",
            ),
        ),
    ]
