# Generated by Django 4.0.5 on 2022-07-19 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts_app', '0014_contract_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='contract_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts_app.contract', verbose_name='Номер договора'),
        ),
    ]
