# Generated by Django 5.0.6 on 2025-07-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0015_alter_contract_date_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
