# Generated by Django 4.0.5 on 2022-07-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0015_alter_contract_executor_alter_posts_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
