# Generated by Django 5.2.12 on 2026-08-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0016_contract_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="estate",
            name="decommission_date",
            field=models.DateField(
                blank=True,
                help_text="Если дата указана, воздушное судно/имущество считается выведенным из эксплуатации",
                null=True,
                verbose_name="Дата вывода из эксплуатации",
            ),
        ),
    ]
