# Generated by Django 4.0.6 on 2022-07-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0016_alter_posts_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='allowed_placed',
            field=models.BooleanField(default=False, verbose_name='Разрешение на публикацию'),
        ),
    ]
