# Generated by Django 4.0.6 on 2022-08-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0020_posts_allowed_placed'),
        ('contracts_app', '0020_contract_type_of_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='access',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.accesslevel', verbose_name='Уровень доступа к документу'),
        ),
    ]
