# Generated by Django 4.0.6 on 2022-08-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0021_alter_contract_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='registration_number',
            field=models.CharField(default='', max_length=100, verbose_name='Номер машины'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='release_date',
            field=models.DateField(verbose_name='Дата выпуска'),
        ),
    ]
