# Generated by Django 4.1 on 2022-08-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0023_estate_exploits_estate_factory_number_estate_gtd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='type_property',
        ),
        migrations.AddField(
            model_name='contract',
            name='type_property',
            field=models.ManyToManyField(blank=True, to='contracts_app.typeproperty', verbose_name='Тип имущества'),
        ),
    ]
