# Generated by Django 4.0.6 on 2022-08-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0023_databaseuser_access_level_and_more'),
        ('contracts_app', '0024_remove_contract_type_property_contract_type_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='divisions',
            field=models.ManyToManyField(blank=True, to='customers_app.division', verbose_name='Подразделение'),
        ),
    ]
