# Generated by Django 4.0.6 on 2022-08-21 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0026_alter_accesslevel_name_alter_counteragent_email_and_more'),
        ('contracts_app', '0025_alter_contract_divisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_counteragent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.counteragent', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='internal_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Номер в папке'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='prolongation',
            field=models.CharField(blank=True, choices=[('auto', 'Автоматическая пролонгация'), ('ag', 'Оформление ДС')], default='', max_length=40, verbose_name='Пролонгация'),
        ),
        migrations.AlterField(
            model_name='typecontract',
            name='type_contract',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип договора'),
        ),
        migrations.AlterField(
            model_name='typedocuments',
            name='type_document',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='typeproperty',
            name='type_property',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип имущества'),
        ),
    ]
