# Generated by Django 4.1 on 2022-08-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0026_alter_contract_contract_counteragent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecontract',
            name='type_contract',
            field=models.CharField(max_length=50, verbose_name='Тип договора'),
        ),
        migrations.AlterField(
            model_name='typedocuments',
            name='file_name_prefix',
            field=models.CharField(max_length=3, verbose_name='Префикс файла'),
        ),
        migrations.AlterField(
            model_name='typedocuments',
            name='type_document',
            field=models.CharField(max_length=50, verbose_name='Тип документа'),
        ),
    ]
