# Generated by Django 4.1 on 2022-09-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0027_alter_typecontract_type_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocuments',
            name='short_name',
            field=models.CharField(default='', max_length=3, verbose_name='Краткое наименование'),
        ),
    ]
