# Generated by Django 4.1.1 on 2022-09-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0005_alter_contractsaccess_authorized_person'),
        ('contracts_app', '0028_typedocuments_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='internal_number',
        ),
        migrations.AddField(
            model_name='contract',
            name='contracts_access',
            field=models.ManyToManyField(to='administration_app.contractsaccess', verbose_name='Уровень доступа к договорам'),
        ),
    ]
