# Generated by Django 4.1.1 on 2022-09-13 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts_app', '0029_remove_contract_internal_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contracts_access',
        ),
        migrations.AddField(
            model_name='typecontract',
            name='authorized_person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Авторизованное лицо'),
        ),
    ]
