# Generated by Django 4.0.6 on 2022-07-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_name', models.CharField(blank=True, default='ООО Авиакомпания "БАРКОЛ"', max_length=100, verbose_name='Название портала')),
                ('portal_paginator', models.IntegerField(default=10, verbose_name='Пагинация по умолчанию')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
