# Generated by Django 5.0.3 on 2024-04-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration_app", "0001_initial"),
        ("customers_app", "0048_alter_division_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=128, verbose_name="Наименование"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        default="", max_length=3, verbose_name="Тип документа"
                    ),
                ),
                (
                    "division_type",
                    models.CharField(
                        default="", max_length=128, verbose_name="Тип подразделения"
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        default=0, verbose_name="Количество уведомлений"
                    ),
                ),
                (
                    "job_list",
                    models.ManyToManyField(
                        blank=True,
                        to="customers_app.job",
                        verbose_name="Список должностей",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["name"],
                "unique_together": {("name", "document_type", "division_type")},
            },
        ),
    ]
