# Generated by Django 4.0.6 on 2022-08-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalproperty',
            name='portal_session',
            field=models.BigIntegerField(default=3600, verbose_name='Длительность сессии'),
        ),
    ]
