# Generated by Django 5.2.12 on 2026-05-20 10:57

import administration_app.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration_app", "0002_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование шаблона"
                    ),
                ),
                (
                    "unique_code",
                    models.SlugField(
                        max_length=100,
                        unique=True,
                        verbose_name="Уникальный код шаблона",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("word", "Microsoft Word"),
                            ("excel", "Microsoft Excel"),
                            ("other", "Другой тип"),
                        ],
                        default="word",
                        max_length=20,
                        verbose_name="Тип шаблона",
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        help_text="Поддерживаются форматы: .docx, .xlsx, .doc, .xls",
                        upload_to=administration_app.models.get_template_document_upload_path,
                        verbose_name="Файл шаблона",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата начала использования",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания использования",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Версия"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон документа",
                "verbose_name_plural": "Шаблоны документов",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["unique_code", "is_active"],
                        name="administrat_unique__b039d5_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="administrat_start_d_8dbbdf_idx",
                    ),
                ],
            },
        ),
    ]
