# Generated by Django 5.2.12 on 2026-07-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration_app", "0003_templatedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalproperty",
            name="mobile_app_version",
            field=models.CharField(
                blank=True,
                default="1.0.0",
                max_length=20,
                verbose_name="Версия мобильного приложения",
            ),
        ),
    ]
