# Generated by Django 4.1.1 on 2022-09-13 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration_app', '0003_mainmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractsAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_category', models.IntegerField(default=0, verbose_name='Категория доступа')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Описание категории')),
                ('authorized_person', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к договорам',
                'verbose_name_plural': 'Доступ к договорам',
            },
        ),
    ]
