# Generated by Django 6.1.1 on 2026-09-27 06:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0004_portalproperty_mobile_app_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebTerminalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=64, verbose_name='IP-адрес клиента')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='User-Agent')),
                ('tab_id', models.CharField(default='tab_1', max_length=32, verbose_name='Идентификатор вкладки')),
                ('is_tmux', models.BooleanField(default=False, help_text='Использовалась ли устойчивая сессия tmux', verbose_name='Сессия tmux')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время начала')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('close_code', models.IntegerField(blank=True, null=True, verbose_name='Код закрытия')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия веб-терминала',
                'verbose_name_plural': 'Сессии веб-терминала',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='administrat_started_dd8401_idx'), models.Index(fields=['user', '-started_at'], name='administrat_user_id_588a1d_idx')],
            },
        ),
    ]
