# Generated by Django 4.1.1 on 2022-09-13 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration_app', '0004_contractsaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsaccess',
            name='authorized_person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Авторизованное лицо'),
        ),
    ]
