# Generated by Django 4.1.1 on 2022-09-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0030_remove_contract_contracts_access_and_more'),
        ('administration_app', '0006_remove_contractsaccess_access_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractsAccess',
        ),
    ]
