# Generated by Django 5.2.12 on 2026-04-16 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Пользовательское название для категоризации паролей.",
                        max_length=255,
                        verbose_name="Название группы",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец группы",
                    ),
                ),
                (
                    "parent_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Оставьте пустым для создания корневой группы.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="password_manager.passwordgroup",
                        verbose_name="Родительская группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа паролей",
                "verbose_name_plural": "Группы паролей",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EncryptedPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("app", "Приложение"),
                            ("website", "Сайт"),
                            ("service", "Сервис"),
                        ],
                        default="website",
                        max_length=50,
                        verbose_name="Тип ресурса",
                    ),
                ),
                ("url", models.URLField(max_length=2048, verbose_name="URL ресурса")),
                ("login", models.CharField(max_length=255, verbose_name="Логин")),
                (
                    "encrypted_password",
                    models.TextField(verbose_name="Зашифрованный пароль"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Примечание"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_passwords",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец записи",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passwords",
                        to="password_manager.passwordgroup",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись пароля",
                "verbose_name_plural": "Записи паролей",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "encrypted_password",
                    models.TextField(verbose_name="Старый зашифрованный пароль"),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("app", "Приложение"),
                            ("website", "Сайт"),
                            ("service", "Сервис"),
                        ],
                        max_length=50,
                        verbose_name="Тип ресурса",
                    ),
                ),
                ("url", models.URLField(max_length=2048, verbose_name="URL ресурса")),
                ("login", models.CharField(max_length=255, verbose_name="Логин")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Примечание"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "original_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="password_manager.encryptedpassword",
                        verbose_name="Исходная запись",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец записи",
                    ),
                ),
            ],
            options={
                "verbose_name": "История пароля",
                "verbose_name_plural": "Истории паролей",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=dict,
                        help_text="Формат словаря: {'user_id': 'read' | 'edit'}",
                        verbose_name="Права доступа",
                    ),
                ),
                (
                    "encrypted_password",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_entries",
                        to="password_manager.encryptedpassword",
                        unique=True,
                        verbose_name="Запись пароля",
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_passwords",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователи с доступом",
                    ),
                ),
            ],
            options={
                "verbose_name": "Общий пароль",
                "verbose_name_plural": "Общие пароли",
            },
        ),
        migrations.CreateModel(
            name="UserKeyHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(max_length=255, verbose_name="Хеш ключевой фразы"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encryption_key_hash",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Хеш ключевой фразы",
                "verbose_name_plural": "Хеши ключевых фраз",
            },
        ),
        migrations.AddIndex(
            model_name="passwordgroup",
            index=models.Index(
                fields=["owner", "parent_group"], name="password_ma_owner_i_d1df24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encryptedpassword",
            index=models.Index(
                fields=["owner", "group", "resource_type"],
                name="password_ma_owner_i_4b3c22_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordhistory",
            index=models.Index(
                fields=["original_record", "owner"],
                name="password_ma_origina_cf35d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sharedpassword",
            index=models.Index(
                fields=["encrypted_password"], name="password_ma_encrypt_246b03_idx"
            ),
        ),
    ]
