# Generated by Django 5.2.12 on 2026-04-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("password_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedpassword",
            name="admin_encrypted_copy",
            field=models.TextField(
                blank=True,
                help_text="Зашифровано мастер-ключом для привилегированного доступа.",
                null=True,
                verbose_name="Копия для администратора",
            ),
        ),
        migrations.AddField(
            model_name="passwordhistory",
            name="admin_encrypted_copy",
            field=models.TextField(
                blank=True,
                help_text="Архивная копия, зашифрованная мастер-ключом.",
                null=True,
                verbose_name="Копия для администратора",
            ),
        ),
    ]
