# Generated by Django 5.2.12 on 2026-04-16 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("password_manager", "0002_encryptedpassword_admin_encrypted_copy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedpassword",
            name="encrypted_password",
            field=models.OneToOneField(
                help_text="Связь «один-к-одному»: одна настройка общего доступа на запись.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_access",
                to="password_manager.encryptedpassword",
                verbose_name="Запись пароля",
            ),
        ),
    ]
