# Generated by Django 5.2.12 on 2026-04-17 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("password_manager", "0003_alter_sharedpassword_encrypted_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedpassword",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="passwords",
                to="password_manager.passwordgroup",
                verbose_name="Группа",
            ),
        ),
    ]
