# Generated by Django 5.2.12 on 2026-04-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("password_manager", "0004_alter_encryptedpassword_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedpassword",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Наименование"
            ),
        ),
    ]
