# Generated by Django 5.2.12 on 2026-04-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("password_manager", "0005_encryptedpassword_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordhistory",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Наименование"
            ),
        ),
    ]
