# Generated by Django 5.0.6 on 2024-12-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="repeat",
            field=models.CharField(
                choices=[
                    ("none", "Не повторять"),
                    ("daily", "Ежедневно"),
                    ("weekly", "Еженедельно"),
                    ("monthly", "Ежемесячно"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
