# Generated by Django 5.0.6 on 2024-12-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks_app", "0002_task_repeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата завершения"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата начала"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="repeat",
            field=models.CharField(
                choices=[
                    ("none", "Не повторять"),
                    ("daily", "Ежедневно"),
                    ("weekly", "Еженедельно"),
                    ("monthly", "Ежемесячно"),
                ],
                default="none",
                max_length=10,
                verbose_name="Повторяемость",
            ),
        ),
    ]
