# Generated by Django 5.0.6 on 2024-12-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks_app", "0004_alter_task_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="due_date",
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("primary", "Основной"),
                    ("warning", "Предупреждающий"),
                    ("info", "Информационный"),
                    ("danger", "Опасный"),
                    ("dark", "Темный"),
                ],
                default="primary",
                max_length=10,
                verbose_name="Важность",
            ),
        ),
    ]
