# Generated by Django 5.0.6 on 2024-12-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks_app", "0008_taskfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="repeat_days",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Дни недели"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания повторения"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_interval",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Интервал повторения"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="repeat",
            field=models.CharField(
                choices=[
                    ("daily", "Ежедневно"),
                    ("weekly", "Еженедельно"),
                    ("monthly", "Ежемесячно"),
                    ("yearly", "Ежегодно"),
                    ("custom", "Пользовательский интервал"),
                ],
                default="none",
                max_length=10,
                verbose_name="Повторяемость",
            ),
        ),
    ]
