# Generated by Django 5.2.12 on 2026-04-22 16:17

import tasks_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks_app", "0009_task_repeat_days_task_repeat_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskfile",
            name="original_filename",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Оригинальное имя"
            ),
        ),
        migrations.AlterField(
            model_name="taskfile",
            name="file",
            field=models.FileField(
                upload_to=tasks_app.models.get_task_file_path, verbose_name="Файл"
            ),
        ),
    ]
