# Generated by Django 5.2.12 on 2026-04-23 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks_app", "0010_taskfile_original_filename_alter_taskfile_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="repeat",
            field=models.CharField(
                choices=[
                    ("none", "Нет"),
                    ("daily", "Ежедневно"),
                    ("weekly", "Еженедельно"),
                    ("monthly", "Ежемесячно"),
                    ("yearly", "Ежегодно"),
                    ("custom", "Пользовательский интервал"),
                ],
                default="none",
                max_length=10,
                verbose_name="Повторяемость",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "completed"], name="tasks_app_t_user_id_528b1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["start_date", "end_date"], name="tasks_app_t_start_d_9176ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["priority"], name="tasks_app_t_priorit_66a772_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskfile",
            index=models.Index(
                fields=["task", "-uploaded_at"], name="tasks_app_t_task_id_05daad_idx"
            ),
        ),
    ]
