# Generated by Django 5.2.12 on 2026-04-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks_app", "0011_alter_task_repeat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="repeat_days",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Дни недели"
            ),
        ),
    ]
