# Generated by Django on 2026-09-07
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_existing_tasks_workflow(apps, schema_editor):
    """Синхронизирует статусы и ответственных для существующих задач."""
    Task = apps.get_model('tasks_app', 'Task')
    for task in Task.objects.all():
        updated_fields = []
        if not getattr(task, 'responsible_id', None) and getattr(task, 'user_id', None):
            task.responsible_id = task.user_id
            updated_fields.append('responsible')
        if getattr(task, 'completed', False):
            task.status = 'completed'
            updated_fields.append('status')
        else:
            task.status = 'new'
            updated_fields.append('status')
        if updated_fields:
            task.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0012_alter_task_repeat_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tasks',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Постановщик / Автор'
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='responsible_tasks',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Ответственный'
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(
                blank=True,
                related_name='assigned_tasks',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Исполнители'
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='observers',
            field=models.ManyToManyField(
                blank=True,
                related_name='observed_tasks',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Наблюдатели'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='shared_with',
            field=models.ManyToManyField(
                blank=True,
                related_name='shared_tasks',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Доступ для (шаринг)'
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Черновик'),
                    ('new', 'Новая'),
                    ('assigned', 'Назначена'),
                    ('in_progress', 'В работе'),
                    ('on_review', 'На проверке'),
                    ('returned', 'Возвращена на доработку'),
                    ('completed', 'Выполнена'),
                    ('cancelled', 'Отменена'),
                    ('overdue', 'Просрочена')
                ],
                db_index=True,
                default='new',
                max_length=20,
                verbose_name='Статус'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(
                choices=[
                    ('primary', 'Основной (Обычный)'),
                    ('warning', 'Внимание (Средний)'),
                    ('info', 'Информационный (Низкий)'),
                    ('danger', 'Высокий (Срочный)'),
                    ('dark', 'Критический (Блокирующий)')
                ],
                db_index=True,
                default='primary',
                max_length=10,
                verbose_name='Важность'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата завершения (дедлайн)'),
        ),
        migrations.AddField(
            model_name='task',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия в работу'),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted_review_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки на проверку'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата фактического завершения'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='task',
            name='requires_eds',
            field=models.BooleanField(default=False, verbose_name='Требуется ЭЦП при приемке'),
        ),
        migrations.AddField(
            model_name='task',
            name='eds_signature',
            field=models.TextField(blank=True, null=True, verbose_name='ЭЦП подпись'),
        ),
        migrations.AddField(
            model_name='task',
            name='eds_signed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='eds_signed_tasks',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Подписал ЭЦП'
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='eds_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания ЭЦП'),
        ),
        migrations.RunPython(
            code=populate_existing_tasks_workflow,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(
                    choices=[('responsible', 'Ответственный'), ('assignee', 'Исполнитель'), ('observer', 'Наблюдатель')],
                    default='assignee', max_length=20, verbose_name='Роль'
                )),
                ('status', models.CharField(
                    choices=[('pending', 'Ожидает принятия'), ('accepted', 'Принято в работу'), ('completed', 'Исполнено'), ('rejected', 'Отклонено')],
                    default='pending', max_length=20, verbose_name='Статус поручения'
                )),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий к поручению')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('assigned_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='task_assignments_given',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Кто назначил'
                )),
                ('assigned_to', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='task_assignments_received',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Кому назначено'
                )),
                ('task', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='assignments',
                    to='tasks_app.task',
                    verbose_name='Задача'
                )),
            ],
            options={
                'verbose_name': 'Поручение / Делегирование',
                'verbose_name_plural': 'Поручения и делегирование',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование подзадачи')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('assigned_to', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='subtasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'
                )),
                ('completed_by', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='completed_subtasks', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил'
                )),
                ('task', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='subtasks', to='tasks_app.task', verbose_name='Задача'
                )),
            ],
            options={
                'verbose_name': 'Подзадача / Чек-лист',
                'verbose_name_plural': 'Подзадачи и чек-листы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'
                )),
                ('parent', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='replies', to='tasks_app.taskcomment', verbose_name='Ответ на комментарий'
                )),
                ('task', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments', to='tasks_app.task', verbose_name='Задача'
                )),
            ],
            options={
                'verbose_name': 'Комментарий к задаче',
                'verbose_name_plural': 'Комментарии к задачам',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(
                    choices=[
                        ('created', 'Задача создана'),
                        ('status_changed', 'Изменен статус'),
                        ('assigned', 'Назначен исполнитель'),
                        ('delegated', 'Задача делегирована'),
                        ('accepted', 'Принята в работу'),
                        ('submitted_review', 'Отправлена на проверку'),
                        ('returned', 'Возвращена на доработку'),
                        ('completed', 'Выполнена'),
                        ('cancelled', 'Отменена'),
                        ('deadline_changed', 'Изменен дедлайн'),
                        ('subtask_toggled', 'Изменен чек-лист'),
                        ('file_added', 'Прикреплен файл'),
                        ('file_deleted', 'Удален файл'),
                        ('comment_added', 'Добавлен комментарий'),
                        ('eds_signed', 'Подписано ЭЦП')
                    ],
                    max_length=30, verbose_name='Действие'
                )),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Новое значение')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Примечание / Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время фиксации')),
                ('task', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='history', to='tasks_app.task', verbose_name='Задача'
                )),
                ('user', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='task_history_records', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'
                )),
            ],
            options={
                'verbose_name': 'Запись истории задачи',
                'verbose_name_plural': 'История изменений задач',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='taskfile',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Описание файла'),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Размер файла (байт)'),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='uploaded_by',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='uploaded_task_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'
            ),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status'], name='tasks_app_t_user_id_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['responsible', 'status'], name='tasks_app_t_resp_id_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'end_date'], name='tasks_app_t_stat_end_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['task', 'assigned_to'], name='tasks_app_ta_task_assig_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['assigned_to', 'status'], name='tasks_app_ta_assig_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['task', 'is_completed'], name='tasks_app_st_task_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='tasks_app_tc_task_creat_idx'),
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['task', '-created_at'], name='tasks_app_th_task_creat_idx'),
        ),
    ]
