# Generated by Django on 2026-09-07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0013_task_workflow_and_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='repeat',
            field=models.CharField(
                choices=[
                    ('none', 'Нет (разовая)'),
                    ('daily', 'Ежедневно'),
                    ('workdays', 'По рабочим дням (Пн-Пт)'),
                    ('weekly', 'Еженедельно / По дням недели'),
                    ('monthly', 'Ежемесячно'),
                    ('yearly', 'Ежегодно'),
                    ('custom', 'Пользовательский интервал (дней)'),
                ],
                default='none',
                max_length=20,
                verbose_name='Повторяемость',
            ),
        ),
    ]
