# Generated by Django 5.2.12 on 2026-09-10 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks_app", "0014_alter_task_repeat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskfile",
            options={
                "verbose_name": "Файл задачи",
                "verbose_name_plural": "Файлы задач",
            },
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="tasks_app_t_user_id_528b1f_idx",
        ),
        migrations.RenameIndex(
            model_name="subtask",
            new_name="tasks_app_s_task_id_ef0b4a_idx",
            old_name="tasks_app_st_task_comp_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="tasks_app_t_user_id_32e3b6_idx",
            old_name="tasks_app_t_user_id_stat_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="tasks_app_t_respons_485151_idx",
            old_name="tasks_app_t_resp_id_stat_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="tasks_app_t_status_5a1f36_idx",
            old_name="tasks_app_t_stat_end_idx",
        ),
        migrations.RenameIndex(
            model_name="taskassignment",
            new_name="tasks_app_t_task_id_10be5e_idx",
            old_name="tasks_app_ta_task_assig_idx",
        ),
        migrations.RenameIndex(
            model_name="taskassignment",
            new_name="tasks_app_t_assigne_ba4ce6_idx",
            old_name="tasks_app_ta_assig_stat_idx",
        ),
        migrations.RenameIndex(
            model_name="taskcomment",
            new_name="tasks_app_t_task_id_b0ec6d_idx",
            old_name="tasks_app_tc_task_creat_idx",
        ),
        migrations.RenameIndex(
            model_name="taskhistory",
            new_name="tasks_app_t_task_id_f7d2a4_idx",
            old_name="tasks_app_th_task_creat_idx",
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="taskfile",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="tasks_app.task",
                verbose_name="Задача",
            ),
        ),
        migrations.AlterField(
            model_name="taskfile",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата загрузки"),
        ),
    ]
