# Generated by Django 4.2.1 on 2023-06-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_key', models.CharField(default='', max_length=37, verbose_name='Уникальный номер')),
                ('chat_id', models.CharField(blank=True, max_length=20, verbose_name='Telegram ID')),
            ],
            options={
                'verbose_name': 'Идентификатор чата телеграм',
                'verbose_name_plural': 'Идентификатор чата телеграм',
            },
        ),
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', max_length=256, verbose_name='Сообщение')),
                ('document_url', models.URLField(blank=True, verbose_name='Ссылка документ')),
                ('document_id', models.CharField(blank=True, default='', max_length=37, null=True, verbose_name='UIN документа')),
                ('sending_counter', models.IntegerField(verbose_name='Счетчик отправок')),
                ('respondents', models.ManyToManyField(to='telegram_app.chatid', verbose_name='Получатели')),
            ],
            options={
                'verbose_name': 'Уведомление телеграм',
                'verbose_name_plural': 'Уведомления телеграм',
            },
        ),
    ]
