# Generated by Django 4.2.1 on 2023-06-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramnotification',
            name='sending_counter',
            field=models.IntegerField(default=0, verbose_name='Счетчик отправок'),
        ),
    ]
