# Generated by Django 4.2.1 on 2023-06-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0002_alter_telegramnotification_sending_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramnotification',
            name='sending_counter',
            field=models.IntegerField(default=3, verbose_name='Счетчик отправок'),
        ),
    ]
