# Generated by Django 5.0.3 on 2024-03-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_app", "0004_telegramnotification_send_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramnotification",
            name="send_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата отправки"),
        ),
    ]
