# Generated by Django 6.1.1 on 2026-09-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0005_telegramnotification_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatid',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна ли подписка'),
        ),
        migrations.AddField(
            model_name='chatid',
            name='notify_birthdays',
            field=models.BooleanField(default=True, verbose_name='Уведомления о днях рождения'),
        ),
        migrations.AddField(
            model_name='chatid',
            name='notify_emails',
            field=models.BooleanField(default=True, verbose_name='Уведомления о корпоративной почте'),
        ),
        migrations.AddField(
            model_name='chatid',
            name='notify_flights',
            field=models.BooleanField(default=True, verbose_name='Уведомления о рейсах и экипажах'),
        ),
        migrations.AddField(
            model_name='chatid',
            name='notify_memos',
            field=models.BooleanField(default=True, verbose_name='Уведомления о служебных записках'),
        ),
        migrations.AddField(
            model_name='chatid',
            name='notify_tasks',
            field=models.BooleanField(default=True, verbose_name='Уведомления о задачах'),
        ),
    ]
