"""
Django settings for djangoProject project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import hashlib
import pathlib
import sys
from pathlib import Path

# Для работы с переменными которые хранятся в файле .env
from decouple import config
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.


BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

if not config("DEVELOPMENT", default=False, cast=bool):
    # Устанавливаем SESSION_ENGINE на использование подписанных кук
    SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')])

USE_X_FORWARDED_FOR = True

CSRF_TRUSTED_ORIGINS = ["https://corp.barkol.ru", "http://192.168.10.12"]

# Application definition

INSTALLED_APPS = [
    "core",
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # optional, if django-constance package is used
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "daphne",
    "django.contrib.staticfiles",
    "library_app.apps.LibraryAppConfig",
    "administration_app.apps.AdministrationAppConfig",
    "customers_app.apps.CustomersAppConfig",
    "contracts_app.apps.ContractsAppConfig",
    "hrdepartment_app.apps.HrdepartmentAppConfig",
    "logistics_app.apps.LogisticsAppConfig",
    "telegram_app.apps.TelegramAppConfig",
    "tasks_app.apps.TasksAppConfig",
    "ppequipment_app.apps.PpequipmentAppConfig",
    "tickets_app.apps.TicketsAppConfig",
    "password_manager.apps.PasswordManagerConfig",
    "map_viewer.apps.MapViewerConfig",
    "widget_tweaks",
    "django_ckeditor_5",
    "channels",
    "dynamic_formsets",
    "chat_app.apps.ChatAppConfig",
    "django_bootstrap5",  # Если используем django-bootstrap5
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.log_context.LogContextMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'administration_app.middleware.RequestMiddleware',
    "xff.middleware.XForwardedForMiddleware",
    "customers_app.middleware.LockScreenMiddleware",
    # "core.middleware.request_logging.RequestLoggingMiddleware",
]

if DEBUG:
    INSTALLED_APPS += ["debug_toolbar"]
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")

XFF_TRUSTED_PROXY_DEPTH = 2

ROOT_URLCONF = "djangoProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Подключаем context processors из приложения administration_app
                "administration_app.context_processors.get_all_contracts",
                "administration_app.context_processors.get_approval_oficial_memo_process",
                "administration_app.context_processors.breadcrumbs",
                # "administration_app.context_processors.get_qrcode",
            ],
        },
    },
]

WSGI_APPLICATION = "djangoProject.wsgi.application"
ASGI_APPLICATION = "djangoProject.asgi.application"

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

if not config("DEVELOPMENT", default=False, cast=bool):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": config("DATABASE_NAME"),
            "HOST": config("DATABASE_HOST"),
            "USER": config("DATABASE_USERNAME"),
            "PASSWORD": config("DATABASE_PASSWORD"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        'OPTIONS': {
            'user_attributes': ('first_name', 'last_name', 'birthday'),
            'max_similarity': 0.6,
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "ru-RU"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# STATIC_URL = 'static/'
# STATICFILES_DIRS = (
#     pathlib.Path.joinpath(BASE_DIR, 'static'),
# )

STATIC_URL = "/static/"
# STATIC_ROOT = pathlib.Path.joinpath(BASE_DIR, 'static')

STATICFILES_DIRS = [
    pathlib.Path.joinpath(BASE_DIR, "static_dev"),
    pathlib.Path.joinpath(BASE_DIR, 'static'),
]

MEDIA_URL = "/media/"
MEDIA_ROOT = pathlib.Path.joinpath(BASE_DIR, "media")

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # или AllowAny, если нужно открытое API
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',  # если используете токены
    ],
}

customColorPalette = [
    {"color": "hsl(4, 90%, 58%)", "label": "Red"},
    {"color": "hsl(340, 82%, 52%)", "label": "Pink"},
    {"color": "hsl(291, 64%, 42%)", "label": "Purple"},
    {"color": "hsl(262, 52%, 47%)", "label": "Deep Purple"},
    {"color": "hsl(231, 48%, 48%)", "label": "Indigo"},
    {"color": "hsl(207, 90%, 54%)", "label": "Blue"},
]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],

    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
                    'code', 'subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|', 'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable', ],
        'htmlSupport': {
            'allow': [
                {
                    'name': '/.*/',  # Разрешить все теги
                    'attributes': True,  # Разрешить все атрибуты (классы)
                    'classes': True,  # Разрешить любые названия классов
                    'styles': True  # Разрешить inline-стили
                }
            ]
        },
        # Важно: если вы хотите вставлять произвольный HTML,
        # добавьте плагин Source Editing
        'extraPlugins': ['GeneralHtmlSupport', 'SourceEditing'],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side', '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells',
                               'tableProperties', 'tableCellProperties'],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'}
            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# DATA_UPLOAD_MAX_MEMORY_SIZE = 5248

# STATIC_ROOT = pathlib.Path.joinpath(BASE_DIR, 'static')
# MEDIA_ROOT = pathlib.Path.joinpath(BASE_DIR, 'media')
# MEDIA_URL = pathlib.Path.joinpath(BASE_DIR, 'media')
AUTH_USER_MODEL = "customers_app.DataBaseUser"
LOGIN_URL = "/users/login/"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_IMAP_HOST = config("EMAIL_IMAP_HOST")
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_IAS_USER = config("EMAIL_IAS_USER")
EMAIL_FLY_USER = config("EMAIL_FLY_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_IAS_PASSWORD = config("EMAIL_IAS_PASSWORD")
EMAIL_FLY_PASSWORD = config("EMAIL_FLY_PASSWORD")
EMAIL_USE_SSL = True
EMAIL_PORT = 465

REDIS_HOST = "127.0.0.1"
REDIS_PORT = "6379"
CELERY_BROKER_URL = "redis://" + REDIS_HOST + ":" + REDIS_PORT + "/0"
CELERY_BROKER_TRANSPORT_OPTION = {"visibility_timeout": 3600}
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # Автоматическая попытка установить соединение с AMQP broker при запуске Celery, если он недоступен.
CELERY_RESULT_BACKEND = "redis://" + REDIS_HOST + ":" + REDIS_PORT + "/0"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

if not config("DEVELOPMENT", default=False, cast=bool):
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://" + REDIS_HOST + ":" + REDIS_PORT + "/1",  # Адрес и порт Redis сервера
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
else:
    # A CACHES dictionary, which contains caching configurations.
    CACHES = {
        # we use "default" as the alias.
        "default": {
            # Here, we're using the file-based cache backend.
            "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",

            # LOCATION parameter to specify the file system path where cached data will be stored.
            "LOCATION": pathlib.Path.joinpath(BASE_DIR, 'django_cache'),
        }
    }

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

INTERNAL_IPS = [
    "127.0.0.1",
]

CKEDITOR_5_FILE_STORAGE = "administration_app.utils.CkeditorCustomStorage"
TELEGRAM_TOKEN = config("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = config("TELEGRAM_CHAT_ID")
API_TOKEN = TELEGRAM_TOKEN
WEBHOOK_PATH = API_TOKEN
WEBHOOK_URL = f"https://corp.barkol.ru/{WEBHOOK_PATH}"
WEBHOOK_SSL_CERTIFICATE = pathlib.Path.joinpath(
    BASE_DIR, config("CERTIFICATE_PEM_PATH")
)  # Путь к сертификату
WEBHOOK_SSL_PRIVATE = pathlib.Path.joinpath(
    BASE_DIR, config("KEY_PEM_PATH")
)  # Путь к приватному ключу

# Устанавливаем SESSION_COOKIE_SECURE в True, чтобы сессионные куки передавались только по HTTPS
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=False, cast=bool)

# Устанавливаем SESSION_COOKIE_HTTPONLY в True, чтобы куки были доступны только через HTTP
SESSION_COOKIE_HTTPONLY = config("SESSION_COOKIE_HTTPONLY", default=False, cast=bool)

# Устанавливаем CSRF_COOKIE_SECURE в True, чтобы CSRF-токены передавались только по HTTPS
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=False, cast=bool)

# Перенаправляем все запросы на HTTPS
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=False, cast=bool)

if not config("DEVELOPMENT", default=False, cast=bool):
    # Включаем HTTP Strict Transport Security (HSTS)
    SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=31536000, cast=int)
    SESSION_COOKIE_DOMAIN = config("SESSION_COOKIE_DOMAIN")
SECURE_HSTS_INCLUDE_SUBDOMAINS = config("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False, cast=bool)
SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=False, cast=bool)
# Устанавливает, что сессия истекает при закрытии браузера
SESSION_EXPIRE_AT_BROWSER_CLOSE = config("SESSION_EXPIRE_AT_BROWSER_CLOSE", default=False, cast=bool)

# Разрешаем доверять заголовкам X-Forwarded-For от прокси
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Django не будет инициализировать стандартный логгер
LOGGING_CONFIG = None
LOGGING = {}

from core.loguru_setup import setup_loguru

logger = setup_loguru()

IS_PRODUCTION = not DEBUG

UNFOLD = {
    "SITE_TITLE": "Корпоративный портал | Админка",  # Суффикс в <title> вкладки браузера
    "SITE_HEADER": "ООО АК 'БАРКОЛ'",  # Большой текст вверху сайдбара
    "SITE_SUBHEADER": "Внутренняя система",  # Подзаголовок под SITE_HEADER
    "SITE_URL": "/",  # Куда ведёт клик по логотипу (обычно "/")

    "BORDER_RADIUS": "8px",
    "COLORS": {
        "base": {
            "50": "oklch(98.5% .002 247.839)",
            "100": "oklch(96.7% .003 264.542)",
            "200": "oklch(92.8% .006 264.531)",
            "300": "oklch(87.2% .01 258.338)",
            "400": "oklch(70.7% .022 261.325)",
            "500": "oklch(55.1% .027 264.364)",
            "600": "oklch(44.6% .03 256.802)",
            "700": "oklch(37.3% .034 259.733)",
            "800": "oklch(27.8% .033 256.848)",
            "900": "oklch(21% .034 264.665)",
            "950": "oklch(13% .028 261.692)",
        },
        "primary": {
            "50": "oklch(97.7% .014 308.299)",
            "100": "oklch(94.6% .033 307.174)",
            "200": "oklch(90.2% .063 306.703)",
            "300": "oklch(82.7% .119 306.383)",
            "400": "oklch(71.4% .203 305.504)",
            "500": "oklch(62.7% .265 303.9)",
            "600": "oklch(55.8% .288 302.321)",
            "700": "oklch(49.6% .265 301.924)",
            "800": "oklch(43.8% .218 303.724)",
            "900": "oklch(38.1% .176 304.987)",
            "950": "oklch(29.1% .149 302.717)",
        },
        "font": {
            "subtle-light": "var(--color-base-500)",  # text-base-500
            "subtle-dark": "var(--color-base-400)",  # text-base-400
            "default-light": "var(--color-base-600)",  # text-base-600
            "default-dark": "var(--color-base-300)",  # text-base-300
            "important-light": "var(--color-base-900)",  # text-base-900
            "important-dark": "var(--color-base-100)",  # text-base-100
        },
    },
    "SIDEBAR": {
        "show_search": True,  # Поиск по всем пунктам сайдбара
        "command_search": False,  # Можно включить позже (как командная строка)
        "show_all_applications": True,
        # ОЧЕНЬ ВАЖНО! Внизу автоматически появятся все модели, которые не вошли в ручной navigation

        "navigation": [
            # ==================== 1. ГЛАВНАЯ ====================
            {
                "title": _("Главная"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Дашборд"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },

            # ==================== 2. ПОРТАЛ И УВЕДОМЛЕНИЯ ====================
            {
                "title": _("Портал и уведомления"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Свойства портала"),
                        "icon": "settings",
                        "link": reverse_lazy("admin:administration_app_portalproperty_changelist"),
                    },
                    {
                        "title": _("Главное меню"),
                        "icon": "menu",
                        "link": reverse_lazy("admin:administration_app_mainmenu_changelist"),
                    },
                    {
                        "title": _("Уведомления"),
                        "icon": "notifications",
                        "link": reverse_lazy("admin:administration_app_notification_changelist"),
                    },
                ],
            },

            # ==================== 3. ЧАТ ====================
            {
                "title": _("Чат"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Сообщения"),
                        "icon": "chat",
                        "link": reverse_lazy("admin:chat_app_message_changelist"),
                    },
                ],
            },

            # ==================== 4. ДОГОВОРЫ И НЕДВИЖИМОСТЬ ====================
            {
                "title": _("Договоры и недвижимость"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Типы свойств"),
                        "icon": "category",
                        "link": reverse_lazy("admin:contracts_app_typeproperty_changelist"),
                    },
                    {
                        "title": _("Типы договоров"),
                        "icon": "description",
                        "link": reverse_lazy("admin:contracts_app_typecontract_changelist"),
                    },
                    {
                        "title": _("Объекты недвижимости"),
                        "icon": "home",
                        "link": reverse_lazy("admin:contracts_app_estate_changelist"),
                    },
                    {
                        "title": _("Договоры"),
                        "icon": "contract",
                        "link": reverse_lazy("admin:contracts_app_contract_changelist"),
                    },
                    {
                        "title": _("Должности (договоры)"),
                        "icon": "work",
                        "link": reverse_lazy("admin:contracts_app_posts_changelist"),
                    },
                    {
                        "title": _("Типы документов"),
                        "icon": "folder",
                        "link": reverse_lazy("admin:contracts_app_typedocuments_changelist"),
                    },
                    {
                        "title": _("Свойства компаний"),
                        "icon": "business",
                        "link": reverse_lazy("admin:contracts_app_companyproperty_changelist"),
                    },
                ],
            },

            # ==================== 5. СОТРУДНИКИ И СТРУКТУРА (customers_app) ====================
            {
                "title": _("Сотрудники и структура"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Пользователи базы"),
                        "icon": "people",
                        "link": reverse_lazy("admin:customers_app_databaseuser_changelist"),
                    },
                    {
                        "title": _("Должности"),
                        "icon": "work",
                        "link": reverse_lazy("admin:customers_app_job_changelist"),
                    },
                    {
                        "title": _("Подразделения"),
                        "icon": "account_tree",
                        "link": reverse_lazy("admin:customers_app_division_changelist"),
                    },
                    {
                        "title": _("Контрагенты"),
                        "icon": "business",
                        "link": reverse_lazy("admin:customers_app_counteragent_changelist"),
                    },
                    {
                        "title": _("Должности (сотрудники)"),
                        "icon": "badge",
                        "link": reverse_lazy("admin:customers_app_posts_changelist"),
                    },
                    {
                        "title": _("Уровни доступа"),
                        "icon": "key",
                        "link": reverse_lazy("admin:customers_app_accesslevel_changelist"),
                    },
                    {
                        "title": _("Профили пользователей"),
                        "icon": "person",
                        "link": reverse_lazy("admin:customers_app_databaseuserprofile_changelist"),
                    },
                    {
                        "title": _("Гражданства"),
                        "icon": "flag",
                        "link": reverse_lazy("admin:customers_app_citizenships_changelist"),
                    },
                    {
                        "title": _("Документы, удостоверяющие личность"),
                        "icon": "badge",
                        "link": reverse_lazy("admin:customers_app_identitydocuments_changelist"),
                    },
                    {
                        "title": _("Рабочие профили"),
                        "icon": "work_history",
                        "link": reverse_lazy("admin:customers_app_databaseuserworkprofile_changelist"),
                    },
                    {
                        "title": _("Вредные условия труда"),
                        "icon": "warning",
                        "link": reverse_lazy("admin:customers_app_harmfulworkingconditions_changelist"),
                    },
                    {
                        "title": _("Просмотр документов физлиц"),
                        "icon": "visibility",
                        "link": reverse_lazy("admin:customers_app_viewdocumentsphysical_changelist"),
                    },
                    {
                        "title": _("История изменений"),
                        "icon": "history",
                        "link": reverse_lazy("admin:customers_app_historychange_changelist"),
                    },
                    {
                        "title": _("Поздравления с ДР"),
                        "icon": "cake",
                        "link": reverse_lazy("admin:customers_app_happybirthdaygreetings_changelist"),
                    },
                    {
                        "title": _("Принадлежность"),
                        "icon": "group",
                        "link": reverse_lazy("admin:customers_app_affiliation_changelist"),
                    },
                    {
                        "title": _("Списки графиков отпусков"),
                        "icon": "calendar_month",
                        "link": reverse_lazy("admin:customers_app_vacationschedulelist_changelist"),
                    },
                    {
                        "title": _("Графики отпусков"),
                        "icon": "beach_access",
                        "link": reverse_lazy("admin:customers_app_vacationschedule_changelist"),
                    },
                    {
                        "title": _("Документы контрагентов"),
                        "icon": "folder_shared",
                        "link": reverse_lazy("admin:customers_app_counteragentdocuments_changelist"),
                    },
                    {
                        "title": _("Статистика пользователей"),
                        "icon": "analytics",
                        "link": reverse_lazy("admin:customers_app_userstats_changelist"),
                    },
                    {
                        "title": _("Квартиры"),
                        "icon": "apartment",
                        "link": reverse_lazy("admin:customers_app_apartments_changelist"),
                    },

                ],
            },

            # ==================== 6. HR И КАДРОВЫЕ ПРОЦЕССЫ (hrdepartment_app) ====================
            {
                "title": _("HR и кадровые процессы"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Медицинские осмотры"),
                        "icon": "medical_services",
                        "link": reverse_lazy("admin:hrdepartment_app_medical_changelist"),
                    },
                    {
                        "title": _("Цели"),
                        "icon": "flag",
                        "link": reverse_lazy("admin:hrdepartment_app_purpose_changelist"),
                    },
                    {
                        "title": _("Официальные записки"),
                        "icon": "description",
                        "link": reverse_lazy("admin:hrdepartment_app_officialmemo_changelist"),
                    },
                    {
                        "title": _("Процесс согласования записок"),
                        "icon": "approval",
                        "link": reverse_lazy("admin:hrdepartment_app_approvaloficialmemoprocess_changelist"),
                    },
                    {
                        "title": _("Направления бизнес-процессов"),
                        "icon": "route",
                        "link": reverse_lazy("admin:hrdepartment_app_businessprocessdirection_changelist"),
                    },
                    {
                        "title": _("Медицинские организации"),
                        "icon": "local_hospital",
                        "link": reverse_lazy("admin:hrdepartment_app_medicalorganisation_changelist"),
                    },
                    {
                        "title": _("Должностные инструкции"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:hrdepartment_app_documentsjobdescription_changelist"),
                    },
                    {
                        "title": _("Приказы"),
                        "icon": "gavel",
                        "link": reverse_lazy("admin:hrdepartment_app_documentsorder_changelist"),
                    },
                    {
                        "title": _("Места производственной деятельности"),
                        "icon": "factory",
                        "link": reverse_lazy("admin:hrdepartment_app_placeproductionactivity_changelist"),
                    },
                    {
                        "title": _("Табель учёта рабочего времени"),
                        "icon": "table_chart",
                        "link": reverse_lazy("admin:hrdepartment_app_reportcard_changelist"),
                    },
                    {
                        "title": _("Причины отмены"),
                        "icon": "cancel",
                        "link": reverse_lazy("admin:hrdepartment_app_reasonforcancellation_changelist"),
                    },
                    {
                        "title": _("Описание приказов"),
                        "icon": "edit_note",
                        "link": reverse_lazy("admin:hrdepartment_app_orderdescription_changelist"),
                    },
                    {
                        "title": _("Предпраздничные дни"),
                        "icon": "event",
                        "link": reverse_lazy("admin:hrdepartment_app_preholidayday_changelist"),
                    },
                    {
                        "title": _("Выходные дни"),
                        "icon": "weekend",
                        "link": reverse_lazy("admin:hrdepartment_app_weekendday_changelist"),
                    },
                    {
                        "title": _("Производственный календарь"),
                        "icon": "calendar_today",
                        "link": reverse_lazy("admin:hrdepartment_app_productioncalendar_changelist"),
                    },
                    {
                        "title": _("Типы рабочего времени"),
                        "icon": "schedule",
                        "link": reverse_lazy("admin:hrdepartment_app_typesuserworktime_changelist"),
                    },
                    {
                        "title": _("Инструкции"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:hrdepartment_app_instructions_changelist"),
                    },
                    {
                        "title": _("Положения"),
                        "icon": "policy",
                        "link": reverse_lazy("admin:hrdepartment_app_provisions_changelist"),
                    },
                    {
                        "title": _("Создание команды"),
                        "icon": "group_add",
                        "link": reverse_lazy("admin:hrdepartment_app_creatingteam_changelist"),
                    },
                    {
                        "title": _("Таймшит"),
                        "icon": "timer",
                        "link": reverse_lazy("admin:hrdepartment_app_timesheet_changelist"),
                    },
                    {
                        "title": _("Оперативная работа"),
                        "icon": "construction",
                        "link": reverse_lazy("admin:hrdepartment_app_operationalwork_changelist"),
                    },
                    {
                        "title": _("Периодическая работа"),
                        "icon": "repeat",
                        "link": reverse_lazy("admin:hrdepartment_app_periodicwork_changelist"),
                    },
                    {
                        "title": _("Наряд-допуск"),
                        "icon": "assignment",
                        "link": reverse_lazy("admin:hrdepartment_app_outfitcard_changelist"),
                    },
                    {
                        "title": _("Подтверждение документов"),
                        "icon": "fact_check",
                        "link": reverse_lazy("admin:hrdepartment_app_documentacknowledgment_changelist"),
                    },
                    {
                        "title": _("Инструктажи"),
                        "icon": "school",
                        "link": reverse_lazy("admin:hrdepartment_app_briefings_changelist"),
                    },
                    {
                        "title": _("Оперативная деятельность"),
                        "icon": "engineering",
                        "link": reverse_lazy("admin:hrdepartment_app_operational_changelist"),
                    },
                    {
                        "title": _("События пользователей"),
                        "icon": "event_note",
                        "link": reverse_lazy("admin:hrdepartment_app_databaseuserevent_changelist"),
                    },
                    {
                        "title": _("Охрана труда"),
                        "icon": "shield",
                        "link": reverse_lazy("admin:hrdepartment_app_laborprotection_changelist"),
                    },
                    {
                        "title": _("Маршруты бизнес-процессов"),
                        "icon": "route",
                        "link": reverse_lazy("admin:hrdepartment_app_businessprocessroutes_changelist"),
                    },
                    {
                        "title": _("Руководящие документы"),
                        "icon": "policy",
                        "link": reverse_lazy("admin:hrdepartment_app_guidancedocuments_changelist"),
                    },
                    {
                        "title": _("Инструкции по охране труда"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:hrdepartment_app_laborprotectioninstructions_changelist"),
                    },
                    {
                        "title": _("Учебные подразделения"),
                        "icon": "school",
                        "link": reverse_lazy("admin:hrdepartment_app_trainingunit_changelist"),
                    },
                    {
                        "title": _("Учебные программы"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:hrdepartment_app_trainingprogram_changelist"),
                    },
                    {
                        "title": _("Студенческие договоры"),
                        "icon": "contract",
                        "link": reverse_lazy("admin:hrdepartment_app_studentagreement_changelist"),
                    },
                ],
            },

            # ==================== 7. БИБЛИОТЕКА И СОБЫТИЯ ====================
            {
                "title": _("Библиотека и события"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Хэштеги"),
                        "icon": "tag",
                        "link": reverse_lazy("admin:library_app_hashtag_changelist"),
                    },
                    {
                        "title": _("Категории помощи"),
                        "icon": "help",
                        "link": reverse_lazy("admin:library_app_helpcategory_changelist"),
                    },
                    {
                        "title": _("Темы помощи"),
                        "icon": "help_outline",
                        "link": reverse_lazy("admin:library_app_helptopic_changelist"),
                    },
                    {
                        "title": _("Формы документов"),
                        "icon": "description",
                        "link": reverse_lazy("admin:library_app_documentform_changelist"),
                    },
                    {
                        "title": _("Конкурсы"),
                        "icon": "emoji_events",
                        "link": reverse_lazy("admin:library_app_contest_changelist"),
                    },
                    {
                        "title": _("Стихотворения"),
                        "icon": "book",
                        "link": reverse_lazy("admin:library_app_poem_changelist"),
                    },
                    {
                        "title": _("Голосования"),
                        "icon": "poll",
                        "link": reverse_lazy("admin:library_app_vote_changelist"),
                    },
                    {
                        "title": _("События компании"),
                        "icon": "celebration",
                        "link": reverse_lazy("admin:library_app_companyevent_changelist"),
                    },
                ],
            },

            # ==================== 8. ЛОГИСТИКА И СКЛАД ====================
            {
                "title": _("Логистика и склад"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Путевые листы"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:logistics_app_waybill_changelist"),
                    },
                    {
                        "title": _("Посылки"),
                        "icon": "package_2",
                        "link": reverse_lazy("admin:logistics_app_package_changelist"),
                    },
                    {
                        "title": _("Изображения посылок"),
                        "icon": "image",
                        "link": reverse_lazy("admin:logistics_app_packageimage_changelist"),
                    },
                    {
                        "title": _("Оценки"),
                        "icon": "star",
                        "link": reverse_lazy("admin:logistics_app_grade_changelist"),
                    },
                    {
                        "title": _("Номенклатура"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:logistics_app_nomenclature_changelist"),
                    },
                    {
                        "title": _("Единицы номенклатуры"),
                        "icon": "straighten",
                        "link": reverse_lazy("admin:logistics_app_nomenclatureunit_changelist"),
                    },
                    {
                        "title": _("Группы номенклатуры"),
                        "icon": "category",
                        "link": reverse_lazy("admin:logistics_app_nomenclaturegroup_changelist"),
                    },
                ],
            },

            # ==================== 9. ЗАДАЧИ ====================
            {
                "title": _("Задачи"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Категории задач"),
                        "icon": "category",
                        "link": reverse_lazy("admin:tasks_app_category_changelist"),
                    },
                    {
                        "title": _("Задачи"),
                        "icon": "task_alt",
                        "link": reverse_lazy("admin:tasks_app_task_changelist"),
                    },
                ],
            },

            # ==================== 10. TELEGRAM ====================
            {
                "title": _("Telegram"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Чаты"),
                        "icon": "telegram",
                        "link": reverse_lazy("admin:telegram_app_chatid_changelist"),
                    },
                    {
                        "title": _("Уведомления Telegram"),
                        "icon": "notifications",
                        "link": reverse_lazy("admin:telegram_app_telegramnotification_changelist"),
                    },
                ],
            },

            # ==================== 11. ДОБРОВОЛЬНЫЕ СООБЩЕНИЯ ====================
            {
                "title": _("Сообщения"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Заявки"),
                        "icon": "category",
                        "link": reverse_lazy("admin:tickets_app_ticket_changelist"),
                    },
                    {
                        "title": _("Добровольные сообщения"),
                        "icon": "task_alt",
                        "link": reverse_lazy("admin:tickets_app_message_changelist"),
                    },
                    {
                        "title": _("Вложения"),
                        "icon": "task_alt",
                        "link": reverse_lazy("admin:tickets_app_attachment_changelist"),
                    },
                ],
            },
            # ==================== 12. ИНВЕНТАРНЫЙ УЧЕТ ====================
            {
                "title": _("Инвентарный учёт"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Справочник оборудования"),
                        "icon": "category",
                        "link": reverse_lazy("admin:ppequipment_app_equipment_changelist"),
                    },
                    {
                        "title": _("Связь оборудования с местоположением"),
                        "icon": "task_alt",
                        "link": reverse_lazy("admin:ppequipment_app_location_changelist"),
                    },
                    {
                        "title": _("Данные инвентаризации"),
                        "icon": "task_alt",
                        "link": reverse_lazy("admin:ppequipment_app_verification_changelist"),
                    },
                    {
                        "title": _("Справочник «Назн-лит»"),
                        "icon": "category",
                        "link": reverse_lazy("admin:ppequipment_app_destlit_changelist"),
                    },
                    {
                        "title": _("Справочник местоположений"),
                        "icon": "task_alt",
                        "link": reverse_lazy("admin:ppequipment_app_locationref_changelist"),
                    },
                    {
                        "title": _("Справочник типов ВС"),
                        "icon": "task_alt",
                        "link": reverse_lazy("admin:ppequipment_app_aircrafttype_changelist"),
                    },
                    {
                        "title": _("Справочник статусов контр-раб"),
                        "icon": "task_alt",
                        "link": reverse_lazy("admin:ppequipment_app_contractorstatus_changelist"),
                    },
                ],
            },
            # ==================== 13. МЕНЕДЖЕР ПАРОЛЕЙ ====================
            {
                "title": _("Менеджер паролей"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Группы паролей"),
                        "icon": "folder",
                        "link": reverse_lazy("admin:password_manager_passwordgroup_changelist"),
                    },
                    {
                        "title": _("Записи паролей"),
                        "icon": "lock",
                        "link": reverse_lazy("admin:password_manager_encryptedpassword_changelist"),
                    },
                    {
                        "title": _("История изменений"),
                        "icon": "history",
                        "link": reverse_lazy("admin:password_manager_passwordhistory_changelist"),
                    },
                    {
                        "title": _("Хеши ключевых фраз"),
                        "icon": "vpn_key",
                        "link": reverse_lazy("admin:password_manager_userkeyhash_changelist"),
                    },
                ],
            },
            # ==================== 14. Карты ====================
            {
                "title": _("Полетные карты"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Группы паролей"),
                        "icon": "folder",
                        "link": reverse_lazy("admin:map_viewer_mapsource_changelist"),
                    },

                ],
            },
        ],
    },

    "SHOW_HISTORY": True,  # Кнопка "История" в changeform
    "SHOW_VIEW_ON_SITE": True,  # Кнопка "Посмотреть на сайте"
    "SHOW_BACK_BUTTON": True,  # Кнопка "Назад" в шапке формы редактирования

    # Отключите отладочные функции в production
    "ENVIRONMENT": "administration_app.environment_callback" if not IS_PRODUCTION else None,
    "ENVIRONMENT_TITLE_PREFIX": "administration_app.environment_title_prefix_callback" if not IS_PRODUCTION else None,

    "SITE_DROPDOWN": [
        {
            "icon": "diamond",
            "title": _("Корпоративный портал"),
            "link": "https://corp.barkol.ru",
            "attrs": {
                "target": "_blank",
            },
        },
        {
            "icon": "diamond",
            "title": _("Администрирование"),
            "link": reverse_lazy("admin:index"),
        },
    ],
    "TABS": [
        {
            "models": [
                # На каких моделях показывать эти вкладки
                "administration_app.portalproperty",
                "administration_app.mainmenu",
                "administration_app.notification",

                "chat_app.message",

                "contracts_app.typeproperty",
                "contracts_app.typecontract",
                "contracts_app.estate",
                "contracts_app.contract",
                "contracts_app.posts",
                "contracts_app.typedocuments",
                "contracts_app.companyproperty",

                "customers_app.databaseuser",
                "customers_app.job",
                "customers_app.division",
                "customers_app.counteragent",
                "customers_app.posts",
                "customers_app.accesslevel",
                "customers_app.databaseuserprofile",
                "customers_app.citizenships",
                "customers_app.identitydocuments",
                "customers_app.databaseuserworkprofile",
                "customers_app.harmfulworkingconditions",
                "customers_app.viewdocumentsphysical",
                "customers_app.historychange",
                "customers_app.happybirthdaygreetings",
                "customers_app.affiliation",
                "customers_app.vacationschedulelist",
                "customers_app.vacationschedule",
                "customers_app.counteragentdocuments",
                "customers_app.userstats",
                "customers_app.apartments",
                "customers_app.apartmentbooking",

                "hrdepartment_app.medical",
                "hrdepartment_app.purpose",
                "hrdepartment_app.officialmemo",
                "hrdepartment_app.approvaloficialmemoprocess",
                "hrdepartment_app.businessprocessdirection",
                "hrdepartment_app.medicalorganisation",
                "hrdepartment_app.documentsjobdescription",
                "hrdepartment_app.documentsorder",
                "hrdepartment_app.placeproductionactivity",
                "hrdepartment_app.reportcard",
                "hrdepartment_app.reasonforcancellation",
                "hrdepartment_app.orderdescription",
                "hrdepartment_app.preholidayday",
                "hrdepartment_app.weekendday",
                "hrdepartment_app.productioncalendar",
                "hrdepartment_app.typesuserworktime",
                "hrdepartment_app.instructions",
                "hrdepartment_app.provisions",
                "hrdepartment_app.creatingteam",
                "hrdepartment_app.timesheet",
                "hrdepartment_app.operationalwork",
                "hrdepartment_app.periodicwork",
                "hrdepartment_app.outfitcard",
                "hrdepartment_app.documentacknowledgment",
                "hrdepartment_app.briefings",
                "hrdepartment_app.operational",
                "hrdepartment_app.databaseuserevent",
                "hrdepartment_app.laborprotection",
                "hrdepartment_app.businessprocessroutes",
                "hrdepartment_app.guidancedocuments",
                "hrdepartment_app.laborprotectioninstructions",
                "hrdepartment_app.trainingunit",
                "hrdepartment_app.trainingprogram",
                "hrdepartment_app.studentagreement",

                "library_app.hashtag",
                "library_app.helpcategory",
                "library_app.helptopic",
                "library_app.documentform",
                "library_app.contest",
                "library_app.poem",
                "library_app.vote",
                "library_app.companyevent",

                "logistics_app.waybill",
                "logistics_app.package",
                "logistics_app.packageimage",
                "logistics_app.grade",
                "logistics_app.nomenclature",
                "logistics_app.nomenclatureunit",
                "logistics_app.nomenclaturegroup",

                "tasks_app.category",
                "tasks_app.task",

                "telegram_app.chatid",
                "telegram_app.telegramnotification",

                # Модели менеджера паролей
                "password_manager.passwordgroup",
                "password_manager.encryptedpassword",
                "password_manager.passwordhistory",
                "password_manager.userkeyhash",
                "password_manager.sharedpassword",
            ],
            "items": [
                {
                    "title": _("Менеджер паролей"),
                    "icon": "lock",
                    "link": reverse_lazy("admin:password_manager_encryptedpassword_changelist"),
                    "permission": lambda request: request.user.has_perm("password_manager.view_encryptedpassword"),
                },
                {
                    "title": _("Портал и уведомления"),
                    "icon": "settings",  # или любой другой из Material Icons
                    "link": reverse_lazy("admin:administration_app_portalproperty_changelist"),
                    "permission": lambda request: request.user.has_perm("administration_app.view_portalproperty"),
                },
                {
                    "title": _("Чат"),
                    "icon": "chat",
                    "link": reverse_lazy("admin:chat_app_message_changelist"),
                },
                {
                    "title": _("Договоры"),
                    "icon": "description",
                    "link": reverse_lazy("admin:contracts_app_contract_changelist"),
                },
                {
                    "title": _("Сотрудники и структура"),
                    "icon": "people",
                    "link": reverse_lazy("admin:customers_app_databaseuser_changelist"),
                },
                {
                    "title": _("HR и кадровые процессы"),
                    "icon": "badge",
                    "link": reverse_lazy("admin:hrdepartment_app_officialmemo_changelist"),
                },
                {
                    "title": _("Библиотека и события"),
                    "icon": "library_books",
                    "link": reverse_lazy("admin:library_app_helptopic_changelist"),
                },
                {
                    "title": _("Логистика и склад"),
                    "icon": "local_shipping",
                    "link": reverse_lazy("admin:logistics_app_waybill_changelist"),
                },
                {
                    "title": _("Задачи"),
                    "icon": "task_alt",
                    "link": reverse_lazy("admin:tasks_app_task_changelist"),
                },
                {
                    "title": _("Telegram"),
                    "icon": "telegram",
                    "link": reverse_lazy("admin:telegram_app_chatid_changelist"),
                },
            ],
        },
    ],
}
