# Generated by Django 5.2.12 on 2026-04-21 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hrdepartment_app", "0150_studentagreement_signed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто назначил",
                    ),
                ),
                (
                    "mpd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="hrdepartment_app.placeproductionactivity",
                        verbose_name="МПД",
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пилот",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение пилота",
                "verbose_name_plural": "Назначения пилотов",
                "ordering": ["date", "mpd__name"],
                "indexes": [
                    models.Index(fields=["date"], name="flight_plan_date_d55f05_idx"),
                    models.Index(
                        fields=["mpd", "date"], name="flight_plan_mpd_id_eb61c5_idx"
                    ),
                    models.Index(
                        fields=["pilot", "date"], name="flight_plan_pilot_i_0853f4_idx"
                    ),
                ],
                "unique_together": {("pilot", "date")},
            },
        ),
    ]
