# Generated by Django 5.2.12 on 2026-08-25 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0017_estate_decommission_date"),
        ("flight_planning", "0001_initial"),
        (
            "hrdepartment_app",
            "0162_approvaloficialmemoprocess_date_of_arrival_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AircraftMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, verbose_name="Дата перемещения / базирования"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Примечание / Основание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="contracts_app.estate",
                        verbose_name="Воздушное судно",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_aircraft_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто переместил / зафиксировал",
                    ),
                ),
                (
                    "mpd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aircraft_movements",
                        to="hrdepartment_app.placeproductionactivity",
                        verbose_name="МПД базирования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перемещение ВС",
                "verbose_name_plural": "Журнал перемещений ВС",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["date"], name="flight_plan_date_8b8e22_idx"),
                    models.Index(
                        fields=["aircraft", "date"],
                        name="flight_plan_aircraf_74b0b3_idx",
                    ),
                    models.Index(
                        fields=["mpd", "date"], name="flight_plan_mpd_id_e157ab_idx"
                    ),
                ],
            },
        ),
    ]
