# Generated by Django 5.2.12 on 2026-08-25 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0017_estate_decommission_date"),
        ("flight_planning", "0002_aircraftmovement"),
        (
            "hrdepartment_app",
            "0162_approvaloficialmemoprocess_date_of_arrival_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pilotassignment",
            name="role_in_crew",
            field=models.CharField(
                blank=True,
                choices=[
                    ("commander", "КВС (Командир воздушного судна)"),
                    ("copilot", "Второй пилот"),
                    ("pilot_instructor", "Пилот-инструктор (проверяющий)"),
                    ("flight_engineer", "Бортмеханик"),
                    (
                        "flight_engineer_instructor",
                        "Бортмеханик-инструктор (проверяющий)",
                    ),
                ],
                default="",
                max_length=50,
                verbose_name="Роль в экипаже",
            ),
        ),
        migrations.CreateModel(
            name="FlightCrew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата")),
                (
                    "flight_type",
                    models.CharField(
                        choices=[
                            ("standard", "Обычный полет"),
                            ("check_flight_engineer", "Проверочный полет бортмеханика"),
                            ("check_pilot", "Проверочный полет пилотов"),
                            ("double_check", "Двойной проверочный полет"),
                        ],
                        default="standard",
                        max_length=50,
                        verbose_name="Тип полета",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Наименование экипажа",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="Примечание"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "aircraft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flight_crews",
                        to="contracts_app.estate",
                        verbose_name="Воздушное судно",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_flight_crews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто создал",
                    ),
                ),
                (
                    "mpd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_crews",
                        to="hrdepartment_app.placeproductionactivity",
                        verbose_name="МПД",
                    ),
                ),
            ],
            options={
                "verbose_name": "Летный экипаж",
                "verbose_name_plural": "Летные экипажи",
                "ordering": ["date", "mpd__name"],
            },
        ),
        migrations.CreateModel(
            name="CrewMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("commander", "КВС (Командир воздушного судна)"),
                            ("copilot", "Второй пилот"),
                            ("pilot_instructor", "Пилот-инструктор (проверяющий)"),
                            ("flight_engineer", "Бортмеханик"),
                            (
                                "flight_engineer_instructor",
                                "Бортмеханик-инструктор (проверяющий)",
                            ),
                        ],
                        max_length=50,
                        verbose_name="Роль в экипаже",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="flight_planning.flightcrew",
                        verbose_name="Экипаж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Член экипажа",
                "verbose_name_plural": "Члены экипажа",
            },
        ),
        migrations.AddField(
            model_name="pilotassignment",
            name="crew",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="flight_planning.flightcrew",
                verbose_name="Экипаж",
            ),
        ),
        migrations.AddIndex(
            model_name="flightcrew",
            index=models.Index(fields=["date"], name="flight_plan_date_42bea1_idx"),
        ),
        migrations.AddIndex(
            model_name="flightcrew",
            index=models.Index(
                fields=["mpd", "date"], name="flight_plan_mpd_id_63fb37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flightcrew",
            index=models.Index(
                fields=["aircraft", "date"], name="flight_plan_aircraf_042b78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crewmember",
            index=models.Index(
                fields=["crew", "member"], name="flight_plan_crew_id_7f85d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crewmember",
            index=models.Index(
                fields=["member", "role"], name="flight_plan_member__de0ca4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="crewmember",
            unique_together={("crew", "member")},
        ),
    ]
