# Generated by Django 5.2.12 on 2026-08-25 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "flight_planning",
            "0003_pilotassignment_role_in_crew_flightcrew_crewmember_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightCrewNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("commander", "КВС (Командир воздушного судна)"),
                            ("copilot", "Второй пилот"),
                            ("pilot_instructor", "Пилот-инструктор (проверяющий)"),
                            ("flight_engineer", "Бортмеханик"),
                            (
                                "flight_engineer_instructor",
                                "Бортмеханик-инструктор (проверяющий)",
                            ),
                        ],
                        default="",
                        max_length=50,
                        verbose_name="Роль автора в экипаже",
                    ),
                ),
                ("message", models.TextField(verbose_name="Текст сообщения / пометки")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время обновления"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crew_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор пометки",
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="flight_planning.flightcrew",
                        verbose_name="Экипаж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пометка к полету",
                "verbose_name_plural": "Пометки к полетам",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["crew", "-created_at"],
                        name="flight_plan_crew_id_408e7a_idx",
                    ),
                    models.Index(
                        fields=["author", "-created_at"],
                        name="flight_plan_author__77f142_idx",
                    ),
                ],
            },
        ),
    ]
