# Generated by Django 5.2 on 2026-08-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_planning', '0004_flightcrewnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightcrew',
            options={
                'ordering': ['date', 'mpd__name'],
                'permissions': [
                    ('can_manage_flight_planning', 'Может управлять планированием полетов (полный доступ)'),
                    ('can_view_flight_planning', 'Может просматривать таблицу планирования полетов'),
                    ('can_view_flight_reports', 'Может просматривать отчеты по планированию полетов'),
                ],
                'verbose_name': 'Летный экипаж',
                'verbose_name_plural': 'Летные экипажи',
            },
        ),
    ]
