# Generated by Django 5.2 on 2026-08-27

from django.db import migrations


def setup_flight_planning_roles(apps, schema_editor):
    """Создает стандартные группы и связывает их с правами доступа для планирования полетов."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    groups_config = {
        'Планирование полетов': [
            'can_manage_flight_planning',
            'can_view_flight_planning',
            'can_view_flight_reports',
            'add_flightcrew',
            'change_flightcrew',
            'delete_flightcrew',
            'view_flightcrew',
            'add_crewmember',
            'change_crewmember',
            'delete_crewmember',
            'view_crewmember',
            'add_pilotassignment',
            'change_pilotassignment',
            'delete_pilotassignment',
            'view_pilotassignment',
            'add_aircraftmovement',
            'change_aircraftmovement',
            'delete_aircraftmovement',
            'view_aircraftmovement',
            'add_flightcrewnote',
            'change_flightcrewnote',
            'delete_flightcrewnote',
            'view_flightcrewnote',
        ],
        'Руководство полетов': [
            'can_view_flight_planning',
            'can_view_flight_reports',
            'view_flightcrew',
            'view_crewmember',
            'view_pilotassignment',
            'view_aircraftmovement',
            'view_flightcrewnote',
        ],
        'Летный состав': [
            'can_view_flight_planning',
            'view_flightcrew',
            'view_crewmember',
            'view_pilotassignment',
            'view_aircraftmovement',
            'view_flightcrewnote',
            'add_flightcrewnote',
        ],
    }

    for group_name, perm_codenames in groups_config.items():
        group, _ = Group.objects.get_or_create(name=group_name)
        perms = Permission.objects.filter(codename__in=perm_codenames)
        for perm in perms:
            group.permissions.add(perm)


def rollback_flight_planning_roles(apps, schema_editor):
    """Откатывает создание групп планирования полетов при отмене миграции."""
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Планирование полетов', 'Руководство полетов', 'Летный состав']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('flight_planning', '0005_alter_flightcrew_options'),
        ('auth', '__latest__'),
    ]

    operations = [
        migrations.RunPython(setup_flight_planning_roles, rollback_flight_planning_roles),
    ]
