# Generated by Django 5.2.12 on 2026-08-28 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight_planning", "0006_setup_flight_planning_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightPlanningDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="Год планирования"
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        db_index=True, verbose_name="Месяц планирования"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Номер редакции"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending", "На утверждении"),
                            ("approved", "Утвержден"),
                            ("archived", "Архивный"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Статус документа",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок документа"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Основание / Причина изменений",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата и время утверждения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата составления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "snapshot_data",
                    models.JSONField(
                        default=dict, verbose_name="Снимок сетки планирования (JSON)"
                    ),
                ),
                (
                    "diff_data",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Список изменений (JSON)"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flight_planning_documents_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Утвердил (руководитель)",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flight_planning_documents_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Составил (диспетчер)",
                    ),
                ),
                (
                    "previous_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subsequent_documents",
                        to="flight_planning.flightplanningdocument",
                        verbose_name="Предыдущая редакция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ расстановки экипажей",
                "verbose_name_plural": "Документы расстановки экипажей",
                "ordering": ["-year", "-month", "-version"],
                "indexes": [
                    models.Index(
                        fields=["year", "month", "status"],
                        name="flight_plan_year_c222ed_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="flight_plan_created_9339c0_idx"
                    ),
                ],
            },
        ),
    ]
