# Generated by Django 5.2.12 on 2026-08-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_initial_check_types(apps, schema_editor):
    """Наполняет справочник базовыми видами проверок из регламента."""
    PeriodicCheckType = apps.get_model('flight_planning', 'PeriodicCheckType')
    TypeProperty = apps.get_model('contracts_app', 'TypeProperty')

    mi8_type = TypeProperty.objects.filter(type_property__icontains='ми-8').first()
    if not mi8_type:
        mi8_type = TypeProperty.objects.filter(type_property__icontains='mi-8').first()

    initial_checks = [
        {
            'name': 'Тренажер',
            'code': 'SIMULATOR',
            'aircraft_type': mi8_type,
            'validity_months': 7,
            'applies_to': 'crew',
            'order': 10,
            'description': 'Периодическая тренажерная подготовка на тренажере ВС.'
        },
        {
            'name': 'Человеческий фактор',
            'code': 'CRM',
            'aircraft_type': None,
            'validity_months': 36,
            'applies_to': 'crew',
            'order': 20,
            'description': 'Подготовка в области человеческого фактора и управления ресурсами экипажа (CRM).'
        },
        {
            'name': 'ВЛЭК ЛС',
            'code': 'VLEK_LS',
            'aircraft_type': None,
            'validity_months': 6,
            'applies_to': 'crew',
            'order': 30,
            'description': 'Врачебно-летная экспертная комиссия летного состава (полугодовое освидетельствование).'
        },
        {
            'name': 'Опасные грузы',
            'code': 'DANGEROUS_GOODS',
            'aircraft_type': None,
            'validity_months': 24,
            'applies_to': 'crew',
            'order': 40,
            'description': 'Подготовка по правилам воздушных перевозок опасных грузов ИКАО/ИАТА.'
        },
        {
            'name': 'Техника пилотирования',
            'code': 'PILOTING_TECH',
            'aircraft_type': mi8_type,
            'validity_months': 12,
            'applies_to': 'pilots',
            'order': 50,
            'description': 'Проверка техники пилотирования и самолетовождения на типе ВС.'
        },
        {
            'name': 'Авиационная безопасность',
            'code': 'AVSEC',
            'aircraft_type': None,
            'validity_months': 36,
            'applies_to': 'all',
            'order': 60,
            'description': 'Периодическая подготовка по авиационной безопасности.'
        },
        {
            'name': 'СУША на ВС',
            'code': 'LAND_SURVIVAL',
            'aircraft_type': mi8_type,
            'validity_months': 12,
            'applies_to': 'crew',
            'order': 70,
            'description': 'Аварийно-спасательная подготовка на суше (АСП) на типе ВС.'
        },
        {
            'name': 'КПК на тип ВС',
            'code': 'KPK_TYPE',
            'aircraft_type': mi8_type,
            'validity_months': 12,
            'applies_to': 'crew',
            'order': 80,
            'description': 'Курсы повышения квалификации (КПК) на тип ВС.'
        },
        {
            'name': 'ВЛЭК',
            'code': 'VLEK_ANNUAL',
            'aircraft_type': None,
            'validity_months': 12,
            'applies_to': 'crew',
            'order': 90,
            'description': 'Ежегодное медицинское заключение ВЛЭК.'
        },
    ]

    for item in initial_checks:
        PeriodicCheckType.objects.get_or_create(
            name=item['name'],
            aircraft_type=item['aircraft_type'],
            defaults=item
        )


def rollback_initial_check_types(apps, schema_editor):
    """Откат начальных видов проверок."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0017_estate_decommission_date'),
        ('flight_planning', '0007_flightplanningdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicCheckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование проверки')),
                ('code', models.CharField(blank=True, default='', max_length=50, verbose_name='Код / Обозначение')),
                ('validity_months', models.PositiveIntegerField(default=12, help_text='Срок действия по умолчанию для автоматического расчета даты окончания', verbose_name='Периодичность (в месяцах)')),
                ('validity_days', models.PositiveIntegerField(default=0, help_text='Дополнительные дни к месяцам при расчете (обычно 0)', verbose_name='Дополнительные дни')),
                ('applies_to', models.CharField(choices=[('all', 'Весь персонал'), ('crew', 'Летный состав (Пилоты и Бортмеханики)'), ('pilots', 'Только пилоты'), ('flight_engineers', 'Только бортмеханики'), ('technicians', 'Только авиатехники')], default='crew', max_length=50, verbose_name='Категория персонала')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание / Нормативный документ')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('aircraft_type', models.ForeignKey(blank=True, help_text='Оставьте пустым для универсальных проверок (*)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_types', to='contracts_app.typeproperty', verbose_name='Тип ВС')),
            ],
            options={
                'verbose_name': 'Вид периодической проверки',
                'verbose_name_plural': 'Виды периодических проверок',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'aircraft_type'], name='flight_plan_is_acti_5ff920_idx')],
            },
        ),
        migrations.CreateModel(
            name='PeriodicCheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True, verbose_name='Дата прохождения (Начало)')),
                ('end_date', models.DateField(db_index=True, verbose_name='Действует до (Окончание)')),
                ('document_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Номер документа / сертификата')),
                ('issued_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Кем выдано / Инструктор / УЦ')),
                ('scan_file', models.FileField(blank=True, null=True, upload_to='flight_planning/check_scans/%Y/%m/', verbose_name='Скан документа')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('aircraft_type', models.ForeignKey(blank=True, help_text='Оставьте пустым для универсальных проверок (*)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_records', to='contracts_app.typeproperty', verbose_name='Тип ВС')),
                ('check_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='flight_planning.periodicchecktype', verbose_name='Вид проверки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_periodic_checks', to=settings.AUTH_USER_MODEL, verbose_name='Кто внес')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_periodic_checks', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись о прохождении проверки',
                'verbose_name_plural': 'Журнал прохождения проверок',
                'ordering': ['-end_date', '-start_date'],
                'indexes': [
                    models.Index(fields=['employee', 'check_type', '-end_date'], name='flight_plan_employe_22765a_idx'),
                    models.Index(fields=['end_date'], name='flight_plan_end_dat_2b8cf1_idx'),
                ],
            },
        ),
        migrations.RunPython(seed_initial_check_types, rollback_initial_check_types),
    ]
