# Generated by Django 5.2.12 on 2026-08-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_initial_status_types(apps, schema_editor):
    """Наполняет справочник базовыми видами состояний и статусов персонала."""
    EmployeeStatusType = apps.get_model('flight_planning', 'EmployeeStatusType')

    initial_types = [
        {
            'name': 'Отпуск',
            'code': 'VACATION',
            'color': '#f59e0b',
            'is_blocking': True,
            'order': 10,
            'description': 'Основной ежегодный оплачиваемый отпуск.'
        },
        {
            'name': 'Дополнительный отпуск',
            'code': 'EXTRA_VACATION',
            'color': '#d97706',
            'is_blocking': True,
            'order': 20,
            'description': 'Дополнительный оплачиваемый или учебный отпуск.'
        },
        {
            'name': 'Больничный',
            'code': 'SICK_LEAVE',
            'color': '#ef4444',
            'is_blocking': True,
            'order': 30,
            'description': 'Временная нетрудоспособность по листку нетрудоспособности.'
        },
        {
            'name': 'Резерв',
            'code': 'RESERVE',
            'color': '#3b82f6',
            'is_blocking': True,
            'order': 40,
            'description': 'Нахождение в резерве (дежурство/резервный состав).'
        },
        {
            'name': 'Медосмотр',
            'code': 'MEDICAL_EXAM',
            'color': '#06b6d4',
            'is_blocking': True,
            'order': 50,
            'description': 'Прохождение периодического медицинского осмотра.'
        },
        {
            'name': 'КПК',
            'code': 'KPK',
            'color': '#8b5cf6',
            'is_blocking': True,
            'order': 60,
            'description': 'Курсы повышения квалификации (КПК) или переподготовка.'
        },
        {
            'name': 'ВЛЭК',
            'code': 'VLEK',
            'color': '#ec4899',
            'is_blocking': True,
            'order': 70,
            'description': 'Прохождение врачебно-летной экспертной комиссии.'
        },
        {
            'name': 'Командировка',
            'code': 'BUSINESS_TRIP',
            'color': '#10b981',
            'is_blocking': True,
            'order': 80,
            'description': 'Служебная командировка вне места постоянного базирования.'
        },
        {
            'name': 'Отгул',
            'code': 'DAY_OFF',
            'color': '#6b7280',
            'is_blocking': True,
            'order': 90,
            'description': 'Дополнительный день отдыха / отгул за ранее отработанное время.'
        },
        {
            'name': 'Другое',
            'code': 'OTHER',
            'color': '#64748b',
            'is_blocking': False,
            'order': 100,
            'description': 'Прочие причины отсутствия или специальный статус.'
        },
    ]

    for item in initial_types:
        EmployeeStatusType.objects.get_or_create(
            code=item['code'],
            defaults={
                'name': item['name'],
                'color': item['color'],
                'is_blocking': item['is_blocking'],
                'order': item['order'],
                'description': item['description'],
                'is_active': True
            }
        )


def rollback_status_types(apps, schema_editor):
    """Откат базовых типов проверок при отмене миграции."""
    EmployeeStatusType = apps.get_model('flight_planning', 'EmployeeStatusType')
    EmployeeStatusType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('flight_planning', '0008_periodicchecktype_periodiccheckrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeStatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Отпуск, Доп отпуск, Больничный, Резерв, Медосмотр, КПК, ВЛЭК', max_length=100, verbose_name='Наименование статуса')),
                ('code', models.CharField(blank=True, choices=[('VACATION', 'Отпуск'), ('EXTRA_VACATION', 'Дополнительный отпуск'), ('SICK_LEAVE', 'Больничный'), ('RESERVE', 'Резерв'), ('MEDICAL_EXAM', 'Медосмотр'), ('KPK', 'КПК'), ('VLEK', 'ВЛЭК'), ('BUSINESS_TRIP', 'Командировка'), ('DAY_OFF', 'Отгул'), ('OTHER', 'Другое')], default='', help_text='Системный код типа состояния', max_length=50, verbose_name='Код статуса')),
                ('color', models.CharField(default='#64748b', help_text='HEX-код цвета (например, #ef4444 для больничного, #f59e0b для отпуска)', max_length=20, verbose_name='Цвет бейджа')),
                ('is_blocking', models.BooleanField(default=True, help_text='Если включено, назначение сотрудника с этим статусом в экипаж будет вызывать предупреждение о занятости', verbose_name='Предупреждать при назначении в экипаж')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=10, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Вид состояния сотрудника',
                'verbose_name_plural': 'Справочник состояний сотрудников',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True, verbose_name='Дата начала (С)')),
                ('end_date', models.DateField(db_index=True, verbose_name='Дата окончания (ПО)')),
                ('document_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Номер документа / приказа')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_status_records', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_records', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('status_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='flight_planning.employeestatustype', verbose_name='Вид состояния')),
            ],
            options={
                'verbose_name': 'Запись о состоянии сотрудника',
                'verbose_name_plural': 'Журнал состояний сотрудников',
                'ordering': ['-start_date', 'employee__last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='employeestatusrecord',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='flight_plan_employe_b2bb74_idx'),
        ),
        migrations.AddIndex(
            model_name='employeestatusrecord',
            index=models.Index(fields=['start_date', 'end_date'], name='flight_plan_start_d_a5198e_idx'),
        ),
        migrations.RunPython(seed_initial_status_types, rollback_status_types),
    ]
