# Generated by Django 5.2.12 on 2026-08-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_planning', '0009_employeestatustype_employeestatusrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRequiredCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, help_text='Если флаг снят, проверка считается необязательной для данного сотрудника.', verbose_name='Обязательна к сдаче')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employee_checks', to=settings.AUTH_USER_MODEL, verbose_name='Кем назначено')),
                ('check_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='flight_planning.periodicchecktype', verbose_name='Вид проверки')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_periodic_checks', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Закрепление проверки за сотрудником',
                'verbose_name_plural': 'Закрепления проверок за персоналом',
                'ordering': ['employee__last_name', 'check_type__order'],
                'unique_together': {('employee', 'check_type')},
            },
        ),
        migrations.AddIndex(
            model_name='employeerequiredcheck',
            index=models.Index(fields=['employee', 'is_required'], name='flight_plan_employe_f9b099_idx'),
        ),
        migrations.AddIndex(
            model_name='employeerequiredcheck',
            index=models.Index(fields=['check_type', 'is_required'], name='flight_plan_check_t_b3cd52_idx'),
        ),
    ]
