# Generated by Django 5.2.12 on 2026-08-31 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0017_estate_decommission_date"),
        ("flight_planning", "0010_employeerequiredcheck"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeerequiredcheck",
            options={
                "ordering": ["employee__last_name", "check_type__order"],
                "verbose_name": "Закрепление мероприятия за сотрудником",
                "verbose_name_plural": "Закрепления мероприятий за персоналом",
            },
        ),
        migrations.AlterModelOptions(
            name="periodiccheckrecord",
            options={
                "ordering": ["-end_date", "-start_date"],
                "verbose_name": "Запись о прохождении мероприятия",
                "verbose_name_plural": "Журнал прохождения мероприятий",
            },
        ),
        migrations.AlterModelOptions(
            name="periodicchecktype",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Вид периодического мероприятия",
                "verbose_name_plural": "Виды периодических мероприятий",
            },
        ),
        migrations.RenameIndex(
            model_name="employeerequiredcheck",
            new_name="flight_plan_employe_b537b4_idx",
            old_name="flight_plan_employe_f9b099_idx",
        ),
        migrations.RenameIndex(
            model_name="employeerequiredcheck",
            new_name="flight_plan_check_t_0432d2_idx",
            old_name="flight_plan_check_t_b3cd52_idx",
        ),
        migrations.RenameIndex(
            model_name="employeestatusrecord",
            new_name="flight_plan_employe_a3533c_idx",
            old_name="flight_plan_employe_b2bb74_idx",
        ),
        migrations.RenameIndex(
            model_name="employeestatusrecord",
            new_name="flight_plan_start_d_16c27a_idx",
            old_name="flight_plan_start_d_a5198e_idx",
        ),
        migrations.RenameIndex(
            model_name="periodiccheckrecord",
            new_name="flight_plan_employe_7542eb_idx",
            old_name="flight_plan_employe_22765a_idx",
        ),
        migrations.RenameIndex(
            model_name="periodiccheckrecord",
            new_name="flight_plan_end_dat_664f9a_idx",
            old_name="flight_plan_end_dat_2b8cf1_idx",
        ),
        migrations.RenameIndex(
            model_name="periodicchecktype",
            new_name="flight_plan_is_acti_b53a21_idx",
            old_name="flight_plan_is_acti_5ff920_idx",
        ),
        migrations.AlterField(
            model_name="employeerequiredcheck",
            name="check_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_assignments",
                to="flight_planning.periodicchecktype",
                verbose_name="Вид мероприятия",
            ),
        ),
        migrations.AlterField(
            model_name="employeerequiredcheck",
            name="is_required",
            field=models.BooleanField(
                default=True,
                help_text="Если флаг снят, мероприятие считается необязательным для данного сотрудника.",
                verbose_name="Обязательно к прохождению",
            ),
        ),
        migrations.AlterField(
            model_name="periodiccheckrecord",
            name="aircraft_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Оставьте пустым для универсальных мероприятий (*)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="check_records",
                to="contracts_app.typeproperty",
                verbose_name="Тип ВС",
            ),
        ),
        migrations.AlterField(
            model_name="periodiccheckrecord",
            name="check_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="flight_planning.periodicchecktype",
                verbose_name="Вид мероприятия",
            ),
        ),
        migrations.AlterField(
            model_name="periodiccheckrecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_periodic_checks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="periodicchecktype",
            name="aircraft_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Оставьте пустым для универсальных мероприятий (*)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="check_types",
                to="contracts_app.typeproperty",
                verbose_name="Тип ВС",
            ),
        ),
        migrations.AlterField(
            model_name="periodicchecktype",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Активно"
            ),
        ),
        migrations.AlterField(
            model_name="periodicchecktype",
            name="name",
            field=models.CharField(
                max_length=200, verbose_name="Наименование мероприятия"
            ),
        ),
    ]
