# Generated by Django 5.2.12 on 2026-09-18 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight_planning", "0011_alter_employeerequiredcheck_options_and_more"),
        ("hrdepartment_app", "0165_placeproductionactivity_icao_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AviationWeatherForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icao_code",
                    models.CharField(
                        db_index=True,
                        help_text="4-буквенный код ICAO аэродрома",
                        max_length=4,
                        verbose_name="Код ICAO",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        db_index=True, verbose_name="Время выпуска (UTC)"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        db_index=True, verbose_name="Действует с (UTC)"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        db_index=True, verbose_name="Действует по (UTC)"
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(verbose_name="Исходная телеграмма TAF"),
                ),
                (
                    "forecast_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Расшифрованные периоды (JSON)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Сохранено в системе"
                    ),
                ),
                (
                    "mpd",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_forecasts",
                        to="hrdepartment_app.placeproductionactivity",
                        verbose_name="МПД базирования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогноз погоды (TAF)",
                "verbose_name_plural": "Архив прогнозов погоды (TAF)",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["icao_code", "issued_at"],
                        name="flight_plan_icao_co_a603bb_idx",
                    ),
                    models.Index(
                        fields=["valid_from", "valid_to"],
                        name="flight_plan_valid_f_ad95e7_idx",
                    ),
                    models.Index(
                        fields=["mpd", "issued_at"],
                        name="flight_plan_mpd_id_6a5924_idx",
                    ),
                ],
                "unique_together": {("icao_code", "issued_at")},
            },
        ),
        migrations.CreateModel(
            name="AviationWeatherObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icao_code",
                    models.CharField(
                        db_index=True,
                        help_text="4-буквенный код ICAO (например, UNNT, USRR, ULLI, UUEE)",
                        max_length=4,
                        verbose_name="Код ICAO",
                    ),
                ),
                (
                    "observation_time",
                    models.DateTimeField(
                        db_index=True, verbose_name="Время наблюдения (UTC)"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("METAR", "Регулярная сводка (METAR)"),
                            ("SPECI", "Специальная сводка (SPECI)"),
                        ],
                        default="METAR",
                        max_length=10,
                        verbose_name="Тип сводки",
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(
                        verbose_name="Исходная телеграмма (METAR/SPECI)"
                    ),
                ),
                (
                    "flight_category",
                    models.CharField(
                        choices=[
                            ("VFR", "ПВП (VFR) — Визуальные метеоусловия"),
                            ("MVFR", "ОПВП (MVFR) — Ухудшенные визуальные"),
                            ("IFR", "ППП (IFR) — Приборные метеоусловия"),
                            ("LIFR", "НППП (LIFR) — Низкие приборные"),
                        ],
                        default="VFR",
                        max_length=10,
                        verbose_name="Летные условия",
                    ),
                ),
                (
                    "wind_direction",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Направление ветра (°)"
                    ),
                ),
                (
                    "wind_speed",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Скорость ветра (м/с)"
                    ),
                ),
                (
                    "wind_gust",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Порывы ветра (м/с)"
                    ),
                ),
                (
                    "wind_variable",
                    models.BooleanField(
                        default=False,
                        verbose_name="Переменное направление ветра (VRB)",
                    ),
                ),
                (
                    "visibility_meters",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Видимость (м)"
                    ),
                ),
                (
                    "cavok",
                    models.BooleanField(
                        default=False, verbose_name="CAVOK (Хорошая погода)"
                    ),
                ),
                (
                    "cloud_base_meters",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Нижняя граница облачности (м)",
                    ),
                ),
                (
                    "cloud_coverage",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Покрытие облачностью",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Температура (°C)"
                    ),
                ),
                (
                    "dew_point",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Точка росы (°C)"
                    ),
                ),
                (
                    "pressure_hpa",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Давление QNH (гПа)"
                    ),
                ),
                (
                    "pressure_mmhg",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Давление QNH (мм рт. ст.)",
                    ),
                ),
                (
                    "weather_phenomena",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Погодные явления",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Сохранено в системе"
                    ),
                ),
                (
                    "mpd",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_observations",
                        to="hrdepartment_app.placeproductionactivity",
                        verbose_name="МПД базирования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Метеонаблюдение (METAR)",
                "verbose_name_plural": "Архив метеонаблюдений (METAR)",
                "ordering": ["-observation_time"],
                "indexes": [
                    models.Index(
                        fields=["icao_code", "observation_time"],
                        name="flight_plan_icao_co_b853de_idx",
                    ),
                    models.Index(
                        fields=["mpd", "observation_time"],
                        name="flight_plan_mpd_id_0e68cb_idx",
                    ),
                    models.Index(
                        fields=["flight_category", "observation_time"],
                        name="flight_plan_flight__f2ee3f_idx",
                    ),
                ],
                "unique_together": {("icao_code", "observation_time")},
            },
        ),
    ]
