# Generated by Django 5.2.12 on 2026-09-18 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flight_planning", "0012_aviationweatherobservation_aviationweatherforecast"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aviationweatherforecast",
            new_name="flight_plan_icao_co_d3810a_idx",
            old_name="flight_plan_icao_co_a603bb_idx",
        ),
        migrations.RenameIndex(
            model_name="aviationweatherforecast",
            new_name="flight_plan_valid_f_d5c04d_idx",
            old_name="flight_plan_valid_f_ad95e7_idx",
        ),
        migrations.RenameIndex(
            model_name="aviationweatherforecast",
            new_name="flight_plan_mpd_id_ae4a9d_idx",
            old_name="flight_plan_mpd_id_6a5924_idx",
        ),
        migrations.RenameIndex(
            model_name="aviationweatherobservation",
            new_name="flight_plan_icao_co_7b7037_idx",
            old_name="flight_plan_icao_co_b853de_idx",
        ),
        migrations.RenameIndex(
            model_name="aviationweatherobservation",
            new_name="flight_plan_mpd_id_30bf24_idx",
            old_name="flight_plan_mpd_id_0e68cb_idx",
        ),
        migrations.RenameIndex(
            model_name="aviationweatherobservation",
            new_name="flight_plan_flight__e1fb11_idx",
            old_name="flight_plan_flight__f2ee3f_idx",
        ),
    ]
