# Generated by Django 6.1.1 on 2026-09-19 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_planning', '0013_rename_flight_plan_icao_co_a603bb_idx_flight_plan_icao_co_d3810a_idx_and_more'),
        ('hrdepartment_app', '0166_placeproductionactivity_elevation_msl_m_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinateWeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта точки')),
                ('longitude', models.FloatField(verbose_name='Долгота точки')),
                ('elevation_msl_m', models.FloatField(blank=True, help_text='Высота поверхности площадки над уровнем моря (MSL) в метрах', null=True, verbose_name='Высота рельефа (MSL, м)')),
                ('provider', models.CharField(default='open-meteo', max_length=50, verbose_name='Провайдер данных')),
                ('model', models.CharField(default='ecmwf_ifs', help_text='Идентификатор численной модели (например, ecmwf_ifs, gfs_seamless, icon_seamless)', max_length=50, verbose_name='Модель атмосферы')),
                ('model_resolution', models.CharField(blank=True, default='0.1', max_length=20, verbose_name='Разрешение сетки')),
                ('model_run_at', models.DateTimeField(db_index=True, help_text='Время запуска/прогона численной модели атмосферы', verbose_name='Инициализация прогона (UTC)')),
                ('forecast_for', models.DateTimeField(db_index=True, help_text='Целевой час, на который рассчитаны метеопараметры', verbose_name='Срок прогноза (UTC)')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено в БД (UTC)')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Температура 2м (°C)')),
                ('dew_point', models.FloatField(blank=True, null=True, verbose_name='Точка росы 2м (°C)')),
                ('relative_humidity', models.FloatField(blank=True, null=True, verbose_name='Относительная влажность (%)')),
                ('surface_pressure_hpa', models.FloatField(blank=True, help_text='Расчетное атмосферное давление на уровне поверхности площадки', null=True, verbose_name='Давление поверхности (гПа)')),
                ('surface_pressure_mmhg', models.FloatField(blank=True, null=True, verbose_name='Давление поверхности (мм рт. ст.)')),
                ('pressure_msl_hpa', models.FloatField(blank=True, help_text='Атмосферное давление, приведенное к среднему уровню моря (QNH/MSLP)', null=True, verbose_name='Давление MSL (гПа)')),
                ('pressure_mmhg', models.FloatField(blank=True, null=True, verbose_name='Давление MSL (мм рт. ст.)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='Скорость ветра 10м (м/с)')),
                ('wind_direction', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Направление ветра 10м (°)')),
                ('wind_gust', models.FloatField(blank=True, null=True, verbose_name='Порывы ветра 10м (м/с)')),
                ('cloud_cover_total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Общая облачность (%)')),
                ('cloud_cover_low', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Нижняя облачность (%)')),
                ('cloud_cover_mid', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Средняя облачность (%)')),
                ('cloud_cover_high', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Верхняя облачность (%)')),
                ('cloud_base_agl_m', models.PositiveIntegerField(blank=True, help_text='Высота нижней границы облачности над поверхностью площадки (AGL) в метрах', null=True, verbose_name='Высота НГО (AGL, м)')),
                ('visibility_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='Расчетная видимость (м)')),
                ('freezing_level_msl_m', models.PositiveIntegerField(blank=True, help_text='Высота изотермы 0°C над средним уровнем моря (MSL)', null=True, verbose_name='Высота нулевой изотермы (MSL, м)')),
                ('precipitation_mm', models.FloatField(default=0.0, verbose_name='Осадки (мм/ч)')),
                ('precipitation_probability', models.FloatField(blank=True, null=True, verbose_name='Вероятность осадков (%)')),
                ('weather_code', models.PositiveSmallIntegerField(blank=True, help_text='Код метеорологического явления по стандарту WMO 4677', null=True, verbose_name='Код погоды WMO')),
                ('model_flight_category', models.CharField(choices=[('VFR', 'ПВП (VFR) — Расчетные визуальные'), ('MVFR', 'ОПВП (MVFR) — Расчетные ухудшенные'), ('IFR', 'ППП (IFR) — Расчетные приборные'), ('LIFR', 'НППП (LIFR) — Расчетные низкие приборные')], default='VFR', help_text='Ориентировочная модельная категория условий полета (VFR/MVFR/IFR/LIFR)', max_length=10, verbose_name='Модельная оценка условий')),
            ],
            options={
                'verbose_name': 'Координатный прогноз погоды',
                'verbose_name_plural': 'Архив координатных прогнозов',
                'ordering': ['-forecast_for'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='aviationweatherforecast',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='aviationweatherobservation',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='AviationWeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_code', models.CharField(db_index=True, help_text='4-буквенный международный код метеостанции/аэродрома (например, USRR, UNNT, USTR)', max_length=4, unique=True, verbose_name='Код ICAO')),
                ('name', models.CharField(help_text='Международное наименование аэропорта/станции', max_length=150, verbose_name='Наименование (латиница)')),
                ('name_ru', models.CharField(blank=True, default='', help_text='Русскоязычное наименование аэропорта или населенного пункта', max_length=150, verbose_name='Наименование (русский)')),
                ('latitude', models.FloatField(help_text='Географическая широта контрольной точки аэродрома в градусах', verbose_name='Широта')),
                ('longitude', models.FloatField(help_text='Географическая долгота контрольной точки аэродрома в градусах', verbose_name='Долгота')),
                ('elevation_msl_m', models.FloatField(blank=True, help_text='Высота контрольной точки аэродрома над средним уровнем моря (MSL) в метрах', null=True, verbose_name='Высота аэродрома (MSL, м)')),
                ('country', models.CharField(default='Russia', max_length=100, verbose_name='Страна')),
                ('is_active', models.BooleanField(default=True, help_text='Включить регулярный сбор фактических сводок METAR/TAF', verbose_name='Активна для мониторинга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Метеостанция (АМСГ/ICAO)',
                'verbose_name_plural': 'Справочник метеостанций (ICAO)',
                'ordering': ['icao_code'],
                'indexes': [models.Index(fields=['icao_code'], name='flight_plan_icao_co_e702da_idx'), models.Index(fields=['is_active', 'icao_code'], name='flight_plan_is_acti_ba0cf2_idx')],
            },
        ),
        migrations.AddField(
            model_name='aviationweatherforecast',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='flight_planning.aviationweatherstation', verbose_name='Метеостанция'),
        ),
        migrations.AddField(
            model_name='aviationweatherobservation',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='flight_planning.aviationweatherstation', verbose_name='Метеостанция'),
        ),
        migrations.AddIndex(
            model_name='aviationweatherforecast',
            index=models.Index(fields=['station', 'issued_at'], name='flight_plan_station_786c30_idx'),
        ),
        migrations.AddIndex(
            model_name='aviationweatherobservation',
            index=models.Index(fields=['station', 'observation_time'], name='flight_plan_station_85e165_idx'),
        ),
        migrations.AddConstraint(
            model_name='aviationweatherforecast',
            constraint=models.UniqueConstraint(fields=('icao_code', 'issued_at'), name='uniq_aviation_forecast_icao_issued'),
        ),
        migrations.AddConstraint(
            model_name='aviationweatherobservation',
            constraint=models.UniqueConstraint(fields=('icao_code', 'observation_time'), name='uniq_aviation_observation_icao_time'),
        ),
        migrations.AddField(
            model_name='coordinateweatherforecast',
            name='mpd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinate_forecasts', to='hrdepartment_app.placeproductionactivity', verbose_name='МПД базирования'),
        ),
        migrations.AddField(
            model_name='coordinateweatherforecast',
            name='nearest_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_forecasts', to='flight_planning.aviationweatherstation', verbose_name='Опорная метеостанция'),
        ),
        migrations.AddIndex(
            model_name='coordinateweatherforecast',
            index=models.Index(fields=['mpd', 'forecast_for'], name='flight_plan_mpd_id_16d7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinateweatherforecast',
            index=models.Index(fields=['forecast_for'], name='flight_plan_forecas_ed18a8_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinateweatherforecast',
            index=models.Index(fields=['model_run_at'], name='flight_plan_model_r_098744_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinateweatherforecast',
            index=models.Index(fields=['nearest_station', 'forecast_for'], name='flight_plan_nearest_5f8d35_idx'),
        ),
        migrations.AddConstraint(
            model_name='coordinateweatherforecast',
            constraint=models.UniqueConstraint(fields=('mpd', 'forecast_for', 'model'), name='uniq_mpd_forecast_model'),
        ),
    ]
