# Generated by Django 6.1.1 on 2026-09-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_planning', '0014_coordinateweatherforecast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviationweatherobservation',
            name='cloud_layers',
            field=models.JSONField(blank=True, default=list, help_text="Структурированные слои облачности: [{'coverage': 'FEW', 'altitude_m': 300, 'type': 'CB'}, ...]", verbose_name='Слои облачности (JSON)'),
        ),
        migrations.AlterField(
            model_name='coordinateweatherforecast',
            name='cloud_base_agl_m',
            field=models.FloatField(blank=True, help_text='Высота нижней границы облачности над поверхностью площадки (AGL) в метрах', null=True, verbose_name='Высота НГО (AGL, м)'),
        ),
        migrations.AlterField(
            model_name='coordinateweatherforecast',
            name='freezing_level_msl_m',
            field=models.FloatField(blank=True, help_text='Высота изотермы 0°C над средним уровнем моря (MSL)', null=True, verbose_name='Высота нулевой изотермы (MSL, м)'),
        ),
        migrations.AlterField(
            model_name='coordinateweatherforecast',
            name='visibility_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Расчетная видимость (м)'),
        ),
    ]
