# Generated by Django 6.1.1 on 2026-09-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_planning', '0015_aviationweatherobservation_cloud_layers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviationweatherstation',
            name='region',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Регион / Субъект РФ'),
        ),
    ]
