# Generated by Django 5.2.12 on 2026-04-10 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AircraftType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Тип ВС"),
                ),
            ],
            options={
                "verbose_name": "Тип ВС",
                "verbose_name_plural": "Типы ВС (справочник)",
                "db_table": "ppequipment_aircraft_type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContractorStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="Статус"),
                ),
            ],
            options={
                "verbose_name": "Статус контр-раб",
                "verbose_name_plural": "Статусы контр-раб (справочник)",
                "db_table": "ppequipment_contractor_status",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DestLit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Назн-лит",
                "verbose_name_plural": "Назн-лит (справочник)",
                "db_table": "ppequipment_dest_lit",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LocationRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=70, unique=True, verbose_name="Местоположение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Местоположение (справочник)",
                "verbose_name_plural": "Местоположения (справочник)",
                "db_table": "ppequipment_location_ref",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VerificationDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата сверки"),
                ),
            ],
            options={
                "verbose_name": "Дата сверки",
                "verbose_name_plural": "Даты сверок",
                "db_table": "ppequipment_verification_date",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "number",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Номер"
                    ),
                ),
                ("name", models.TextField(verbose_name="Наименование")),
                (
                    "edition",
                    models.TextField(blank=True, null=True, verbose_name="Издание"),
                ),
                (
                    "issue",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Выпуск"
                    ),
                ),
                (
                    "approved_by",
                    models.TextField(
                        blank=True, null=True, verbose_name="Кем утверждён"
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата утверждения"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Приоритет"
                    ),
                ),
                (
                    "aircraft_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment",
                        to="ppequipment_app.aircrafttype",
                        verbose_name="Тип ВС",
                    ),
                ),
                (
                    "dest_lit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment",
                        to="ppequipment_app.destlit",
                        verbose_name="Назн-лит",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
                "db_table": "ppequipment_equipment",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        db_column="номер",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="ppequipment_app.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
                (
                    "location_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_entries",
                        to="ppequipment_app.locationref",
                        verbose_name="Местоположение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Местоположение оборудования",
                "verbose_name_plural": "Местоположения оборудования",
                "db_table": "ppequipment_location",
            },
        ),
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "inventory_number",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Инвентарный №",
                    ),
                ),
                (
                    "last_verification_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Последняя сверка"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Примечание"),
                ),
                (
                    "vs_number",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="№ ВС"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата оконч."),
                ),
                (
                    "is_destroyed",
                    models.BooleanField(default=False, verbose_name="Уничтожен"),
                ),
                (
                    "contractor_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verifications",
                        to="ppequipment_app.contractorstatus",
                        verbose_name="Контр-раб",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        db_column="номер",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="ppequipment_app.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
                (
                    "location_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verifications",
                        to="ppequipment_app.locationref",
                        verbose_name="Где",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сверка",
                "verbose_name_plural": "Сверки",
                "db_table": "ppequipment_verification",
            },
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(fields=["number"], name="equip_number_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["equipment"], name="loc_equip_idx"),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("equipment", "location_ref"), name="uq_equip_location"
            ),
        ),
        migrations.AddIndex(
            model_name="verification",
            index=models.Index(fields=["equipment"], name="verif_equip_idx"),
        ),
    ]
