# Generated by Django 5.2.12 on 2026-04-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ppequipment_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="slug",
            field=models.SlugField(blank=True, editable=False, max_length=150),
        ),
    ]
