# Generated by Django 5.2.12 on 2026-05-07 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ppequipment_app", "0002_verification_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "ordering": ["number"],
                "verbose_name": "Производственно техническая документация",
                "verbose_name_plural": "Производственно техническая документация",
            },
        ),
    ]
