# Generated by Django 5.2.12 on 2026-05-07 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ppequipment_app", "0003_alter_equipment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "verbose_name": "Местоположение ПТД",
                "verbose_name_plural": "Местоположения ПТД",
            },
        ),
        migrations.AlterField(
            model_name="location",
            name="equipment",
            field=models.ForeignKey(
                db_column="номер",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="ppequipment_app.equipment",
                verbose_name="ПТД",
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                db_column="номер",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verifications",
                to="ppequipment_app.equipment",
                verbose_name="ПТД",
            ),
        ),
    ]
