# Generated by Django 5.2.12 on 2026-05-07 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ppequipment_app",
            "0004_alter_location_options_alter_location_equipment_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="verification_date",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verifications_date",
                to="ppequipment_app.verificationdate",
                verbose_name="Дата сверки",
            ),
        ),
        migrations.AddField(
            model_name="verificationdate",
            name="verification_responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
