# Generated by Django 5.2.12 on 2026-05-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ppequipment_app", "0005_verification_verification_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="location_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата перемещения"
            ),
        ),
    ]
