# Generated by Django 5.2.12 on 2026-06-18 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ppequipment_app", "0007_alter_verificationdate_verification_responsible"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "ordering": ["number"],
                "verbose_name": "Производственно-техническая документация",
                "verbose_name_plural": "Производственно-техническая документация",
            },
        ),
    ]
