# Generated by Django 5.0.1 on 2024-03-14 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hrdepartment_app", "0069_alter_officialmemo_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WayBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(max_length=100, verbose_name="Номер документа"),
                ),
                ("document_date", models.DateField(verbose_name="Дата документа")),
                (
                    "date_of_creation",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        max_length=100,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="way_bill_executor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "place_of_departure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="way_bill_place_of_departure",
                        to="hrdepartment_app.placeproductionactivity",
                        verbose_name="Место отправления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транспортная накладная",
                "verbose_name_plural": "Транспортные накладные",
                "ordering": ["-date_of_creation"],
            },
        ),
    ]
