# Generated by Django 5.0.1 on 2024-03-18 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logistics_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waybill",
            options={},
        ),
        migrations.RemoveField(
            model_name="waybill",
            name="date_of_creation",
        ),
        migrations.RemoveField(
            model_name="waybill",
            name="document_date",
        ),
        migrations.RemoveField(
            model_name="waybill",
            name="document_number",
        ),
        migrations.RemoveField(
            model_name="waybill",
            name="executor",
        ),
        migrations.RemoveField(
            model_name="waybill",
            name="place_of_departure",
        ),
    ]
