# Generated by Django 5.0.3 on 2024-03-18 10:35

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0047_alter_databaseuser_options"),
        ("hrdepartment_app", "0069_alter_officialmemo_options"),
        ("logistics_app", "0002_alter_waybill_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waybill",
            options={
                "ordering": ["-date_of_creation"],
                "verbose_name": "Транспортная накладная",
                "verbose_name_plural": "Транспортные накладные",
            },
        ),
        migrations.AddField(
            model_name="waybill",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AddField(
            model_name="waybill",
            name="date_of_creation",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата и время создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="waybill",
            name="document_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата документа"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="waybill",
            name="document_number",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 3, 18, 10, 35, 9, 626419, tzinfo=datetime.timezone.utc
                ),
                max_length=100,
                verbose_name="Номер документа",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="waybill",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="way_bill_executor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AddField(
            model_name="waybill",
            name="place_division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customers_app.division",
                verbose_name="Подразделение",
            ),
        ),
        migrations.AddField(
            model_name="waybill",
            name="place_of_departure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="way_bill_place_of_departure",
                to="hrdepartment_app.placeproductionactivity",
                verbose_name="Куда",
            ),
        ),
        migrations.AddField(
            model_name="waybill",
            name="state",
            field=models.CharField(
                choices=[
                    (0, "Не обработана"),
                    (1, "Обработана"),
                    (2, "Отправлена"),
                    (3, "Принята"),
                    (4, "Отклонена"),
                ],
                default=0,
                max_length=100,
                verbose_name="Состояние",
            ),
        ),
    ]
