# Generated by Django 5.0.3 on 2024-03-19 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics_app", "0003_alter_waybill_options_waybill_comment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="waybill",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="way_bill_responsible",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Получение",
            ),
        ),
    ]
