# Generated by Django 5.0.3 on 2024-03-30 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics_app", "0004_waybill_responsible"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="waybill",
            name="content",
            field=models.CharField(
                default="", max_length=300, verbose_name="Содержание"
            ),
        ),
        migrations.AddField(
            model_name="waybill",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="way_bill_sender",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AlterField(
            model_name="waybill",
            name="document_number",
            field=models.CharField(
                default=uuid.uuid4, max_length=37, verbose_name="Номер документа"
            ),
        ),
    ]
