# Generated by Django 5.0.3 on 2024-04-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics_app", "0006_alter_waybill_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="waybill",
            name="urgency",
            field=models.CharField(
                choices=[("0", "Не срочно"), ("1", "Срочно"), ("2", "Очень срочно")],
                default="0",
                max_length=100,
                verbose_name="Срочность",
            ),
        ),
    ]
