# Generated by Django 5.0.3 on 2024-04-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics_app", "0007_waybill_urgency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waybill",
            name="comment",
            field=models.CharField(
                default="", max_length=300, verbose_name="Комментарий"
            ),
        ),
    ]
