# Generated by Django 5.0.3 on 2024-04-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics_app", "0009_alter_waybill_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_creation",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "way_bill",
                    models.ManyToManyField(
                        to="logistics_app.waybill",
                        verbose_name="Транспортная накладная",
                    ),
                ),
            ],
            options={
                "verbose_name": "Посылка",
                "verbose_name_plural": "Посылки",
                "ordering": ["-date_of_creation"],
            },
        ),
    ]
