# Generated by Django 5.0.3 on 2024-04-25 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logistics_app", "0010_package"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="way_bill",
        ),
    ]
