# Generated by Django 5.0.3 on 2024-04-25 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0093_creatingteam_email_cancellation_send"),
        ("logistics_app", "0011_remove_package_way_bill"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="date_of_dispatch",
            field=models.DateField(blank=True, null=True, verbose_name="Дата отправки"),
        ),
        migrations.AddField(
            model_name="package",
            name="number_of_dispatch",
            field=models.CharField(
                default="", max_length=37, verbose_name="Номер посылки"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="place_of_dispatch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hrdepartment_app.placeproductionactivity",
                verbose_name="Куда отправляется",
            ),
        ),
        migrations.AddField(
            model_name="waybill",
            name="package_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="logistics_app.package",
                verbose_name="Посылка",
            ),
        ),
    ]
