# Generated by Django 5.0.3 on 2024-04-27 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logistics_app", "0014_package_type_of_dispatch"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={
                "ordering": ["-date_of_dispatch"],
                "verbose_name": "Посылка",
                "verbose_name_plural": "Посылки",
            },
        ),
    ]
