# Generated by Django 5.0.3 on 2024-04-27 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics_app", "0016_packageimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packageimage",
            options={
                "ordering": ["-date_of_creation"],
                "verbose_name": "Фотографию к посылке",
                "verbose_name_plural": "Фотографии к посылкам",
            },
        ),
        migrations.AlterField(
            model_name="packageimage",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="logistics_app.package",
                verbose_name="",
            ),
        ),
    ]
