# Generated by Django 5.0.3 on 2024-05-21 10:50

import logistics_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics_app", "0017_alter_packageimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageimage",
            name="image",
            field=models.ImageField(
                upload_to=logistics_app.models.image_directory_path, verbose_name=""
            ),
        ),
    ]
