# Generated by Django 5.0.6 on 2025-04-04 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0124_operational"),
        ("logistics_app", "0020_alter_waybill_responsible"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="place_of_dispatch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hrdepartment_app.placeproductionactivity",
                verbose_name="Точка назначения",
            ),
        ),
        migrations.AlterField(
            model_name="waybill",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="way_bill_sender",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Инициатор",
            ),
        ),
    ]
