# Generated by Django 5.0.6 on 2026-09-13 18:40

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import logistics_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts_app", "0017_estate_decommission_date"),
        ("customers_app", "0084_rename_customers_a_thumbpr_6f8092_idx_customers_a_thumbpr_3a89e2_idx_and_more"),
        ("logistics_app", "0021_alter_package_place_of_dispatch_alter_waybill_sender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocFlowDocumentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название типа документа")),
                (
                    "category",
                    models.CharField(
                        choices=[("INBOUND", "Входящий"), ("OUTBOUND", "Исходящий"), ("INTERNAL", "Внутренний")],
                        default="INBOUND",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Символьный код")),
                ("description", models.TextField(blank=True, verbose_name="Описание и регламент")),
                (
                    "default_sla_hours",
                    models.PositiveIntegerField(default=24, verbose_name="Срок согласования по умолчанию (в часах)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Тип документа СЭД",
                "verbose_name_plural": "Типы документов СЭД",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="DocFlowNumberCounter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveIntegerField(verbose_name="Год")),
                (
                    "flow_type",
                    models.CharField(
                        choices=[("INBOUND", "Входящий"), ("OUTBOUND", "Исходящий"), ("INTERNAL", "Внутренний")],
                        max_length=20,
                        verbose_name="Тип документооборота",
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0, verbose_name="Последний выданный номер")),
            ],
            options={
                "verbose_name": "Счетчик номеров СЭД",
                "verbose_name_plural": "Счетчики номеров СЭД",
            },
        ),
        migrations.AddConstraint(
            model_name="docflownumbercounter",
            constraint=models.UniqueConstraint(fields=("year", "flow_type"), name="unique_docflow_counter_year_flow"),
        ),
        migrations.CreateModel(
            name="DocFlowDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор UUID",
                    ),
                ),
                (
                    "reg_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Регистрационный номер",
                    ),
                ),
                ("reg_date", models.DateField(blank=True, null=True, verbose_name="Дата регистрации")),
                ("title", models.CharField(max_length=500, verbose_name="Краткое наименование / тема")),
                ("description", models.TextField(blank=True, verbose_name="Содержание / описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("ON_REGISTRATION", "На первичной регистрации"),
                            ("ON_APPROVAL", "На согласовании"),
                            ("ON_REWORK", "На доработке"),
                            ("APPROVED", "Согласован / Принят"),
                            ("SIGNED", "Подписан сторонами"),
                            ("EXECUTED", "Исполнен"),
                            ("REJECTED", "Отклонен"),
                            ("ARCHIVED", "В архиве"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[("INBOUND", "Входящий"), ("OUTBOUND", "Исходящий"), ("INTERNAL", "Внутренний")],
                        default="INBOUND",
                        max_length=20,
                        verbose_name="Поток / Категория",
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[("NORMAL", "Обычная"), ("URGENT", "Срочно"), ("CRITICAL", "Критически срочно")],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="Срочность",
                    ),
                ),
                (
                    "counteragent_contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email контрагента для уведомлений"),
                ),
                ("current_step_order", models.PositiveIntegerField(default=1, verbose_name="Порядок текущего этапа")),
                ("deadline", models.DateTimeField(blank=True, null=True, verbose_name="Плановый срок (дедлайн)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения")),
                (
                    "counteragent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docflow_documents",
                        to="customers_app.counteragent",
                        verbose_name="Контрагент",
                    ),
                ),
                (
                    "doc_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="logistics_app.docflowdocumenttype",
                        verbose_name="Тип документа",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="docflow_initiated_docs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Инициатор (Автор)",
                    ),
                ),
                (
                    "related_contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docflow_documents",
                        to="contracts_app.contract",
                        verbose_name="Связанный договор",
                    ),
                ),
                (
                    "related_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docflow_documents",
                        to="logistics_app.package",
                        verbose_name="Связанная посылка",
                    ),
                ),
                (
                    "related_waybill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docflow_documents",
                        to="logistics_app.waybill",
                        verbose_name="Связанная накладная",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="docflow_responsible_docs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ СЭД",
                "verbose_name_plural": "Документы СЭД",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocFlowFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Название документа / файла")),
                ("is_main", models.BooleanField(default=True, verbose_name="Основной файл документа")),
                ("current_version_number", models.CharField(default="1.0", max_length=20, verbose_name="Текущая версия")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="logistics_app.docflowdocument",
                        verbose_name="Документ СЭД",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл документа СЭД",
                "verbose_name_plural": "Файлы документов СЭД",
                "ordering": ["-is_main", "title"],
            },
        ),
        migrations.CreateModel(
            name="DocFlowFileVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_number", models.CharField(max_length=20, verbose_name="Номер версии (например, 1.0, 1.1)")),
                ("file", models.FileField(upload_to=logistics_app.models.docflow_file_upload_to, verbose_name="Физический файл")),
                ("file_size", models.PositiveBigIntegerField(default=0, verbose_name="Размер файла (байт)")),
                ("file_hash", models.CharField(blank=True, max_length=64, verbose_name="Контрольная сумма SHA-256")),
                ("change_comment", models.TextField(blank=True, verbose_name="Комментарий к версии / замечания")),
                ("is_reviewer_edit", models.BooleanField(default=False, verbose_name="Правка согласующего лица")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время загрузки")),
                (
                    "doc_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="logistics_app.docflowfile",
                        verbose_name="Файл документа",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="docflow_uploaded_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем загружен",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия файла СЭД",
                "verbose_name_plural": "Версии файлов СЭД",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DocFlowRouteTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Наименование шаблона")),
                ("is_default", models.BooleanField(default=True, verbose_name="Использовать по умолчанию для типа")),
                ("description", models.TextField(blank=True, verbose_name="Описание маршрута")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "doc_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_templates",
                        to="logistics_app.docflowdocumenttype",
                        verbose_name="Тип документа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон маршрута СЭД",
                "verbose_name_plural": "Шаблоны маршрутов СЭД",
                "ordering": ["doc_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="DocFlowRouteStepTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step_order", models.PositiveIntegerField(default=1, verbose_name="Порядковый номер этапа")),
                ("step_name", models.CharField(max_length=255, verbose_name="Название этапа")),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("SEQUENTIAL", "Последовательный (Один сотрудник)"),
                            ("PARALLEL_AND", "Параллельный «И» (Все должны согласовать)"),
                            ("PARALLEL_OR", "Параллельный «ИЛИ» (Любой из группы)"),
                            ("HEAD_OF_DEPARTMENT", "Руководитель подразделения автора"),
                        ],
                        default="SEQUENTIAL",
                        max_length=25,
                        verbose_name="Тип этапа",
                    ),
                ),
                ("sla_hours", models.PositiveIntegerField(default=24, verbose_name="Срок на рассмотрение (в часах)")),
                (
                    "allow_reviewer_file_edit",
                    models.BooleanField(default=True, verbose_name="Разрешить согласующему загружать файл с правками"),
                ),
                ("can_rollback_to", models.BooleanField(default=True, verbose_name="Разрешить откат на данный шаг")),
                (
                    "assigned_division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docflow_step_templates",
                        to="customers_app.division",
                        verbose_name="Назначенное подразделение",
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docflow_user_step_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Назначенный сотрудник",
                    ),
                ),
                (
                    "assigned_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="docflow_parallel_step_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Группа согласующих сотрудников",
                    ),
                ),
                (
                    "route_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="logistics_app.docflowroutetemplate",
                        verbose_name="Шаблон маршрута",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаг шаблона маршрута СЭД",
                "verbose_name_plural": "Шаги шаблонов маршрутов СЭД",
                "ordering": ["route_template", "step_order"],
            },
        ),
        migrations.CreateModel(
            name="DocFlowRouteStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step_order", models.PositiveIntegerField(default=1, verbose_name="Порядковый номер этапа")),
                ("step_name", models.CharField(max_length=255, verbose_name="Название этапа")),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("SEQUENTIAL", "Последовательный (Один сотрудник)"),
                            ("PARALLEL_AND", "Параллельный «И» (Все должны согласовать)"),
                            ("PARALLEL_OR", "Параллельный «ИЛИ» (Любой из группы)"),
                            ("HEAD_OF_DEPARTMENT", "Руководитель подразделения автора"),
                        ],
                        default="SEQUENTIAL",
                        max_length=25,
                        verbose_name="Тип этапа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает очереди"),
                            ("IN_PROGRESS", "В процессе согласования"),
                            ("APPROVED", "Согласован"),
                            ("RETURNED", "Возвращен на доработку / Шаг отката"),
                            ("REJECTED", "Отклонен"),
                            ("SKIPPED", "Пропущен"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="Статус шага",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Время поступления на этап")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Время завершения этапа")),
                ("due_date", models.DateTimeField(blank=True, null=True, verbose_name="Дедлайн этапа")),
                ("sla_hours", models.PositiveIntegerField(default=24, verbose_name="Нормативный срок SLA (в часах)")),
                ("can_rollback_to", models.BooleanField(default=True, verbose_name="Доступен ли шаг для целевого отката")),
                (
                    "allow_reviewer_file_edit",
                    models.BooleanField(default=True, verbose_name="Разрешить согласующему загружать файл с правками"),
                ),
                (
                    "approved_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="docflow_step_approved_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудники, фактически согласовавшие шаг",
                    ),
                ),
                (
                    "assigned_division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docflow_route_steps",
                        to="customers_app.division",
                        verbose_name="Назначенное подразделение",
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docflow_route_user_steps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Назначенный сотрудник",
                    ),
                ),
                (
                    "assigned_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="docflow_route_parallel_steps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Назначенные согласующие (группа)",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_steps",
                        to="logistics_app.docflowdocument",
                        verbose_name="Документ СЭД",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаг маршрута согласования СЭД",
                "verbose_name_plural": "Шаги маршрутов согласования СЭД",
                "ordering": ["document", "step_order"],
            },
        ),
        migrations.CreateModel(
            name="DocFlowApprovalLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Документ зарегистрирован"),
                            ("STARTED", "Маршрут согласования запущен"),
                            ("APPROVED", "Согласовано (Виза наложена)"),
                            ("APPROVED_WITH_COMMENTS", "Согласовано с замечаниями / правками"),
                            ("RETURNED_TO_AUTHOR", "Возвращено автору на доработку"),
                            ("ROLLBACK_TO_STEP", "Откат на предыдущий шаг"),
                            ("REJECTED", "Документ отклонен"),
                            ("DELEGATED", "Шаг делегирован другому сотруднику"),
                            ("RESTARTED", "Маршрут возобновлен / перезапущен"),
                            ("NEW_VERSION_UPLOADED", "Загружена новая версия файла"),
                            ("COMMENTED", "Добавлен комментарий"),
                        ],
                        max_length=35,
                        verbose_name="Действие",
                    ),
                ),
                ("target_step_order", models.PositiveIntegerField(blank=True, null=True, verbose_name="Целевой шаг при откате")),
                ("comment", models.TextField(blank=True, verbose_name="Резолюция / Замечания / Особое мнение")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Время совершения действия")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP-адрес пользователя")),
                ("user_agent", models.CharField(blank=True, max_length=500, verbose_name="Клиентское приложение (User Agent)")),
                ("pep_signature_hash", models.CharField(blank=True, max_length=128, verbose_name="Цифровой хэш ПЭП (SHA-256)")),
                ("pep_certificate_id", models.CharField(blank=True, max_length=64, verbose_name="Идентификатор сертификата ПЭП")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_logs",
                        to="logistics_app.docflowdocument",
                        verbose_name="Документ СЭД",
                    ),
                ),
                (
                    "route_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="logistics_app.docflowroutestep",
                        verbose_name="Связанный шаг маршрута",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="docflow_action_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник (автор действия)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись аудита и визирования СЭД",
                "verbose_name_plural": "Журнал аудита и визирования СЭД",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocFlowComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="Текст сообщения / обсуждения")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время отправки")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="docflow_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор комментария",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="logistics_app.docflowdocument",
                        verbose_name="Документ СЭД",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="logistics_app.docflowcomment",
                        verbose_name="Родительский комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к документу СЭД",
                "verbose_name_plural": "Комментарии к документам СЭД",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="docflowdocument",
            index=models.Index(fields=["status", "flow_type"], name="idx_docflow_status_flow"),
        ),
        migrations.AddIndex(
            model_name="docflowdocument",
            index=models.Index(fields=["initiator", "status"], name="idx_docflow_init_status"),
        ),
        migrations.AddIndex(
            model_name="docflowdocument",
            index=models.Index(fields=["responsible", "status"], name="idx_docflow_resp_status"),
        ),
        migrations.AddIndex(
            model_name="docflowdocument",
            index=models.Index(fields=["reg_date", "status"], name="idx_docflow_date_status"),
        ),
        migrations.AddConstraint(
            model_name="docflowroutesteptemplate",
            constraint=models.UniqueConstraint(fields=("route_template", "step_order"), name="unique_template_step_order"),
        ),
        migrations.AddIndex(
            model_name="docflowroutestep",
            index=models.Index(fields=["document", "status", "step_order"], name="idx_docstep_doc_stat_order"),
        ),
        migrations.AddIndex(
            model_name="docflowapprovallog",
            index=models.Index(fields=["document", "created_at"], name="idx_doclog_doc_created"),
        ),
    ]
