# Generated by Django 5.2 on 2026-08-31 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, verbose_name="Корпоративный Email"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Имя отправителя",
                    ),
                ),
                (
                    "imap_host",
                    models.CharField(
                        default="imap.barkol.ru",
                        max_length=255,
                        verbose_name="Сервер IMAP",
                    ),
                ),
                (
                    "imap_port",
                    models.IntegerField(default=993, verbose_name="Порт IMAP"),
                ),
                (
                    "imap_use_ssl",
                    models.BooleanField(default=True, verbose_name="IMAP SSL"),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        default="sm.barkol.ru",
                        max_length=255,
                        verbose_name="Сервер SMTP",
                    ),
                ),
                (
                    "smtp_port",
                    models.IntegerField(default=465, verbose_name="Порт SMTP"),
                ),
                (
                    "smtp_use_ssl",
                    models.BooleanField(default=True, verbose_name="SMTP SSL"),
                ),
                (
                    "smtp_use_tls",
                    models.BooleanField(
                        default=False, verbose_name="SMTP STARTTLS"
                    ),
                ),
                (
                    "encrypted_password",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="Зашифрованный пароль",
                    ),
                ),
                (
                    "signature_html",
                    models.TextField(
                        blank=True, default="", verbose_name="Подпись (HTML)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлен"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail_account",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Почтовый аккаунт",
                "verbose_name_plural": "Почтовые аккаунты",
                "ordering": ["user__last_name", "email"],
            },
        ),
    ]
