# Generated by Django on 2026-08-31 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailbox_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Имя / Организация",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, verbose_name="Email адрес"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Вручную"),
                            ("auto", "Автоматически из переписки"),
                        ],
                        default="auto",
                        max_length=32,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлен"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail_contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Почтовый контакт",
                "verbose_name_plural": "Почтовые контакты (Адресная книга)",
                "ordering": ["name", "email"],
                "unique_together": {("user", "email")},
            },
        ),
    ]
