# Generated by Django migration for Mailbox.work_application_password

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailbox_app", "0006_mailtemplate_mailprintsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailbox",
            name="work_application_password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Пароль от почтового ящика на внешнем хостинге ISPManager (Reg.ru), используемый для авторизации в «Доставка SMTP» (SMTP AUTH) и «Загрузка POP3»",
                max_length=255,
                verbose_name="Внешний пароль (ISPManager / Доставка SMTP)",
            ),
        ),
    ]
