# Generated by Django 4.1 on 2022-08-30 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import library_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts_app', '0027_alter_typecontract_type_contract_and_more'),
        ('customers_app', '0043_counteragent_ref_key_databaseuser_ref_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_key', models.CharField(default='', max_length=37, verbose_name='Уникальный номер')),
                ('date_entry', models.DateField(auto_now_add=True, verbose_name='Дата ввода информации')),
                ('document_date', models.DateField(default='', verbose_name='Дата документа')),
                ('document_number', models.CharField(default='', max_length=10, verbose_name='Номер документа')),
                ('doc_file', models.FileField(blank=True, upload_to=library_app.models.document_directory_path, verbose_name='Файл документа')),
                ('allowed_placed', models.BooleanField(default=False, verbose_name='Разрешение на публикацию')),
                ('validity_period_start', models.DateField(default='', verbose_name='Документ действует с')),
                ('validity_period_end', models.DateField(default='', verbose_name='Документ действует по')),
                ('actuality', models.BooleanField(default=False, verbose_name='Актуальность')),
                ('previous_document', models.URLField(verbose_name='Предшествующий документ')),
                ('access', models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.accesslevel', verbose_name='Уровень доступа к документу')),
                ('document_division', models.ManyToManyField(to='customers_app.division', verbose_name='Принадлежность к подразделению')),
                ('employee', models.ManyToManyField(blank=True, related_name='document_employee', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('type_of_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts_app.typedocuments', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
