# Generated by Django 4.1.6 on 2023-02-13 00:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers_app', '0010_division_destination_point'),
        ('contracts_app', '0002_initial'),
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='DocumentsJobDescription',
        ),
        migrations.AlterModelOptions(
            name='documentsjobdescription',
            options={'verbose_name': 'Должностная инструкция', 'verbose_name_plural': 'Должностные инструкции'},
        ),
    ]
