# Generated by Django 4.1 on 2022-08-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_documents_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='previous_document',
            field=models.URLField(blank=True, verbose_name='Предшествующий документ'),
        ),
    ]
