# Generated by Django 4.2 on 2023-04-24 09:31

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_helptopic_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': 'Хэштэг', 'verbose_name_plural': 'Хэштэги'},
        ),
        migrations.AlterModelOptions(
            name='helpcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='helptopic',
            options={'verbose_name': 'Топик', 'verbose_name_plural': 'Топики'},
        ),
        migrations.AlterField(
            model_name='helptopic',
            name='hash_tag',
            field=models.ManyToManyField(blank=True, to='library_app.hashtag'),
        ),
        migrations.AlterField(
            model_name='helptopic',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Содержание'),
        ),
    ]
