# Generated by Django 4.1.7 on 2023-03-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_documentsjobdescription_scan_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsorder',
            name='document_division',
        ),
    ]
