# Generated by Django 4.1.6 on 2023-02-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0011_posts_post_date_end_posts_post_date_start_and_more'),
        ('library_app', '0003_remove_documentsjobdescription_document_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsjobdescription',
            name='document_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.job', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='documentsjobdescription',
            name='document_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.division', verbose_name='Подразделение'),
        ),
    ]
