# Generated by Django 4.1.7 on 2023-03-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_remove_documentsorder_document_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsorder',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Утверждён'),
        ),
    ]
