# Generated by Django 4.1 on 2022-08-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_documents_previous_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='document_name',
            field=models.CharField(default='', max_length=200, verbose_name='Наименование документа'),
        ),
    ]
