# Generated by Django 4.1.7 on 2023-03-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_documentsorder_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsorder',
            name='type_of_document',
        ),
    ]
