# Generated by Django 4.1.7 on 2023-03-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_remove_documentsorder_type_of_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsjobdescription',
            name='type_of_document',
        ),
    ]
