# Generated by Django 4.1 on 2022-08-31 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_documents_ref_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='ref_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Уникальный номер'),
        ),
    ]
