# Generated by Django 4.1.6 on 2023-02-15 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_documentsjobdescription_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsjobdescription',
            name='document_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_app.documentsorder', verbose_name='Приказ'),
        ),
    ]
