# Generated by Django 5.0.3 on 2024-04-10 09:25

import library_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0005_documentform_employee_documentform_executor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentform",
            name="sample",
            field=models.FileField(
                blank=True,
                upload_to=library_app.models.sample_directory_path,
                verbose_name="Образец заполнения",
            ),
        ),
    ]
