# Generated by Django 5.0.3 on 2024-04-11 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0047_alter_databaseuser_options"),
        ("library_app", "0006_alter_documentform_sample"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentform",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customers_app.division",
                verbose_name="Подразделение",
            ),
        ),
    ]
