# Generated by Django 5.0.3 on 2024-04-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0047_alter_databaseuser_options"),
        ("library_app", "0008_remove_documentform_division_documentform_division"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentform",
            name="division",
            field=models.ManyToManyField(
                blank=True, to="customers_app.division", verbose_name="Подразделение"
            ),
        ),
    ]
