# Generated by Django 5.0.6 on 2024-10-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0009_alter_documentform_division"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentform",
            name="draft_visible",
            field=models.BooleanField(
                default=False, verbose_name="Показывать черновик"
            ),
        ),
    ]
