# Generated by Django 5.0.6 on 2024-11-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0011_contest_poem_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poem",
            name="content",
            field=models.TextField(verbose_name="Содержание стиха"),
        ),
        migrations.AlterField(
            model_name="poem",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название стиха"),
        ),
    ]
