# Generated by Django 5.0.6 on 2024-11-26 17:51

import library_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0013_companyevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyevent",
            name="event_media",
            field=models.FileField(
                blank=True,
                upload_to=library_app.models.event_media_directory_path,
                verbose_name="Медиафайл",
            ),
        ),
        migrations.AlterField(
            model_name="companyevent",
            name="event_report",
            field=models.FileField(
                blank=True,
                upload_to=library_app.models.event_report_directory_path,
                verbose_name="Отчёт по встрече",
            ),
        ),
    ]
