# Generated by Django 5.0.6 on 2024-11-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0014_alter_companyevent_event_media_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyevent",
            name="event_video",
            field=models.URLField(blank=True, verbose_name="Видео"),
        ),
    ]
