# Generated by Django 5.0.6 on 2024-12-01 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0015_companyevent_event_video"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contest",
            options={"verbose_name": "Конкурс", "verbose_name_plural": "Конкурсы"},
        ),
        migrations.AlterModelOptions(
            name="poem",
            options={"verbose_name": "Стих", "verbose_name_plural": "Стихи"},
        ),
        migrations.AlterModelOptions(
            name="vote",
            options={"verbose_name": "Голос", "verbose_name_plural": "Голоса"},
        ),
    ]
