# Generated by Django 5.0.6 on 2024-12-11 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0016_alter_contest_options_alter_poem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyevent",
            options={
                "ordering": ["-event_date"],
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
            },
        ),
    ]
