# Generated by Django 5.0.6 on 2025-07-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0017_alter_companyevent_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="documentform",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
