# Generated by Django 5.2.12 on 2026-04-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0018_companyevent_updated_at_documentform_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="helptopic",
            name="custom_css",
            field=models.TextField(blank=True),
        ),
    ]
