# Generated by Django 4.1.6 on 2023-02-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuserworkprofile',
            name='ref_key',
            field=models.CharField(default='', max_length=37, verbose_name='Уникальный номер'),
        ),
    ]
