# Generated by Django 4.0.5 on 2022-06-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, verbose_name='возраст'),
        ),
    ]
