# Generated by Django 4.1.5 on 2023-01-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0002_remove_harmfulworkingconditions_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmfulworkingconditions',
            name='code',
            field=models.CharField(default='', max_length=9, verbose_name='Код'),
        ),
    ]
