# Generated by Django 4.1.5 on 2023-01-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0004_alter_counteragent_ogrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuser',
            name='person_ref_key',
            field=models.CharField(default='', max_length=37, verbose_name='Уникальный номер'),
        ),
    ]
