# Generated by Django 4.1.6 on 2023-02-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0004_databaseuserworkprofile_service_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseuserworkprofile',
            name='service_number',
        ),
    ]
