# Generated by Django 4.0.5 on 2022-07-05 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('customers_app', '0005_accesslevel_country_division_job_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseuser',
            name='access_right',
            field=models.ManyToManyField(blank=True, default=0, to='customers_app.accesslevel',
                                         verbose_name='права доступа'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='customers_app.address'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='corp_phone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='corp', to='customers_app.phonenumber',
                                       verbose_name='корпоративный номер'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'мужской'), ('female', 'женский')], default='',
                                   max_length=7, null=True, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='phone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='cell', to='customers_app.phonenumber',
                                       verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='type_users',
            field=models.CharField(blank=True, choices=[('natural_person', 'физическое лицо'),
                                                        ('staff_member', 'штатный сотрудник'),
                                                        ('freelancer', 'внештатный сотрудник')], max_length=40,
                                   null=True, verbose_name='тип пользователя'),
        ),
        migrations.CreateModel(
            name='Counteragent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='', max_length=150, verbose_name='Наименование')),
                ('full_name', models.CharField(default='', max_length=250, verbose_name='Полное наименование')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('type_counteragent', models.CharField(
                    choices=[('juridical_person', 'юридическое лицо'), ('physical_person', 'физическое лицо'),
                             ('separate_subdivision', 'обособленное подразделение'),
                             ('government_agency', 'государственный орган')], max_length=40,
                    verbose_name='Тип контрагента')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('base_counteragent', models.BooleanField(default=False, verbose_name='Основная организация')),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='account', to=settings.AUTH_USER_MODEL,
                                                 verbose_name='Бухгалтер')),
                ('contact_person',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='contact', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Контактное лицо')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='direct', to=settings.AUTH_USER_MODEL,
                                               verbose_name='Директор')),
                ('juridical_address',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juridical',
                                   to='customers_app.address', verbose_name='Юридический адрес')),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            to='customers_app.phonenumber', verbose_name='Номер телефона')),
                ('physical_address',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical',
                                   to='customers_app.address', verbose_name='Физический адрес')),
            ],
        ),
    ]
