# Generated by Django 4.1.5 on 2023-02-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0006_alter_databaseuser_person_ref_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuserworkprofile',
            name='work_email_password',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Пароль от корпоративной почты'),
        ),
    ]
