# Generated by Django 4.1.6 on 2023-02-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0007_alter_division_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseuserworkprofile',
            name='work_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Рабочий email'),
        ),
    ]
