# Generated by Django 4.1.5 on 2023-02-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0007_databaseuserworkprofile_work_email_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='right_to_approval',
            field=models.BooleanField(default=False, verbose_name='Имеет право на согласование'),
        ),
    ]
