# Generated by Django 4.0.5 on 2022-07-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0007_address_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='history',
            field=models.DateField(auto_created=True, null=True, verbose_name='Дата создания'),
        ),
    ]
