# Generated by Django 4.1.6 on 2023-02-23 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('customers_app', '0008_alter_databaseuserworkprofile_work_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuserprofile',
            name='ref_key',
            field=models.CharField(default='', max_length=37, verbose_name='Уникальный номер'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to='customers_app.databaseuserprofile',
                                       verbose_name='Личный профиль пользователя'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='user_work_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to='customers_app.databaseuserworkprofile',
                                       verbose_name='Рабочий профиль пользователя'),
        ),
    ]
