# Generated by Django 4.0.5 on 2022-07-14 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0008_division_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseuser',
            name='works',
        ),
        migrations.AddField(
            model_name='databaseuser',
            name='divisions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.division', verbose_name='подразделение'),
        ),
        migrations.AddField(
            model_name='databaseuser',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.job', verbose_name='должность'),
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
