# Generated by Django 4.1.7 on 2023-02-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0009_databaseuserprofile_ref_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='type_of_role',
            field=models.CharField(blank=True, choices=[('0', 'Общий'), ('1', 'НО'), ('2', 'Кадры'), ('3', 'Бухгалтерия')], max_length=11, null=True, verbose_name='Роль подразделения'),
        ),
    ]
