# Generated by Django 4.1.5 on 2023-02-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0009_division_type_of_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='destination_point',
            field=models.BooleanField(default=False, verbose_name='Используется как место назначения'),
        ),
    ]
