# Generated by Django 4.1.7 on 2023-02-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0010_alter_division_type_of_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type_of_job',
            field=models.CharField(blank=True, choices=[('0', 'Общий состав'), ('1', 'Летный состав'), ('2', 'Инженерный состав')], max_length=17, null=True, verbose_name='Принадлежность'),
        ),
    ]
