# Generated by Django 4.0.5 on 2022-07-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0010_remove_databaseuser_corp_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_created=True, verbose_name='Дата создания')),
                ('post_description', models.TextField(blank=True, verbose_name='Текст поста')),
            ],
        ),
    ]
