# Generated by Django 4.1.6 on 2023-02-15 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0010_division_destination_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания отображения'),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала отображения'),
        ),
        migrations.AddField(
            model_name='posts',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_person', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо'),
        ),
    ]
