# Generated by Django 4.1.6 on 2023-02-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0011_posts_post_date_end_posts_post_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='address',
            field=models.CharField(default='', max_length=250, verbose_name='Адрес'),
        ),
    ]
