# Generated by Django 4.0.5 on 2022-07-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customers_app', '0011_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_divisions',
            field=models.ManyToManyField(to='customers_app.division', verbose_name='Подразделения поста'),
        ),
    ]
