# Generated by Django 4.1.7 on 2023-03-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customers_app', '0011_job_type_of_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='group',
            field=models.ManyToManyField(to='auth.group', verbose_name='Группы должности'),
        ),
    ]
