# Generated by Django 4.0.6 on 2022-07-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0013_merge_20220715_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
