# Generated by Django 4.1.7 on 2023-03-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0013_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='group',
            field=models.ManyToManyField(to='customers_app.groups', verbose_name='Группы должности'),
        ),
    ]
