# Generated by Django 4.0.6 on 2022-07-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customers_app', '0014_delete_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslevel',
            options={'verbose_name': 'Уровень доступа', 'verbose_name_plural': 'Уровни доступа'},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='counteragent',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='databaseuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения организации'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Страна'),
        ),
    ]
