# Generated by Django 4.0.5 on 2022-07-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customers_app', '0015_alter_accesslevel_options_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='juridical_address',
            field=models.TextField(blank=True, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='physical_address',
            field=models.TextField(blank=True, null=True, verbose_name='Физический адрес'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
