# Generated by Django 4.1.7 on 2023-03-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0015_databaseuser_user_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseuser',
            name='access_level',
            field=models.CharField(default='', max_length=37, verbose_name='Права доступа'),
        ),
    ]
