# Generated by Django 4.0.6 on 2022-07-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0016_remove_city_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslevel',
            name='name',
            field=models.CharField(blank=True, max_length=25, verbose_name=''),
        ),
    ]
