# Generated by Django 4.1.7 on 2023-03-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0016_alter_databaseuser_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseuser',
            name='access_level',
            field=models.CharField(max_length=1),
        ),
    ]
