# Generated by Django 4.0.6 on 2022-07-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0017_accesslevel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevel',
            name='name',
            field=models.CharField(blank=True, max_length=26, verbose_name=''),
        ),
    ]
