# Generated by Django 4.1.7 on 2023-03-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0017_alter_databaseuser_access_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseuser',
            name='access_level',
        ),
    ]
