# Generated by Django 4.0.6 on 2022-08-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0019_remove_databaseuser_access_right_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='allowed_placed',
            field=models.BooleanField(default=False, verbose_name='Разрешение на публикацию'),
        ),
    ]
