# Generated by Django 4.1.7 on 2023-03-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0020_remove_databaseuserworkprofile_work_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseuserprofile',
            name='passport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.identitydocuments', verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='identitydocuments',
            name='series',
            field=models.CharField(default='', max_length=5, verbose_name='Серия'),
        ),
    ]
