# Generated by Django 4.0.6 on 2022-08-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0020_posts_allowed_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
