# Generated by Django 4.0.6 on 2022-08-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0021_alter_posts_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contracts_access_view', models.CharField(blank=True, choices=[('0', 'Административный доступ'), ('1', 'Особой важности'), ('2', 'Совершенно секретные'), ('3', 'Секретные'), ('4', 'Для служебного пользования')], default='4', max_length=1, null=True, verbose_name='Уровень доступа к договорам')),
                ('contracts_access_add', models.BooleanField(default=False, verbose_name='Разрешение на создание договора')),
                ('contracts_access_edit', models.BooleanField(default=False, verbose_name='Разрешение на редактирование договора')),
                ('contracts_access_agreement', models.BooleanField(default=False, verbose_name='Право на публикацию договора')),
            ],
            options={
                'verbose_name': 'Уровень доступа пользователя',
                'verbose_name_plural': 'Уровни доступа пользователей',
            },
        ),
    ]
