# Generated by Django 4.1.7 on 2023-03-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0021_alter_databaseuserprofile_passport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseuserprofile',
            name='passport',
        ),
        migrations.AddField(
            model_name='databaseuserprofile',
            name='passport',
            field=models.ManyToManyField(blank=True, null=True, to='customers_app.identitydocuments', verbose_name='Паспорт'),
        ),
    ]
