# Generated by Django 4.1 on 2022-08-19 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0024_useraccessmode_guide_access_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counteragent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='access_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.useraccessmode', verbose_name='Права доступа'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='access_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.accesslevel', verbose_name='Права доступа'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='divisions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.division', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'мужской'), ('female', 'женский')], default='', max_length=7, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.job', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='surname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='type_users',
            field=models.CharField(blank=True, choices=[('natural_person', 'физическое лицо'), ('staff_member', 'штатный сотрудник'), ('freelancer', 'внештатный сотрудник')], max_length=40, null=True, verbose_name='Тип пользователя'),
        ),
    ]
