# Generated by Django 4.1.7 on 2023-03-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0024_remove_databaseuserprofile_passport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuser',
            name='passphrase',
            field=models.CharField(default='', max_length=256, verbose_name='Парольная фраза'),
        ),
    ]
