# Generated by Django 4.1.7 on 2023-03-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0025_databaseuser_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseuser',
            name='passphrase',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Парольная фраза'),
        ),
    ]
