# Generated by Django 4.0.6 on 2022-08-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0025_alter_counteragent_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=26, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='juridical_address',
            field=models.TextField(blank=True, default='', verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='kpp',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Корпоративный номер телефона'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='physical_address',
            field=models.TextField(blank=True, default='', verbose_name='Физический адрес'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='type_counteragent',
            field=models.CharField(choices=[('juridical_person', 'юридическое лицо'), ('physical_person', 'физическое лицо'), ('separate_subdivision', 'обособленное подразделение'), ('government_agency', 'государственный орган')], default='', max_length=40, verbose_name='Тип контрагента'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'мужской'), ('female', 'женский')], default='', max_length=7, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='internal_phone',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Внутренний номер телефона'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='personal_phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Личный номер телефона'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='type_users',
            field=models.CharField(blank=True, choices=[('natural_person', 'физическое лицо'), ('staff_member', 'штатный сотрудник'), ('freelancer', 'внештатный сотрудник')], default='', max_length=40, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='work_phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Корпоративный номер телефона'),
        ),
        migrations.AlterField(
            model_name='job',
            name='code',
            field=models.CharField(default='', max_length=5, verbose_name='код должности'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_description',
            field=models.TextField(blank=True, default='', verbose_name='Текст поста'),
        ),
    ]
