# Generated by Django 4.1 on 2022-08-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0026_alter_accesslevel_name_alter_counteragent_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=200, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='useraccessmode',
            name='contracts_access_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts_view', to='customers_app.accesslevel', verbose_name='Уровень доступа к договорам'),
        ),
        migrations.AlterField(
            model_name='useraccessmode',
            name='guide_access_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_view', to='customers_app.accesslevel', verbose_name='Уровень доступа к справочникам'),
        ),
        migrations.AlterField(
            model_name='useraccessmode',
            name='posts_access_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_view', to='customers_app.accesslevel', verbose_name='Уровень доступа к сообщениям'),
        ),
    ]
