# Generated by Django 4.1.7 on 2023-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0026_alter_databaseuser_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_description',
            field=models.TextField(blank=True, default='', verbose_name='Текст сообщения'),
        ),
    ]
