# Generated by Django 4.1.7 on 2023-03-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0027_alter_posts_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telegram ID'),
        ),
    ]
