# Generated by Django 4.1 on 2022-08-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0027_alter_job_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseuser',
            name='access_right',
        ),
    ]
