# Generated by Django 4.1 on 2022-08-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0028_remove_databaseuser_access_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Гражданство пользователя',
                'verbose_name_plural': 'Гражданства пользователей',
            },
        ),
        migrations.CreateModel(
            name='IdentityDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(default='', max_length=4, verbose_name='Серия')),
                ('number', models.CharField(default='', max_length=6, verbose_name='Номер')),
                ('issued_by_whom', models.CharField(default='', max_length=250, verbose_name='Кем выдан')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('division_code', models.CharField(default='', max_length=7, verbose_name='Код подразделения')),
            ],
            options={
                'verbose_name': 'Паспорт пользователя',
                'verbose_name_plural': 'Паспорта пользователей',
            },
        ),
        migrations.CreateModel(
            name='DataBaseUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snils', models.CharField(blank=True, default='', max_length=14, verbose_name='СНИЛС')),
                ('oms', models.CharField(blank=True, default='', max_length=24, verbose_name='Полис ОМС')),
                ('inn', models.CharField(blank=True, default='', max_length=12, verbose_name='ИНН')),
                ('citizenship', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customers_app.citizenships', verbose_name='Гражданство')),
                ('passport', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customers_app.identitydocuments', verbose_name='Паспорт')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
