# Generated by Django 4.1 on 2022-08-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0029_citizenships_identitydocuments_databaseuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuser',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.databaseuserprofile', verbose_name='Личный профиль пользователя'),
        ),
    ]
