# Generated by Django 4.2 on 2023-05-02 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0029_historychange'),
    ]

    operations = [
        migrations.AddField(
            model_name='historychange',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время добавления'),
            preserve_default=False,
        ),
    ]
