# Generated by Django 4.2 on 2023-05-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0030_historychange_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type_of_job',
            field=models.CharField(blank=True, choices=[('0', 'Общий состав'), ('1', 'Летный состав'), ('2', 'Инженерный состав'), ('3', 'Транспортный отдел')], max_length=18, null=True, verbose_name='Принадлежность'),
        ),
    ]
