# Generated by Django 4.1 on 2022-08-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0030_databaseuser_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='access',
        ),
    ]
