# Generated by Django 4.1 on 2022-08-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0031_remove_division_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='hash_view',
        ),
    ]
