# Generated by Django 4.2 on 2023-05-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0032_databaseuserworkprofile_personal_work_schedule_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyBirthdayGreetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_from', models.IntegerField(default=0, max_length=3, verbose_name='')),
                ('age_to', models.IntegerField(default=0, max_length=3, verbose_name='')),
                ('gender', models.CharField(blank=True, choices=[('male', 'мужской'), ('female', 'женский')], default='', max_length=7, verbose_name='Пол')),
                ('greetings', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Поздравление',
                'verbose_name_plural': 'Поздравления',
            },
        ),
    ]
