# Generated by Django 4.1 on 2022-08-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0032_remove_division_hash_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
