# Generated by Django 4.2.1 on 2023-06-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0034_alter_happybirthdaygreetings_age_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='email_send',
            field=models.BooleanField(default=False, verbose_name='Письмо отправлено'),
        ),
    ]
