# Generated by Django 4.1 on 2022-08-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0034_alter_division_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
