# Generated by Django 4.1 on 2022-08-26 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0035_alter_division_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarmfulWorkingConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=5, verbose_name='Код')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('frequency', models.PositiveSmallIntegerField(max_length=1, verbose_name='Периодичность осмотров')),
            ],
            options={
                'verbose_name': 'Вредные условия труда',
                'verbose_name_plural': 'Вредные условия труда',
            },
        ),
        migrations.RemoveField(
            model_name='databaseuser',
            name='divisions',
        ),
        migrations.RemoveField(
            model_name='databaseuser',
            name='internal_phone',
        ),
        migrations.RemoveField(
            model_name='databaseuser',
            name='job',
        ),
        migrations.RemoveField(
            model_name='databaseuser',
            name='work_phone',
        ),
        migrations.AddField(
            model_name='counteragent',
            name='ogrn',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='job',
            name='code',
            field=models.CharField(default='', max_length=5, verbose_name='Код должности'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='DataBaseUserWorkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_employment', models.DateField(blank=True, verbose_name='Дата приема на работу')),
                ('internal_phone', models.CharField(blank=True, default='', max_length=3, verbose_name='Внутренний номер телефона')),
                ('work_phone', models.CharField(blank=True, default='', max_length=15, verbose_name='Корпоративный номер телефона')),
                ('divisions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.division', verbose_name='Подразделение')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.job', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Рабочий профиль пользователя',
                'verbose_name_plural': 'Рабочие профили пользователей',
            },
        ),
        migrations.AddField(
            model_name='databaseuser',
            name='user_work_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.databaseuserworkprofile', verbose_name='Рабочий профиль пользователя'),
        ),
        migrations.AddField(
            model_name='job',
            name='harmful',
            field=models.ManyToManyField(blank=True, to='customers_app.harmfulworkingconditions', verbose_name='Вредные условия труда'),
        ),
    ]
