# Generated by Django 4.2.1 on 2023-06-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0035_posts_email_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='happybirthdaygreetings',
            name='sign',
            field=models.TextField(default='Генеральный директор ООО Авиакомпания "БАРКОЛ" Бархотов В.С. и весь колектив!', verbose_name='Подпись'),
        ),
    ]
