# Generated by Django 4.1 on 2022-08-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0036_harmfulworkingconditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmfulworkingconditions',
            name='frequency',
            field=models.PositiveSmallIntegerField(verbose_name='Периодичность осмотров'),
        ),
    ]
