# Generated by Django 4.2.1 on 2023-06-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0037_alter_happybirthdaygreetings_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happybirthdaygreetings',
            name='sign',
            field=models.TextField(default='Генеральный директор ООО Авиакомпания "БАРКОЛ" Бархотов В.С. и весь коллектив!', verbose_name='Подпись'),
        ),
    ]
