# Generated by Django 4.1 on 2022-08-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0038_identitydocuments_work_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identitydocuments',
            name='work_email',
        ),
        migrations.AddField(
            model_name='databaseuserworkprofile',
            name='work_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Рабочий email'),
        ),
    ]
