# Generated by Django 4.2.1 on 2023-07-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0039_alter_happybirthdaygreetings_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuser',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Наименование'),
        ),
    ]
