# Generated by Django 4.1 on 2022-08-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0039_remove_identitydocuments_work_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counteragent',
            name='ogrn',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='ОГРН'),
        ),
    ]
