# Generated by Django 4.2.1 on 2023-07-21 16:37

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0040_databaseuser_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Содержание'),
        ),
    ]
