# Generated by Django 4.1 on 2022-08-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0041_alter_databaseuserprofile_citizenship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='ref_key',
            field=models.CharField(default='', max_length=37, verbose_name='Уникальный номер'),
        ),
    ]
