# Generated by Django 4.2.1 on 2023-08-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0041_alter_posts_post_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Наименование")),
            ],
            options={
                "verbose_name": "Принадлежность к подразделению",
                "verbose_name_plural": "Принадлежности к подразделению",
            },
        ),
    ]
