# Generated by Django 4.1 on 2022-08-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0042_division_ref_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteragent',
            name='ref_key',
            field=models.CharField(default='', max_length=37, verbose_name='Уникальный номер'),
        ),
        migrations.AddField(
            model_name='databaseuser',
            name='ref_key',
            field=models.CharField(default='', max_length=37, verbose_name='Уникальный номер'),
        ),
        migrations.AddField(
            model_name='identitydocuments',
            name='ref_key',
            field=models.CharField(default='', max_length=37, verbose_name='Уникальный номер'),
        ),
        migrations.AddField(
            model_name='job',
            name='ref_key',
            field=models.CharField(default='', max_length=37, verbose_name='Уникальный номер'),
        ),
    ]
