# Generated by Django 4.1 on 2022-08-30 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0043_counteragent_ref_key_databaseuser_ref_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='code',
            field=models.CharField(default='', max_length=8, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='division',
            name='okved',
            field=models.CharField(default='', max_length=8, verbose_name='Код ОКВЭД2'),
        ),
        migrations.AlterField(
            model_name='division',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.division'),
        ),
    ]
