# Generated by Django 4.2.1 on 2024-01-09 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0043_job_division_affiliation"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Начало отпуска")),
                ("end_date", models.DateField(verbose_name="Конец отпуска")),
                (
                    "type_vacation",
                    models.CharField(
                        choices=[
                            (
                                "dd940e62-cfaf-11e6-bad8-902b345cadc2",
                                "Отпуск за свой счет",
                            ),
                            (
                                "b51bdb10-8fb9-11e9-80cc-309c23d346b4",
                                "Дополнительный оплачиваемый отпуск пострадавшим на ЧАЭС",
                            ),
                            (
                                "c3e8c3e8-cfb6-11e6-bad8-902b345cadc2",
                                "Дополнительный неоплачиваемый отпуск пострадавшим на ЧАЭС",
                            ),
                            (
                                "c3e8c3e7-cfb6-11e6-bad8-902b345cadc2",
                                "Дополнительный учебный отпуск (оплачиваемый)",
                            ),
                            (
                                "dd940e63-cfaf-11e6-bad8-902b345cadc2",
                                "Дополнительный учебный отпуск без оплаты",
                            ),
                            (
                                "6f4631a7-df12-11e6-950a-0cc47a7917f4",
                                "Дополнительный отпуск КЛО, ЗКЛО, начальник ИБП",
                            ),
                            (
                                "56f643c6-bf49-11e9-a3dc-0cc47a7917f4",
                                "Дополнительный оплачиваемый отпуск пострадавшим в аварии на ЧАЭС",
                            ),
                            (
                                "dd940e60-cfaf-11e6-bad8-902b345cadc2",
                                "Дополнительный ежегодный отпуск",
                            ),
                            ("ebbd9c67-cfaf-11e6-bad8-902b345cadc2", "Основной"),
                        ],
                        max_length=100,
                        verbose_name="Тип отпуска",
                    ),
                ),
                (
                    "days",
                    models.IntegerField(default=0, verbose_name="Количество дней"),
                ),
                ("years", models.IntegerField(default=0, verbose_name="Год графика")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание отпусков",
                "verbose_name_plural": "Расписание отпусков",
            },
        ),
    ]
