# Generated by Django 4.2.1 on 2024-01-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0044_vacationschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacationScheduleList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(max_length=100, verbose_name="Номер документа"),
                ),
                (
                    "document_year",
                    models.IntegerField(default=0, verbose_name="Год документа"),
                ),
            ],
        ),
    ]
