# Generated by Django 4.1 on 2022-08-31 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0044_division_code_division_okved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccessmode',
            name='documents_access_add',
            field=models.BooleanField(default=False, verbose_name='Разрешение на создание договора'),
        ),
        migrations.AddField(
            model_name='useraccessmode',
            name='documents_access_agreement',
            field=models.BooleanField(default=False, verbose_name='Право на публикацию договора'),
        ),
        migrations.AddField(
            model_name='useraccessmode',
            name='documents_access_edit',
            field=models.BooleanField(default=False, verbose_name='Разрешение на редактирование договора'),
        ),
        migrations.AddField(
            model_name='useraccessmode',
            name='documents_access_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_view', to='customers_app.accesslevel', verbose_name='Уровень доступа к договорам'),
        ),
        migrations.AlterField(
            model_name='useraccessmode',
            name='contracts_access_add',
            field=models.BooleanField(default=False, verbose_name='Разрешение на создание документа'),
        ),
        migrations.AlterField(
            model_name='useraccessmode',
            name='contracts_access_agreement',
            field=models.BooleanField(default=False, verbose_name='Право на публикацию документа'),
        ),
        migrations.AlterField(
            model_name='useraccessmode',
            name='contracts_access_edit',
            field=models.BooleanField(default=False, verbose_name='Разрешение на редактирование документа'),
        ),
        migrations.AlterField(
            model_name='useraccessmode',
            name='contracts_access_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts_view', to='customers_app.accesslevel', verbose_name='Уровень доступа к документам'),
        ),
    ]
