# Generated by Django 5.0.1 on 2024-02-11 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0045_vacationschedulelist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacationschedulelist",
            options={
                "verbose_name": "Номер документа графика отпусков",
                "verbose_name_plural": "Номера документов графиков отпусков",
            },
        ),
    ]
