# Generated by Django 4.1 on 2022-09-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0046_alter_databaseuserprofile_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseuserworkprofile',
            name='date_of_employment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='identitydocuments',
            name='date_of_issue',
            field=models.DateField(null=True, verbose_name='Дата выдачи'),
        ),
    ]
