# Generated by Django 5.0.3 on 2024-04-11 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0047_alter_databaseuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="division",
            options={
                "ordering": ["code"],
                "verbose_name": "Подразделение",
                "verbose_name_plural": "Подразделения организации",
            },
        ),
    ]
