# Generated by Django 4.1.1 on 2022-09-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0047_alter_databaseuserworkprofile_date_of_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harmfulworkingconditions',
            name='ref_key',
            field=models.CharField(default='', max_length=37, verbose_name='Уникальный номер'),
        ),
    ]
