# Generated by Django 5.0.3 on 2024-04-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0048_alter_division_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaseuserworkprofile",
            name="work_application_password",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Пароль приложения от корпоративной почты",
            ),
        ),
    ]
