# Generated by Django 4.1.1 on 2022-09-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0048_harmfulworkingconditions_ref_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewDocumentsPhysical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_key', models.CharField(default='', max_length=37, verbose_name='Уникальный номер')),
                ('codeMVD', models.CharField(default='', max_length=5, verbose_name='Код МВД')),
                ('codePFR', models.CharField(default='', max_length=5, verbose_name='Код ПФР')),
                ('name', models.TextField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид документа физического лица',
                'verbose_name_plural': 'Виды документов физических лиц',
            },
        ),
    ]
