# Generated by Django 5.0.6 on 2024-06-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0049_databaseuserworkprofile_work_application_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counteragent",
            name="full_name",
            field=models.CharField(
                default="", max_length=300, verbose_name="Полное наименование"
            ),
        ),
        migrations.AlterField(
            model_name="counteragent",
            name="short_name",
            field=models.CharField(
                default="", max_length=300, verbose_name="Наименование"
            ),
        ),
    ]
