# Generated by Django 4.1.1 on 2022-09-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0049_viewdocumentsphysical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='Название категории'),
        ),
    ]
