# Generated by Django 4.1.1 on 2022-09-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0050_alter_division_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='Код подразделения'),
        ),
    ]
