# Generated by Django 4.1.1 on 2022-09-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0051_alter_division_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='okved',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Код ОКВЭД2'),
        ),
    ]
