# Generated by Django 5.0.6 on 2024-06-22 10:40

import customers_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0052_counteragent_natural_person_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounteragentDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_creation",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to=customers_app.models.document_directory_path,
                        verbose_name="Документ",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="", max_length=400, verbose_name="Описание"
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers_app.counteragent",
                        verbose_name="Контрагент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ контрагента",
                "verbose_name_plural": "Документы контрагента",
                "ordering": ["-date_of_creation"],
            },
        ),
    ]
