# Generated by Django 4.1.1 on 2022-09-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0052_alter_division_okved'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
