# Generated by Django 4.1.1 on 2022-09-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0053_job_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_entry',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата ввода'),
        ),
        migrations.AddField(
            model_name='job',
            name='date_exclusions',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата исключения'),
        ),
        migrations.AddField(
            model_name='job',
            name='excluded_standard_spelling',
            field=models.BooleanField(default=True, verbose_name='Исключена из штатного расписания'),
        ),
    ]
