# Generated by Django 5.0.6 on 2024-12-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0054_alter_counteragent_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="post_title",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Заголовок"
            ),
        ),
    ]
