# Generated by Django 4.1.1 on 2022-09-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0054_job_date_entry_job_date_exclusions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='active',
        ),
    ]
