# Generated by Django 4.1.1 on 2022-09-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0055_remove_job_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employment_function',
            field=models.CharField(default='', max_length=37, verbose_name='Трудовая функция'),
        ),
    ]
