# Generated by Django 5.0.6 on 2025-03-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0056_userstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaseuser",
            name="is_ppa",
            field=models.BooleanField(default=False, verbose_name="МПД"),
        ),
    ]
