# Generated by Django 5.0.6 on 2025-06-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0057_databaseuser_is_ppa"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaseuser",
            name="type_of_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Общий"),
                    ("1", "НО"),
                    ("2", "Кадры"),
                    ("3", "Бухгалтерия"),
                ],
                max_length=1,
                null=True,
                verbose_name="Роль подразделения",
            ),
        ),
    ]
