# Generated by Django 5.0.6 on 2025-06-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0058_databaseuser_type_of_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databaseuser",
            name="type_of_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Общий"),
                    ("1", "Наземное обеспечение"),
                    ("2", "Отдел кадров"),
                    ("3", "Бухгалтерия"),
                ],
                max_length=1,
                null=True,
                verbose_name="Роль подразделения",
            ),
        ),
    ]
