# Generated by Django 5.0.6 on 2025-07-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0059_alter_databaseuser_type_of_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaseuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
