# Generated by Django 5.0.6 on 2025-12-21 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0016_contract_updated_at"),
        ("customers_app", "0060_databaseuser_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=250, verbose_name="Адрес"
                    ),
                ),
                (
                    "validity_period",
                    models.DateField(
                        blank=True, null=True, verbose_name="Срок действия"
                    ),
                ),
                (
                    "beds_number",
                    models.IntegerField(default=0, verbose_name="Количество мест"),
                ),
                (
                    "type_description",
                    models.CharField(
                        blank=True, default="", max_length=250, verbose_name="Описание"
                    ),
                ),
                (
                    "contracts",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts_app.contract",
                        verbose_name="Договор",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers_app.division",
                    ),
                ),
            ],
            options={
                "verbose_name": "Квартира",
                "verbose_name_plural": "Квартиры",
            },
        ),
    ]
