# Generated by Django 5.0.6 on 2025-12-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0061_apartments"),
        ("hrdepartment_app", "0133_alter_laborprotectioninstructions_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartments",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hrdepartment_app.placeproductionactivity",
            ),
        ),
    ]
