# Generated by Django 5.0.6 on 2026-01-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0062_alter_apartments_place"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="counteragent",
            index=models.Index(
                fields=["inn", "kpp"], name="customers_a_inn_8a6f80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="counteragent",
            index=models.Index(fields=["inn"], name="customers_a_inn_333845_idx"),
        ),
    ]
