# Generated by Django 5.0.6 on 2026-02-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0063_counteragent_customers_a_inn_8a6f80_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartments",
            name="occupied_beds",
            field=models.IntegerField(default=0, verbose_name="Занято мест"),
        ),
    ]
