# Generated by Django 5.0.6 on 2026-02-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0016_contract_updated_at"),
        ("customers_app", "0064_apartments_occupied_beds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartments",
            name="contracts",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"parent_category__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contracts_app.contract",
                verbose_name="Договор",
            ),
        ),
    ]
