# Generated by Django 5.0.6 on 2026-02-09 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0016_contract_updated_at"),
        ("customers_app", "0065_alter_apartments_contracts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartments",
            name="contracts",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "parent_category__isnull": True,
                    "type_of_contract__type_contract": "Аренда квартир",
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contracts_app.contract",
                verbose_name="Договор",
            ),
        ),
    ]
