# Generated by Django 5.0.6 on 2026-03-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0066_alter_apartments_contracts"),
    ]

    operations = [
        migrations.AddField(
            model_name="counteragent",
            name="educational_organization",
            field=models.BooleanField(
                default=False, verbose_name="Образовательная организация"
            ),
        ),
    ]
