# Generated by Django 5.0.6 on 2026-03-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0067_counteragent_educational_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaseuser",
            name="employment_contract",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                verbose_name="Номер трудового договора",
            ),
        ),
        migrations.AddField(
            model_name="databaseuser",
            name="employment_contract_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата трудового договора"
            ),
        ),
    ]
