# Generated by Django 5.0.6 on 2026-03-18 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0068_databaseuser_employment_contract_and_more"),
        ("hrdepartment_app", "0148_trainingunit_unit_name_short_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField(verbose_name="Дата начала")),
                ("date_end", models.DateField(verbose_name="Дата окончания")),
                (
                    "beds_count",
                    models.IntegerField(default=1, verbose_name="Количество мест"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="customers_app.apartments",
                        verbose_name="Квартира",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartment_bookings",
                        to="hrdepartment_app.approvaloficialmemoprocess",
                        verbose_name="Бизнес-процесс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование квартиры",
                "verbose_name_plural": "Бронирования квартир",
                "ordering": ["date_start"],
            },
        ),
    ]
