# Generated by Django 5.0.6 on 2026-03-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0069_apartmentbooking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartmentbooking",
            name="beds_count",
        ),
        migrations.AddField(
            model_name="apartmentbooking",
            name="date_created",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата создания"
            ),
        ),
    ]
