# Generated by Django 5.0.6 on 2026-03-19 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0070_remove_apartmentbooking_beds_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentbooking",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
    ]
