# Generated by Django 5.2.12 on 2026-03-24 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0071_alter_apartmentbooking_date_created"),
        ("hrdepartment_app", "0149_approvaloficialmemoprocess_apartment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentbooking",
            name="process",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartment_booking",
                to="hrdepartment_app.approvaloficialmemoprocess",
                verbose_name="Бизнес-процесс",
            ),
        ),
    ]
