# Generated by Django 5.2.12 on 2026-05-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("customers_app", "0072_alter_apartmentbooking_process"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="databaseuser",
            index=models.Index(fields=["title"], name="customers_a_title_52f9c8_idx"),
        ),
    ]
