# Generated by Django 5.2.12 on 2026-05-04 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0073_databaseuser_customers_a_title_52f9c8_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_number",
                    models.CharField(
                        help_text="Уникальный номер документа",
                        max_length=50,
                        unique=True,
                        verbose_name="Номер согласия",
                    ),
                ),
                (
                    "consent_date",
                    models.DateField(
                        help_text="Дата, когда подписано согласие",
                        verbose_name="Дата подписания",
                    ),
                ),
                (
                    "employee_full_name",
                    models.CharField(
                        help_text="ФИО на момент подписания согласия",
                        max_length=150,
                        verbose_name="ФИО сотрудника",
                    ),
                ),
                (
                    "employee_position",
                    models.CharField(
                        blank=True,
                        help_text="Должность на момент подписания",
                        max_length=200,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "consent_template",
                    models.CharField(
                        default="Стандартный шаблон",
                        help_text="Название или версия шаблона согласия",
                        max_length=100,
                        verbose_name="Шаблон согласия",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация",
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "scanned_copy",
                    models.FileField(
                        help_text="Загрузите скан подписанного согласия (PDF, JPG, PNG)",
                        upload_to="biometric_consents/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Скан согласия с подписью",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, если согласие не отозвано",
                        verbose_name="Действует",
                    ),
                ),
                (
                    "revocation_date",
                    models.DateField(
                        blank=True,
                        help_text="Дата, когда сотрудник отозвал согласие",
                        null=True,
                        verbose_name="Дата отзыва",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_consents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто создал запись",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Сотрудник, давший согласие",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_consents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Согласие на обработку биометрии",
                "verbose_name_plural": "Согласия на обработку биометрии",
                "ordering": ["-consent_date"],
            },
        ),
    ]
