# Generated by Django 5.2.12 on 2026-05-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0074_biometricconsent"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="biometricconsent",
            index=models.Index(
                fields=["consent_number"], name="customers_a_consent_8a2dd2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="biometricconsent",
            constraint=models.UniqueConstraint(
                fields=("consent_number",), name="unique_consent_number"
            ),
        ),
    ]
