# Generated by Django 5.2.12 on 2026-05-15 08:16

import customers_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customers_app",
            "0075_biometricconsent_customers_a_consent_8a2dd2_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="biometricconsent",
            name="scanned_copy",
            field=models.FileField(
                help_text="Загрузите скан подписанного согласия (PDF, JPG, PNG)",
                upload_to=customers_app.models.get_biometric_consent_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="Скан согласия с подписью",
            ),
        ),
    ]
