# Generated by Django 5.2.12 on 2026-05-15 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0076_alter_biometricconsent_scanned_copy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biometricconsent",
            name="consent_template",
        ),
    ]
