# Generated by Django 5.2.12 on 2026-05-20 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration_app", "0003_templatedocument"),
        ("customers_app", "0077_remove_biometricconsent_consent_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Стандартное согласие, Расширенное согласие и т.д.",
                        max_length=200,
                        verbose_name="Наименование типа согласия",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Уникальный код типа согласия (например: standard, extended)",
                        unique=True,
                        verbose_name="Кодовое обозначение",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Описание типа согласия",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, если этот тип согласия используется",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше в списке",
                        verbose_name="Порядок сортировки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_consent_types",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто создал",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Шаблон согласия для этого типа",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consent_types",
                        to="administration_app.templatedocument",
                        verbose_name="Шаблон документа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип согласия",
                "verbose_name_plural": "Типы согласий",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="biometricconsent",
            name="consent_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Тип согласия на обработку биометрии",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biometric_consents",
                to="customers_app.consenttype",
                verbose_name="Тип согласия",
            ),
        ),
        migrations.AddIndex(
            model_name="consenttype",
            index=models.Index(
                fields=["code", "is_active"], name="customers_a_code_04594f_idx"
            ),
        ),
    ]
