# Generated by Django 5.2 on 2026-08-31 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers_app", "0078_consenttype_biometricconsent_consent_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.TextField(
                        unique=True, verbose_name="Endpoint URL push-сервера"
                    ),
                ),
                (
                    "p256dh",
                    models.CharField(max_length=255, verbose_name="Ключ p256dh"),
                ),
                (
                    "auth",
                    models.CharField(max_length=255, verbose_name="Ключ auth"),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="Устройство / Браузер",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push-подписка устройства",
                "verbose_name_plural": "Push-подписки устройств",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="customers_a_user_id_44f12d_idx"
                    )
                ],
            },
        ),
    ]
