# Generated by Django 5.2.12 on 2026-09-02 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0079_pushsubscription"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pushsubscription",
            new_name="customers_a_user_id_6e3c2a_idx",
            old_name="customers_a_user_id_44f12d_idx",
        ),
    ]
