# Generated by Django 5.2.12 on 2026-09-10 05:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0083_usercertificate"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="usercertificate",
            new_name="customers_a_thumbpr_3a89e2_idx",
            old_name="customers_a_thumbpr_6f8092_idx",
        ),
        migrations.RenameIndex(
            model_name="usercertificate",
            new_name="customers_a_snils_a7d002_idx",
            old_name="customers_a_snils_47e928_idx",
        ),
        migrations.RenameIndex(
            model_name="usercertificate",
            new_name="customers_a_inn_5c71ae_idx",
            old_name="customers_a_inn_0a174c_idx",
        ),
        migrations.RenameIndex(
            model_name="usercertificate",
            new_name="customers_a_user_id_cee4d9_idx",
            old_name="customers_a_user_id_0f8ce9_idx",
        ),
        migrations.RenameIndex(
            model_name="userpasskey",
            new_name="customers_a_credent_14ad4b_idx",
            old_name="customers_a_credent_495bd5_idx",
        ),
        migrations.RenameIndex(
            model_name="userpasskey",
            new_name="customers_a_user_id_2c7a5b_idx",
            old_name="customers_a_user_id_0fca81_idx",
        ),
    ]
