# Generated by Django 5.2.12 on 2026-09-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers_app", "0086_populate_initial_org_structure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="code",
            field=models.CharField(blank=True, default="", max_length=5, verbose_name="Код должности"),
        ),
        migrations.AlterField(
            model_name="job",
            name="employment_function",
            field=models.CharField(blank=True, default="", max_length=37, verbose_name="Трудовая функция"),
        ),
        migrations.AlterField(
            model_name="job",
            name="group",
            field=models.ManyToManyField(blank=True, to="customers_app.groups", verbose_name="Группы должности"),
        ),
        migrations.AlterField(
            model_name="job",
            name="ref_key",
            field=models.CharField(blank=True, default="", max_length=37, verbose_name="Уникальный номер"),
        ),
    ]
