# Generated by Django 6.1.1 on 2026-09-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customers_app', '0087_alter_job_blank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuser',
            name='personal_groups',
            field=models.ManyToManyField(blank=True, help_text='Индивидуальные дополнительные группы доступа сотрудника (не сбрасываются при синхронизации по должности).', related_name='personal_group_users', to='auth.group', verbose_name='Персональные группы доступа'),
        ),
    ]
