# Generated by Django 6.1.1 on 2026-10-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0017_estate_decommission_date'),
        ('customers_app', '0088_databaseuser_personal_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuser',
            name='allowed_aircraft_types',
            field=models.ManyToManyField(blank=True, help_text='Типы воздушных судов, указанные в свидетельстве специалиста по ТО ВС.', related_name='certifying_staff_users', to='contracts_app.typeproperty', verbose_name='Типы ВС по свидетельству специалиста'),
        ),
        migrations.AddField(
            model_name='databaseuser',
            name='maintenance_staff_certificate',
            field=models.CharField(blank=True, default='', help_text='Номер бессрочного свидетельства специалиста по техническому обслуживанию ВС (например, III. № 0184728).', max_length=100, verbose_name='Свидетельство специалиста по ТО ВС'),
        ),
    ]
