# Generated by Django 5.2.12 on 2026-06-19 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("customers_app", "0078_consenttype_biometricconsent_consent_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObligationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Код"),
                ),
            ],
            options={
                "verbose_name": "Тип обязательства",
                "verbose_name_plural": "Типы обязательств",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400, verbose_name="Наименование")),
                (
                    "inn",
                    models.CharField(db_index=True, max_length=12, verbose_name="ИНН"),
                ),
                (
                    "kpp",
                    models.CharField(
                        blank=True, default="", max_length=9, verbose_name="КПП"
                    ),
                ),
                (
                    "ogrn",
                    models.CharField(
                        blank=True, default="", max_length=15, verbose_name="ОГРН"
                    ),
                ),
                (
                    "juridical_address",
                    models.TextField(
                        blank=True, default="", verbose_name="Юридический адрес"
                    ),
                ),
                (
                    "ref_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=37,
                        verbose_name="Уникальный номер 1С",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время выполнения"
                    ),
                ),
                (
                    "object_name",
                    models.CharField(max_length=100, verbose_name="Объект обмена"),
                ),
                (
                    "records_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество полученных записей"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(verbose_name="Длительность выполнения (сек)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успех"), ("error", "Ошибка")],
                        default="success",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "errors",
                    models.TextField(blank=True, default="", verbose_name="Ошибки"),
                ),
            ],
            options={
                "verbose_name": "Журнал синхронизации",
                "verbose_name_plural": "Журналы синхронизации",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CreditAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(max_length=100, verbose_name="Номер договора"),
                ),
                ("contract_date", models.DateField(verbose_name="Дата договора")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма кредита"
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Процентная ставка"
                    ),
                ),
                (
                    "term_months",
                    models.IntegerField(verbose_name="Срок кредита (в месяцах)"),
                ),
                (
                    "remaining_debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Остаток долга",
                    ),
                ),
                (
                    "ref_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=37,
                        verbose_name="Уникальный номер 1С",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_agreements",
                        to="customers_app.counteragent",
                        verbose_name="Банк",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_credits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кредитный договор",
                "verbose_name_plural": "Кредитные договоры",
                "ordering": ["-contract_date"],
            },
        ),
        migrations.CreateModel(
            name="CreditPaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Дата платежа")),
                (
                    "principal",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Основной долг"
                    ),
                ),
                (
                    "interest",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Проценты"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Общая сумма"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирован"),
                            ("partially_paid", "Частично оплачен"),
                            ("paid", "Оплачен"),
                            ("overdue", "Просрочен"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "credit_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_schedules",
                        to="finance_app.creditagreement",
                        verbose_name="Кредитный договор",
                    ),
                ),
            ],
            options={
                "verbose_name": "График платежа по кредиту",
                "verbose_name_plural": "Графики платежей по кредитам",
                "ordering": ["payment_date"],
            },
        ),
        migrations.CreateModel(
            name="CreditPaymentFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Дата платежа")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма платежа"
                    ),
                ),
                (
                    "payment_doc_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Номер платежного документа",
                    ),
                ),
                (
                    "ref_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=37,
                        verbose_name="Уникальный номер 1С",
                    ),
                ),
                (
                    "credit_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_facts",
                        to="finance_app.creditagreement",
                        verbose_name="Кредитный договор",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_facts",
                        to="finance_app.creditpaymentschedule",
                        verbose_name="График платежа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Факт оплаты кредита",
                "verbose_name_plural": "Факты оплаты кредитов",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="FinanceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "field_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Поле"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="Старое значение"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="Новое значение"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Создание"),
                            ("update", "Изменение"),
                            ("delete", "Удаление"),
                        ],
                        max_length=20,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто изменил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал аудита финансов",
                "verbose_name_plural": "Журнал аудита финансов",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FinancialContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(max_length=100, verbose_name="Номер договора"),
                ),
                ("date_conclusion", models.DateField(verbose_name="Дата договора")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Сумма договора",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активный"),
                            ("completed", "Завершен"),
                            ("suspended", "Приостановлен"),
                            ("terminated", "Расторгнут"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "ref_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=37,
                        verbose_name="Уникальный номер 1С",
                    ),
                ),
                (
                    "counteragent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_contracts",
                        to="customers_app.counteragent",
                        verbose_name="Контрагент",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_financial_contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный сотрудник",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_contracts",
                        to="finance_app.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Финансовый договор",
                "verbose_name_plural": "Финансовые договоры",
                "ordering": ["-date_conclusion"],
            },
        ),
        migrations.CreateModel(
            name="DebtSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(verbose_name="Дата снимка")),
                (
                    "debt_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Сумма задолженности",
                    ),
                ),
                (
                    "overdue_debt_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Сумма просроченной задолженности",
                    ),
                ),
                (
                    "days_overdue",
                    models.IntegerField(
                        default=0, verbose_name="Количество дней просрочки"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debt_snapshots",
                        to="finance_app.financialcontract",
                        verbose_name="Договор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Снимок задолженности",
                "verbose_name_plural": "Снимки задолженности",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Текст уведомления")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("portal", "Внутреннее уведомление портала"),
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                        ],
                        default="portal",
                        max_length=20,
                        verbose_name="Канал уведомлений",
                    ),
                ),
                ("sent", models.BooleanField(default=False, verbose_name="Отправлено")),
                ("read", models.BooleanField(default=False, verbose_name="Прочитано")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialObligation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Сумма обязательства",
                    ),
                ),
                ("date_origin", models.DateField(verbose_name="Дата возникновения")),
                ("date_execution", models.DateField(verbose_name="Дата исполнения")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланировано"),
                            ("active", "Активно"),
                            ("completed", "Исполнено"),
                            ("overdue", "Просрочено"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "ref_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=37,
                        verbose_name="Уникальный номер 1С",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obligations",
                        to="finance_app.financialcontract",
                        verbose_name="Договор",
                    ),
                ),
                (
                    "counteragent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_obligations",
                        to="customers_app.counteragent",
                        verbose_name="Контрагент",
                    ),
                ),
                (
                    "obligation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligations",
                        to="finance_app.obligationtype",
                        verbose_name="Тип обязательства",
                    ),
                ),
            ],
            options={
                "verbose_name": "Финансовое обязательство",
                "verbose_name_plural": "Финансовые обязательства",
                "ordering": ["-date_execution"],
            },
        ),
        migrations.CreateModel(
            name="PaymentFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Дата платежа")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма платежа"
                    ),
                ),
                (
                    "payment_doc_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Номер платежного документа",
                    ),
                ),
                (
                    "ref_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=37,
                        verbose_name="Уникальный номер 1С",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_facts",
                        to="finance_app.financialobligation",
                        verbose_name="Обязательство",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фактический платеж",
                "verbose_name_plural": "Фактические платежи",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Дата платежа")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма платежа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирован"),
                            ("partially_paid", "Частично оплачен"),
                            ("paid", "Оплачен"),
                            ("overdue", "Просрочен"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_schedules",
                        to="finance_app.financialobligation",
                        verbose_name="Обязательство",
                    ),
                ),
            ],
            options={
                "verbose_name": "Плановый платеж",
                "verbose_name_plural": "Плановые платежи",
                "ordering": ["payment_date"],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "portal_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Внутренние уведомления"
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Уведомления по Email"
                    ),
                ),
                (
                    "telegram_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Уведомления в Telegram"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_notification_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
            },
        ),
    ]
