# Generated by Django 5.2.12 on 2026-06-29 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentralBankKeyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="Действует с")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Ставка (%)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ключевая ставка ЦБ",
                "verbose_name_plural": "Ключевые ставки ЦБ",
                "ordering": ["-date_from"],
            },
        ),
        migrations.CreateModel(
            name="CreditTranche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата выдачи транша")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма транша"
                    ),
                ),
                (
                    "credit_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tranches",
                        to="finance_app.creditagreement",
                        verbose_name="Кредитный договор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транш кредита",
                "verbose_name_plural": "Транши кредитов",
                "ordering": ["date"],
            },
        ),
    ]
