# Generated by Django 5.2.12 on 2026-06-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance_app", "0002_centralbankkeyrate_credittranche"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditpaymentfact",
            name="payment_type",
            field=models.CharField(
                choices=[("principal", "Основной долг (ОД)"), ("interest", "Проценты")],
                default="principal",
                max_length=20,
                verbose_name="Тип платежа",
            ),
        ),
    ]
