# Generated by Django 5.2.12 on 2026-07-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance_app", "0003_creditpaymentfact_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentfact",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("in", "Поступление"), ("out", "Списание")],
                max_length=20,
                null=True,
                verbose_name="Вид операции",
            ),
        ),
    ]
