# Generated by Django 5.2.12 on 2026-07-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance_app", "0004_paymentfact_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditagreement",
            name="tranche_repayment_days",
            field=models.IntegerField(
                default=45, verbose_name="Дней на погашение транша"
            ),
        ),
    ]
