# Generated by Django 5.2.12 on 2026-07-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance_app", "0005_creditagreement_tranche_repayment_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditagreement",
            name="has_unused_limit_commission",
            field=models.BooleanField(
                default=False, verbose_name="Есть комиссия за неиспользованный лимит"
            ),
        ),
        migrations.AddField(
            model_name="creditagreement",
            name="unused_limit_commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=5,
                verbose_name="Ставка комиссии за неиспользованный лимит (%)",
            ),
        ),
    ]
