# Generated by Django 5.1.5 on 2026-08-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance_app", "0006_creditagreement_has_unused_limit_commission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditagreement",
            name="availability_period_end",
            field=models.DateField(
                blank=True,
                help_text="Дата, по которую можно получать транши. После неё остается только обязательство по погашению ранее выданных.",
                null=True,
                verbose_name="Последний день периода обращения",
            ),
        ),
        migrations.AddField(
            model_name="creditagreement",
            name="credit_end_date",
            field=models.DateField(
                blank=True,
                help_text="Дата включительно, по которую будет рассчитываться срок кредитования, после которой овердрафт считается закрытым.",
                null=True,
                verbose_name="Общий срок кредитования",
            ),
        ),
        migrations.AlterField(
            model_name="creditagreement",
            name="term_months",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Срок кредита (в месяцах)"
            ),
        ),
    ]
