# Generated by Django 5.2.12 on 2026-04-03 08:34

import tickets_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                upload_to=tickets_app.models.get_attachment_upload_path,
                validators=[tickets_app.models.validate_file_extension],
                verbose_name="Файл",
            ),
        ),
    ]
