# Generated by Django 5.2.12 on 2026-04-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets_app", "0002_alter_attachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="original_name",
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
