# Generated by Django 5.2.12 on 2026-04-03 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets_app", "0003_attachment_original_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="parent_ticket",
            field=models.ForeignKey(
                blank=True,
                help_text="Если это обжалование, укажите предыдущее закрытое сообщение",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appeals",
                to="tickets_app.ticket",
                verbose_name="Родительское сообщение (обжалование)",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новое"),
                    ("in_progress", "В работе"),
                    ("redirected", "Переадресовано"),
                    ("resolved", "Решено"),
                    ("closed", "Закрыто"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
