# Generated by Django 6.1.1 on 2026-09-22 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0004_alter_ticket_parent_ticket_alter_ticket_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('curator', models.ForeignKey(blank=True, help_text='Сотрудник, уполномоченный разбирать новые заявки и назначать ответственных специалистов.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_ticket_settings', to=settings.AUTH_USER_MODEL, verbose_name='Куратор заявок (Диспетчер СДС)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто назначил')),
            ],
            options={
                'verbose_name': 'Настройки СДС',
                'verbose_name_plural': 'Настройки СДС',
            },
        ),
    ]
