# Generated by Django 6.1.1 on 2026-09-22 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0005_ticketsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='responsible',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='ticketsettings',
            name='curator',
            field=models.ForeignKey(blank=True, help_text='Сотрудник, уполномоченный разбирать новые заявки и назначать ответственных специалистов.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_ticket_settings', to=settings.AUTH_USER_MODEL, verbose_name='Куратор заявок (Диспетчер СДС)'),
        ),
    ]
