# Generated by Django 6.1.1 on 2026-09-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0006_alter_ticket_responsible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_confidential',
            field=models.BooleanField(default=True, help_text='Если включено, ФИО и контакты заявителя скрыты от назначенного исполнителя (видны только руководству и куратору СДС)', verbose_name='Конфиденциально для исполнителя'),
        ),
    ]
