# Generated by Django 4.1.3 on 2022-11-19 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hrdepartment_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=4, verbose_name='Номер')),
                ('date_entry', models.DateField(auto_now_add=True, null=True, verbose_name='Дата ввода информации')),
                ('working_status', models.CharField(blank=True, choices=[('1', 'Поступающий на работу'), ('2', 'Работающий')], default='', max_length=40, verbose_name='Статус')),
                ('medical_direction', models.FileField(blank=True, upload_to=hrdepartment_app.models.contract_directory_path, verbose_name='Файл документа')),
                ('harmful', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.harmfulworkingconditions', verbose_name='Вредные условия труда')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.counteragent', verbose_name='Медицинская организация')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Медицинское направление',
                'verbose_name_plural': 'Медицинские направления',
            },
        ),
    ]
