# Generated by Django 4.1.3 on 2022-11-21 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrdepartment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialmemo',
            name='order_date',
            field=models.DateField(null=True, verbose_name='Дата приказа'),
        ),
        migrations.AddField(
            model_name='officialmemo',
            name='order_number',
            field=models.CharField(default='', max_length=20, verbose_name='Номер приказа'),
        ),
        migrations.AlterField(
            model_name='officialmemo',
            name='period_for',
            field=models.DateField(null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='officialmemo',
            name='period_from',
            field=models.DateField(null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='officialmemo',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
