# Generated by Django 4.1.7 on 2023-03-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceProductionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Место назначения',
                'verbose_name_plural': 'Места назначения',
            },
        ),
        migrations.RemoveField(
            model_name='officialmemo',
            name='other_place_production_activity',
        ),
        migrations.AlterField(
            model_name='officialmemo',
            name='place_production_activity',
            field=models.ManyToManyField(to='hrdepartment_app.placeproductionactivity', verbose_name='МПД'),
        ),
    ]
