# Generated by Django 4.1 on 2022-08-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='date_entry',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата ввода информации'),
        ),
    ]
