# Generated by Django 4.1.7 on 2023-02-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0002_alter_medicalorganisation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='number',
            field=models.CharField(default='', max_length=11, verbose_name='Номер'),
        ),
    ]
