# Generated by Django 4.1.3 on 2022-11-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('hrdepartment_app', '0002_officialmemo_order_date_officialmemo_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialmemo',
            name='purpose',
        ),
        migrations.AddField(
            model_name='officialmemo',
            name='purpose_trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='hrdepartment_app.purpose', verbose_name='Цель'),
        ),
    ]
