# Generated by Django 4.1 on 2022-08-28 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0041_alter_databaseuserprofile_citizenship_and_more'),
        ('hrdepartment_app', '0002_medical_date_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medical',
            options={'verbose_name': 'Медицинское направление', 'verbose_name_plural': 'Медицинские направления'},
        ),
        migrations.AddField(
            model_name='medical',
            name='harmful',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.harmfulworkingconditions'),
        ),
    ]
