# Generated by Django 4.1.7 on 2023-02-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hrdepartment_app', '0003_alter_medical_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalorganisation',
            name='email',
            field=models.CharField(default='', max_length=150, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='medicalorganisation',
            name='phone',
            field=models.CharField(default='', max_length=150, verbose_name='Телефон'),
        ),
    ]
