# Generated by Django 4.1.3 on 2022-11-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0003_remove_officialmemo_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialmemo',
            name='comments',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='officialmemo',
            name='order_number',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='Номер приказа'),
        ),
    ]
