# Generated by Django 4.1.7 on 2023-03-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0004_alter_medicalorganisation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='date_entry',
            field=models.DateField(null=True, verbose_name='Дата ввода информации'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='date_of_inspection',
            field=models.DateField(null=True, verbose_name='Дата осмотра'),
        ),
    ]
