# Generated by Django 4.1.7 on 2023-03-27 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrdepartment_app', '0004_alter_documentsjobdescription_validity_period_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, verbose_name='Дата и время прихода')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='Дата и время ухода')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рабочее время',
                'verbose_name_plural': 'Табель учета',
            },
        ),
    ]
