# Generated by Django 4.1.3 on 2022-11-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hrdepartment_app', '0004_officialmemo_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialmemo',
            name='document_accepted',
            field=models.BooleanField(default=False, verbose_name='Документ принят'),
        ),
    ]
