# Generated by Django 4.1.7 on 2023-03-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0005_alter_medical_date_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvaloficialmemoprocess',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='approvaloficialmemoprocess',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='officialmemo',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='officialmemo',
            name='order_number',
        ),
    ]
