# Generated by Django 4.1.3 on 2022-11-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0005_officialmemo_document_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialmemo',
            name='comments',
            field=models.CharField(default='', max_length=250, verbose_name='Примечание'),
        ),
    ]
