# Generated by Django 4.1.7 on 2023-03-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0005_reportcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='search_day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время ухода'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время прихода'),
        ),
    ]
