# Generated by Django 4.1.7 on 2023-03-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0006_reportcard_search_day_alter_reportcard_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcard',
            old_name='search_day',
            new_name='report_card_day',
        ),
    ]
