# Generated by Django 4.1.7 on 2023-03-08 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_documentsorder_approved'),
        ('hrdepartment_app', '0006_remove_approvaloficialmemoprocess_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_app.documentsorder', verbose_name='Приказ'),
        ),
        migrations.AddField(
            model_name='officialmemo',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_app.documentsorder', verbose_name='Приказ'),
        ),
    ]
