# Generated by Django 4.1.7 on 2023-03-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0007_rename_search_day_reportcard_report_card_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Дата и время ухода'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Дата и время прихода'),
        ),
    ]
