# Generated by Django 4.1.7 on 2023-04-04 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0008_alter_reportcard_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonForCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Причина отмены',
                'verbose_name_plural': 'Причины отмены',
            },
        ),
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='cancellation',
            field=models.BooleanField(default=False, verbose_name='Отмена'),
        ),
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='reason_cancellation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrdepartment_app.reasonforcancellation'),
        ),
    ]
