# Generated by Django 4.2 on 2023-04-24 09:31

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0009_reasonforcancellation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsorder',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Содержание'),
        ),
    ]
