# Generated by Django 4.1.3 on 2022-11-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hrdepartment_app', '0009_officialmemo_document_agreed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialmemo',
            name='document_agreed',
        ),
        migrations.RemoveField(
            model_name='officialmemo',
            name='document_not_agreed',
        ),
        migrations.RemoveField(
            model_name='officialmemo',
            name='reason_for_approval',
        ),
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='comments_for_approval',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Комментарий для согласования'),
        ),
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='document_agreed',
            field=models.BooleanField(default=False, verbose_name='Документ не согласован'),
        ),
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='document_not_agreed',
            field=models.BooleanField(default=False, verbose_name='Документ согласован'),
        ),
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='reason_for_approval',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Примечание к согласованию'),
        ),
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='submit_for_approval',
            field=models.BooleanField(default=False, verbose_name='Передан на согласование'),
        ),
    ]
