# Generated by Django 4.1.3 on 2022-11-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hrdepartment_app', '0010_remove_officialmemo_document_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='location_selected',
            field=models.BooleanField(default=False, verbose_name='Выбрано место проживания'),
        ),
    ]
