# Generated by Django 4.2 on 2023-04-26 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0011_approvaloficialmemoprocess_person_accounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialmemo',
            name='place_departure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_departure', to='hrdepartment_app.placeproductionactivity', verbose_name='Место отправления'),
        ),
        migrations.AlterField(
            model_name='officialmemo',
            name='place_production_activity',
            field=models.ManyToManyField(related_name='place_production_activity', to='hrdepartment_app.placeproductionactivity', verbose_name='МПД'),
        ),
    ]
