# Generated by Django 4.2 on 2023-04-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0012_officialmemo_place_departure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='email_send',
            field=models.BooleanField(default=False, verbose_name='Письмо отправлено'),
        ),
    ]
