# Generated by Django 4.2 on 2023-04-27 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0014_alter_documentsjobdescription_document_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsjobdescription',
            name='document_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата документа'),
        ),
        migrations.AlterField(
            model_name='documentsorder',
            name='document_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата документа'),
        ),
    ]
