# Generated by Django 4.1.3 on 2022-12-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0014_alter_approvaloficialmemoprocess_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvaloficialmemoprocess',
            name='document_agreed',
        ),
    ]
