# Generated by Django 4.2 on 2023-04-27 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0015_alter_documentsjobdescription_document_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='accepted_accounting',
            field=models.BooleanField(default=False, verbose_name='Принято в бухгалтерии'),
        ),
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='prepaid_expense',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Пометка выплаты'),
        ),
        migrations.AlterField(
            model_name='documentsorder',
            name='document_foundation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_foundation', to='hrdepartment_app.officialmemo', verbose_name='Документ основание'),
        ),
    ]
