# Generated by Django 4.1.5 on 2023-01-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0016_approvaloficialmemoprocess_accommodation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaloficialmemoprocess',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приказа'),
        ),
        migrations.AlterField(
            model_name='approvaloficialmemoprocess',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Номер приказа'),
        ),
    ]
