# Generated by Django 4.1.5 on 2023-01-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hrdepartment_app', '0017_alter_approvaloficialmemoprocess_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialmemo',
            name='official_memo_type',
            field=models.CharField(choices=[('1', 'Направление'), ('2', 'Продление')], default='1', max_length=9,
                                   verbose_name='Тип СП'),
        ),
    ]
