# Generated by Django 4.2 on 2023-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0017_placeproductionactivity_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeproductionactivity',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name=''),
        ),
    ]
