# Generated by Django 4.1.5 on 2023-01-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customers_app', '0004_alter_counteragent_ogrn'),
        ('hrdepartment_app', '0018_officialmemo_official_memo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialmemo',
            name='place_production_activity',
        ),
        migrations.AddField(
            model_name='officialmemo',
            name='place_production_activity',
            field=models.ManyToManyField(null=True, to='customers_app.division', verbose_name='МПД'),
        ),
    ]
