# Generated by Django 4.2 on 2023-05-04 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0020_officialmemo_document_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialmemo',
            name='document_extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrdepartment_app.officialmemo', verbose_name='Документ основания'),
        ),
    ]
