# Generated by Django 4.1.5 on 2023-02-03 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrdepartment_app', '0021_alter_approvaloficialmemoprocess_person_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialmemo',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
