# Generated by Django 4.1.5 on 2023-02-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0023_alter_officialmemo_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialmemo',
            name='type_trip',
            field=models.CharField(blank=True, choices=[('1', 'Служебная поездка'), ('2', 'Командировка')], default='', max_length=9, verbose_name='Тип поездки'),
        ),
    ]
