# Generated by Django 4.2 on 2023-05-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0023_documentsorder_cancellation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialmemo',
            name='cancellation',
            field=models.BooleanField(default=False, verbose_name='Отмена'),
        ),
        migrations.AddField(
            model_name='officialmemo',
            name='reason_cancellation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrdepartment_app.reasonforcancellation', verbose_name='Причина отмены'),
        ),
    ]
