# Generated by Django 4.1.5 on 2023-02-04 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0024_officialmemo_type_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 4, 21, 34, 47, 772784, tzinfo=datetime.timezone.utc), verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officialmemo',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 4, 21, 35, 2, 588193, tzinfo=datetime.timezone.utc), verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
    ]
