# Generated by Django 4.2 on 2023-05-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0025_approvaloficialmemoprocess_originals_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='number_business_trip_days',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
    ]
