# Generated by Django 4.1.5 on 2023-02-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0025_approvaloficialmemoprocess_date_of_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialmemo',
            name='other_place_production_activity',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Другое место назначения'),
        ),
        migrations.AlterField(
            model_name='officialmemo',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер приказа'),
        ),
    ]
