# Generated by Django 4.1.5 on 2023-02-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0010_division_destination_point'),
        ('hrdepartment_app', '0026_officialmemo_other_place_production_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProcessDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_process_type', models.CharField(blank=True, default='', max_length=5, verbose_name='Тип бизнес процесса')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('clerk', models.ManyToManyField(related_name='clerk', to='customers_app.job', verbose_name='Исполнитель')),
                ('person_agreement', models.ManyToManyField(related_name='person_agreement', to='customers_app.job', verbose_name='Исполнитель')),
                ('person_executor', models.ManyToManyField(related_name='person_executor', to='customers_app.job', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Направление бизнес процесса',
                'verbose_name_plural': 'Направления бизнес процессов',
            },
        ),
    ]
