# Generated by Django 4.2 on 2023-05-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0026_approvaloficialmemoprocess_number_business_trip_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='number_flight_days',
            field=models.IntegerField(default=0, verbose_name='Дни ЛД'),
        ),
        migrations.AlterField(
            model_name='approvaloficialmemoprocess',
            name='number_business_trip_days',
            field=models.IntegerField(default=0, verbose_name='Дни СП'),
        ),
    ]
