# Generated by Django 4.1.5 on 2023-02-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0027_businessprocessdirection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprocessdirection',
            name='business_process_type',
            field=models.CharField(blank=True, choices=[('1', 'SP')], default='', max_length=5, verbose_name='Тип бизнес процесса'),
        ),
    ]
