# Generated by Django 4.2 on 2023-05-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0027_approvaloficialmemoprocess_number_flight_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='date_transfer_hr',
            field=models.DateField(blank=True, null=True, verbose_name='Дата передачи в ОК'),
        ),
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='end_date_trip',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания по СЗ'),
        ),
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='start_date_trip',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала по СЗ'),
        ),
    ]
