# Generated by Django 4.1.5 on 2023-02-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0010_division_destination_point'),
        ('hrdepartment_app', '0028_alter_businessprocessdirection_business_process_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprocessdirection',
            name='clerk',
            field=models.ManyToManyField(related_name='clerk', to='customers_app.job', verbose_name='Делопроизводитель'),
        ),
        migrations.AlterField(
            model_name='businessprocessdirection',
            name='person_agreement',
            field=models.ManyToManyField(related_name='person_agreement', to='customers_app.job', verbose_name='Согласующее лицо'),
        ),
    ]
