# Generated by Django 4.1.5 on 2023-02-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0029_alter_businessprocessdirection_clerk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialmemo',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Номер приказа'),
        ),
    ]
