# Generated by Django 4.2 on 2023-05-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0030_historychange_date_add'),
        ('hrdepartment_app', '0029_approvaloficialmemoprocess_date_transfer_accounting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocessdirection',
            name='person_hr',
            field=models.ManyToManyField(related_name='person_hr', to='customers_app.job', verbose_name='Сотрудник ОК'),
        ),
    ]
