# Generated by Django 4.2 on 2023-05-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0030_businessprocessdirection_person_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaloficialmemoprocess',
            name='submitted_for_signature',
            field=models.DateField(blank=True, null=True, verbose_name='Дата передачи на подпись'),
        ),
    ]
