# Generated by Django 4.1.6 on 2023-02-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0030_alter_officialmemo_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='ref_key',
            field=models.CharField(default='', max_length=37, verbose_name='Уникальный номер'),
        ),
    ]
