# Generated by Django 4.1.6 on 2023-02-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0031_medical_ref_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_key', models.CharField(default='', max_length=37, verbose_name='Уникальный номер')),
                ('number', models.CharField(default='', max_length=200, verbose_name='Наименование')),
                ('ogrn', models.CharField(default='', max_length=13, verbose_name='ОГРН')),
                ('address', models.CharField(default='', max_length=250, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Медицинская организация',
                'verbose_name_plural': 'Медицинскик организации',
            },
        ),
    ]
