# Generated by Django 4.2 on 2023-05-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0032_approvaloficialmemoprocess_date_receipt_original_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='')),
            ],
            options={
                'verbose_name': 'Наименование приказа',
                'verbose_name_plural': 'Наименования приказов',
            },
        ),
    ]
