# Generated by Django 4.2 on 2023-05-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0033_orderdescription'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE hrdepartment_app_documentsorder SET document_name = 1"
        ),
        migrations.AlterField(
            model_name='documentsorder',
            name='document_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrdepartment_app.orderdescription', verbose_name='Наименование документа'),
        ),
    ]
