# Generated by Django 4.1.6 on 2023-02-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0011_posts_post_date_end_posts_post_date_start_and_more'),
        ('hrdepartment_app', '0034_alter_medical_type_inspection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical',
            name='harmful',
        ),
        migrations.AddField(
            model_name='medical',
            name='harmful',
            field=models.ManyToManyField(null=True, to='customers_app.harmfulworkingconditions', verbose_name='Вредные условия труда'),
        ),
    ]
