# Generated by Django 4.2 on 2023-05-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0034_alter_documentsorder_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialmemo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Наименование'),
        ),
    ]
