# Generated by Django 4.2 on 2023-05-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0036_approvaloficialmemoprocess_prepaid_expense_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialmemo',
            name='official_memo_type',
            field=models.CharField(choices=[('1', 'Направление'), ('2', 'Продление'), ('3', 'Без выезда')], default='1', max_length=9, verbose_name='Тип СП'),
        ),
    ]
