# Generated by Django 4.1.6 on 2023-02-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0036_alter_medical_harmful'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalorganisation',
            old_name='number',
            new_name='description',
        ),
        migrations.AddField(
            model_name='medical',
            name='date_of_inspection',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата осмотра'),
        ),
    ]
