# Generated by Django 4.1.6 on 2023-02-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0037_rename_number_medicalorganisation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalorganisation',
            name='email',
            field=models.EmailField(default='0', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='medicalorganisation',
            name='tel',
            field=models.CharField(default='0', max_length=15, verbose_name='Телефон'),
        ),
    ]
