# Generated by Django 4.2 on 2023-05-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0037_alter_officialmemo_official_memo_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreHolidayDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preholiday_day', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('work_time', models.TimeField(blank=True, null=True, verbose_name='Рабочее время')),
            ],
            options={
                'verbose_name': 'Предпраздничный день',
                'verbose_name_plural': 'Предпраздничные дни',
            },
        ),
    ]
