# Generated by Django 4.2 on 2023-05-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0039_weekendday'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekendday',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Описание'),
        ),
    ]
