# Generated by Django 4.1.6 on 2023-02-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0039_rename_tel_medicalorganisation_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical',
            old_name='type_of_inspection',
            new_name='view_inspection',
        ),
    ]
