# Generated by Django 4.2 on 2023-05-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0041_productioncalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='doc_ref_key',
            field=models.CharField(blank=True, default='', max_length=37, verbose_name='Уникальный номер документа'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='manual_input',
            field=models.BooleanField(default=False, verbose_name='Ручной ввод'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='reason_adjustment',
            field=models.TextField(blank=True, verbose_name='Причина ручной корректировки'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='record_type',
            field=models.CharField(blank=True, choices=[('1', 'Явка'), ('2', 'Ежегодный отпуск'), ('3', 'Дополнителный отпуск')], default='', max_length=100, verbose_name='Тип записи'),
        ),
    ]
