# Generated by Django 4.2 on 2023-05-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0043_alter_reportcard_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekendday',
            name='weekend_type',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Тип дня'),
        ),
    ]
