# Generated by Django 4.2 on 2023-05-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0044_weekendday_weekend_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekendday',
            name='weekend_type',
            field=models.CharField(blank=True, choices=[('1', 'Праздник'), ('2', 'Выходной')], max_length=8, null=True, verbose_name='Тип дня'),
        ),
    ]
