# Generated by Django 4.2 on 2023-05-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0045_alter_weekendday_weekend_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='rec_no',
            field=models.IntegerField(blank=True, default=0, verbose_name='Номер записи'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время ухода'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='record_type',
            field=models.CharField(blank=True, choices=[('1', 'Явка'), ('2', 'Ежегодный'), ('3', 'Дополнительный ежегодный отпуск'), ('4', 'Отпуск за свой счет'), ('5', 'Дополнительный учебный отпуск (оплачиваемый)'), ('6', 'Отпуск по уходу за ребенком'), ('7', 'Дополнительный неоплачиваемый отпуск пострадавшим в аварии на ЧАЭС'), ('8', 'Отпуск по беременности и родам'), ('9', 'Отпуск без оплаты согласно ТК РФ'), ('10', 'Дополнительный отпуск'), ('11', 'Дополнительный оплачиваемый отпуск пострадавшим в '), ('12', 'Основной'), ('13', 'Ручной ввод')], default='', max_length=100, verbose_name='Тип записи'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время прихода'),
        ),
    ]
