# Generated by Django 4.2 on 2023-05-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0046_reportcard_rec_no_alter_reportcard_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='current_intervals',
            field=models.BooleanField(default=True, verbose_name='Текущий интервал'),
        ),
    ]
