# Generated by Django 4.2.1 on 2023-06-04 20:04

from django.db import migrations, models
import hrdepartment_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0047_reportcard_current_intervals'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='medical_direction2',
            field=models.FileField(blank=True, upload_to=hrdepartment_app.models.contract_directory_path, verbose_name='Файл ПО'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='medical_direction',
            field=models.FileField(blank=True, upload_to=hrdepartment_app.models.contract_directory_path, verbose_name='Файл ПМО'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='record_type',
            field=models.CharField(blank=True, choices=[('1', 'Явка'), ('2', 'Ежегодный'), ('3', 'Дополнительный ежегодный отпуск'), ('4', 'Отпуск за свой счет'), ('5', 'Дополнительный учебный отпуск (оплачиваемый)'), ('6', 'Отпуск по уходу за ребенком'), ('7', 'Дополнительный неоплачиваемый отпуск пострадавшим в аварии на ЧАЭС'), ('8', 'Отпуск по беременности и родам'), ('9', 'Отпуск без оплаты согласно ТК РФ'), ('10', 'Дополнительный отпуск'), ('11', 'Дополнительный оплачиваемый отпуск пострадавшим в '), ('12', 'Основной'), ('13', 'Ручной ввод'), ('14', 'Служебная поездка'), ('15', 'Командировка')], default='', max_length=100, verbose_name='Тип записи'),
        ),
    ]
