# Generated by Django 4.2.1 on 2023-06-14 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0050_alter_reportcard_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialmemo',
            name='document_extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extension', to='hrdepartment_app.officialmemo', verbose_name='Документ основания'),
        ),
    ]
