# Generated by Django 4.2.1 on 2023-06-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0051_alter_officialmemo_document_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsjobdescription',
            name='applying_for_job',
            field=models.BooleanField(default=False, verbose_name='Обязательно к ознакомлению при приеме на работу'),
        ),
        migrations.AddField(
            model_name='documentsorder',
            name='applying_for_job',
            field=models.BooleanField(default=False, verbose_name='Обязательно к ознакомлению при приеме на работу'),
        ),
    ]
