# Generated by Django 4.2.1 on 2023-06-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_documentform'),
        ('hrdepartment_app', '0054_provisions_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructions',
            name='document_form',
            field=models.ManyToManyField(to='library_app.documentform', verbose_name='Бланки документов'),
        ),
        migrations.AddField(
            model_name='provisions',
            name='document_form',
            field=models.ManyToManyField(to='library_app.documentform', verbose_name='Бланки документов'),
        ),
    ]
