# Generated by Django 4.2.1 on 2023-07-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0056_reportcard_confirmed_reportcard_place_report_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdescription',
            name='name',
            field=models.CharField(max_length=250, verbose_name=''),
        ),
    ]
