# Generated by Django 4.2.1 on 2023-08-07 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0059_orderdescription_affiliation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdescription",
            name="affiliation",
        ),
    ]
