# Generated by Django 4.2.1 on 2023-08-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0043_job_division_affiliation"),
        ("hrdepartment_app", "0062_alter_documentsorder_document_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdescription",
            name="affiliation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customers_app.affiliation",
                verbose_name="Принадлежность",
            ),
        ),
    ]
