# Generated by Django 4.2.1 on 2023-11-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0064_alter_reportcard_record_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsjobdescription",
            name="parent_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hrdepartment_app.documentsjobdescription",
            ),
        ),
        migrations.AddField(
            model_name="documentsorder",
            name="parent_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hrdepartment_app.documentsorder",
            ),
        ),
        migrations.AddField(
            model_name="instructions",
            name="parent_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hrdepartment_app.instructions",
            ),
        ),
        migrations.AddField(
            model_name="provisions",
            name="parent_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hrdepartment_app.provisions",
            ),
        ),
    ]
