# Generated by Django 5.0.3 on 2024-03-19 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0069_alter_officialmemo_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentsorder",
            options={
                "ordering": ["document_date"],
                "verbose_name": "Приказ",
                "verbose_name_plural": "Приказы",
            },
        ),
    ]
