# Generated by Django 5.0.3 on 2024-03-19 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0070_alter_documentsorder_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentsorder",
            options={
                "ordering": ["-document_date"],
                "verbose_name": "Приказ",
                "verbose_name_plural": "Приказы",
            },
        ),
    ]
