# Generated by Django 5.0.3 on 2024-03-20 09:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0071_alter_documentsorder_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvaloficialmemoprocess",
            options={
                "ordering": ["-document__period_from"],
                "verbose_name": "Служебная записка по служебной поездке",
                "verbose_name_plural": "Служебные записки по служебным поездкам",
            },
        ),
        migrations.CreateModel(
            name="CreatingTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_start",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        null=True,
                        verbose_name="Дата начала",
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
                (
                    "date_create",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        null=True,
                        verbose_name="Дата приказа",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Номер приказа",
                    ),
                ),
                (
                    "approving_person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approving_person",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Согласующее лицо",
                    ),
                ),
                (
                    "executor_person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executor_person",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="place",
                        to="hrdepartment_app.placeproductionactivity",
                    ),
                ),
                (
                    "senior_brigade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="senior_brigade",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Старший бригады",
                    ),
                ),
                (
                    "team_brigade",
                    models.ManyToManyField(
                        related_name="team_brigade",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Состав бригады",
                    ),
                ),
            ],
            options={
                "verbose_name": "Создание бригады",
                "verbose_name_plural": "Создание бригад",
            },
        ),
    ]
