# Generated by Django 5.0.3 on 2024-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0073_creatingteam_company_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatingteam",
            name="agreed",
            field=models.BooleanField(default=False, verbose_name="Согласовано"),
        ),
    ]
