# Generated by Django 5.0.3 on 2024-03-20 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0074_creatingteam_agreed"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatingteam",
            name="documents_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_order",
                to="hrdepartment_app.documentsorder",
            ),
        ),
    ]
