# Generated by Django 5.0.3 on 2024-03-20 13:50

import django.db.models.deletion
import hrdepartment_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0007_delete_hotel"),
        ("hrdepartment_app", "0075_creatingteam_documents_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creatingteam",
            name="documents_order",
        ),
        migrations.AddField(
            model_name="creatingteam",
            name="cancellation",
            field=models.BooleanField(default=False, verbose_name="Отмена"),
        ),
        migrations.AddField(
            model_name="creatingteam",
            name="doc_file",
            field=models.FileField(
                blank=True,
                upload_to=hrdepartment_app.models.ord_directory_path,
                verbose_name="Файл документа",
            ),
        ),
        migrations.AddField(
            model_name="creatingteam",
            name="scan_file",
            field=models.FileField(
                blank=True,
                upload_to=hrdepartment_app.models.ord_directory_path,
                verbose_name="Скан документа",
            ),
        ),
        migrations.AlterField(
            model_name="creatingteam",
            name="company_property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_property",
                to="contracts_app.companyproperty",
                verbose_name="Задание на полет",
            ),
        ),
        migrations.AlterField(
            model_name="creatingteam",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="place",
                to="hrdepartment_app.placeproductionactivity",
                verbose_name="МПД",
            ),
        ),
    ]
