# Generated by Django 5.0.3 on 2024-03-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0076_remove_creatingteam_documents_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeproductionactivity",
            name="short_name",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name=""
            ),
        ),
    ]
