# Generated by Django 5.0.3 on 2024-03-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0077_alter_placeproductionactivity_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeproductionactivity",
            name="use_team_orders",
            field=models.BooleanField(
                default=False, verbose_name="Использовать в приказах"
            ),
        ),
        migrations.AlterField(
            model_name="placeproductionactivity",
            name="short_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=30,
                verbose_name="Краткое наименование",
            ),
        ),
    ]
