# Generated by Django 5.0.3 on 2024-03-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0007_delete_hotel"),
        ("hrdepartment_app", "0078_placeproductionactivity_use_team_orders_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatingteam",
            name="company_property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_property",
                to="contracts_app.estate",
                verbose_name="Задание на полет",
            ),
        ),
    ]
