# Generated by Django 5.0.3 on 2024-03-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0079_alter_creatingteam_company_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprocessdirection",
            name="business_process_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Служебная поездка"),
                    ("2", "Приказы о старших бригадах"),
                ],
                default="",
                max_length=5,
                verbose_name="Тип бизнес процесса",
            ),
        ),
    ]
