# Generated by Django 5.0.3 on 2024-03-28 11:36

import hrdepartment_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0081_placeproductionactivity_additional_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatingteam",
            name="doc_file",
            field=models.FileField(
                blank=True,
                upload_to=hrdepartment_app.models.team_directory_path,
                verbose_name="Файл документа",
            ),
        ),
        migrations.AlterField(
            model_name="creatingteam",
            name="number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Номер приказа",
            ),
        ),
        migrations.AlterField(
            model_name="creatingteam",
            name="scan_file",
            field=models.FileField(
                blank=True,
                upload_to=hrdepartment_app.models.team_directory_path,
                verbose_name="Скан документа",
            ),
        ),
    ]
