# Generated by Django 5.0.3 on 2024-03-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0082_alter_creatingteam_doc_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatingteam",
            name="number",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Номер приказа"
            ),
        ),
    ]
