# Generated by Django 5.0.3 on 2024-03-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0008_alter_companyproperty_options"),
        ("hrdepartment_app", "0084_alter_creatingteam_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creatingteam",
            name="company_property",
        ),
        migrations.AddField(
            model_name="creatingteam",
            name="company_property",
            field=models.ManyToManyField(
                related_name="company_property",
                to="contracts_app.estate",
                verbose_name="Задание на полет",
            ),
        ),
    ]
