# Generated by Django 5.0.3 on 2024-03-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0087_creatingteam_replaceable_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatingteam",
            name="document_type",
            field=models.CharField(
                choices=[("0", "Новый документ"), ("1", "Замещающий документ")],
                default="0",
                max_length=1,
                verbose_name="Тип документа",
            ),
        ),
        migrations.AlterField(
            model_name="creatingteam",
            name="replaceable_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hrdepartment_app.creatingteam",
                verbose_name="Отменяемый документ",
            ),
        ),
    ]
