# Generated by Django 5.0.3 on 2024-03-30 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0088_creatingteam_document_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creatingteam",
            options={
                "ordering": ["-id"],
                "verbose_name": "Создание бригады",
                "verbose_name_plural": "Создание бригад",
            },
        ),
        migrations.AlterModelOptions(
            name="reportcard",
            options={
                "ordering": ("-report_card_day",),
                "verbose_name": "Рабочее время",
                "verbose_name_plural": "Табель учета",
            },
        ),
    ]
