# Generated by Django 5.0.3 on 2024-04-17 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0090_creatingteam_email_send"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medical",
            options={
                "ordering": ["-date_entry"],
                "verbose_name": "Медицинское направление",
                "verbose_name_plural": "Медицинские направления",
            },
        ),
    ]
