# Generated by Django 5.0.3 on 2024-04-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0091_alter_medical_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeproductionactivity",
            name="email",
            field=models.EmailField(
                blank=True, max_length=250, verbose_name="Электронная почта"
            ),
        ),
    ]
