# Generated by Django 5.0.3 on 2024-04-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0092_placeproductionactivity_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatingteam",
            name="email_cancellation_send",
            field=models.BooleanField(
                default=False, verbose_name="Письмо от отмене отправлено"
            ),
        ),
    ]
