# Generated by Django 5.0.3 on 2024-04-26 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0093_creatingteam_email_cancellation_send"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatingteam",
            name="team_brigade",
            field=models.ManyToManyField(
                blank=True,
                related_name="team_brigade",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Состав бригады",
            ),
        ),
    ]
