# Generated by Django 5.0.3 on 2024-05-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0095_alter_reportcard_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="officialmemo",
            name="expenses",
            field=models.BooleanField(default=False, verbose_name="Пометка выплаты"),
        ),
        migrations.AddField(
            model_name="officialmemo",
            name="expenses_summ",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Сумма аванса"
            ),
        ),
    ]
