# Generated by Django 5.0.6 on 2024-06-21 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0097_alter_reportcard_record_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="provisions",
            options={
                "ordering": ["-date_entry"],
                "verbose_name": "Положение",
                "verbose_name_plural": "Положения",
            },
        ),
    ]
