# Generated by Django 5.0.6 on 2024-09-15 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0100_alter_preholidayday_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcard",
            name="timesheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_cards",
                to="hrdepartment_app.timesheet",
                verbose_name="Табель учета рабочего времени",
            ),
        ),
    ]
