# Generated by Django 5.0.6 on 2024-09-15 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0101_reportcard_timesheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheet",
            name="time_sheets_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_sheets_place",
                to="hrdepartment_app.placeproductionactivity",
                verbose_name="МПД",
            ),
        ),
    ]
