# Generated by Django 5.0.6 on 2024-09-18 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0015_alter_contract_date_entry"),
        ("hrdepartment_app", "0102_timesheet_time_sheets_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcard",
            name="air_board",
            field=models.ManyToManyField(
                related_name="company_air_board",
                to="contracts_app.estate",
                verbose_name="Воздушный борт",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="flight_hours",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Летные часы"
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="lunch_time",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Время обеда"
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="sign_report_card",
            field=models.BooleanField(
                default=False, verbose_name="Признак табеля рабочего времени"
            ),
        ),
        migrations.CreateModel(
            name="OperationalWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, verbose_name="Наименование")),
                ("code", models.TextField(blank=True, verbose_name="Код")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "air_bord_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracts_app.typeproperty",
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оперативная работа",
                "verbose_name_plural": "Оперативные работы",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PeriodicWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, verbose_name="Наименование")),
                ("code", models.TextField(blank=True, verbose_name="Код")),
                ("ratio", models.FloatField(blank=True, verbose_name="Ставка")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "air_bord_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracts_app.typeproperty",
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Периодическая работа",
                "verbose_name_plural": "Периодические работы",
                "ordering": ("name",),
            },
        ),
    ]
