# Generated by Django 5.0.6 on 2024-09-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hrdepartment_app",
            "0103_reportcard_air_board_reportcard_flight_hours_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcard",
            name="operational_work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hrdepartment_app.operationalwork",
                verbose_name="Оперативные работы",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="periodic_work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hrdepartment_app.periodicwork",
                verbose_name="Периодические работы",
            ),
        ),
    ]
