# Generated by Django 5.0.6 on 2024-09-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hrdepartment_app",
            "0104_reportcard_operational_work_reportcard_periodic_work",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcard",
            name="additional_work",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Дополнительные работы",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="other_work",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Другие работы"
            ),
        ),
    ]
