# Generated by Django 5.0.6 on 2024-09-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0015_alter_contract_date_entry"),
        ("hrdepartment_app", "0106_alter_periodicwork_ratio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="air_board",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="company_air_board",
                to="contracts_app.estate",
                verbose_name="Воздушный борт",
            ),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="operational_work",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="report_operational",
                to="hrdepartment_app.operationalwork",
                verbose_name="Оперативные работы",
            ),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="periodic_work",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="report_periodic",
                to="hrdepartment_app.periodicwork",
                verbose_name="Периодические работы",
            ),
        ),
    ]
