# Generated by Django 5.0.6 on 2024-09-25 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0015_alter_contract_date_entry"),
        ("hrdepartment_app", "0108_alter_reportcard_air_board_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportcard",
            name="air_board",
        ),
        migrations.RemoveField(
            model_name="reportcard",
            name="operational_work",
        ),
        migrations.RemoveField(
            model_name="reportcard",
            name="other_work",
        ),
        migrations.RemoveField(
            model_name="reportcard",
            name="periodic_work",
        ),
        migrations.CreateModel(
            name="OutfitCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outfit_card_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата"),
                ),
                (
                    "other_work",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Другие работы",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "air_board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_air_board",
                        to="contracts_app.estate",
                        verbose_name="Воздушный борт",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный",
                    ),
                ),
                (
                    "operational_work",
                    models.ManyToManyField(
                        blank=True,
                        related_name="outfit_card_operational",
                        to="hrdepartment_app.operationalwork",
                        verbose_name="Оперативные работы",
                    ),
                ),
                (
                    "outfit_card_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outfit_card_place",
                        to="hrdepartment_app.placeproductionactivity",
                        verbose_name="МПД",
                    ),
                ),
                (
                    "periodic_work",
                    models.ManyToManyField(
                        blank=True,
                        related_name="outfit_card_periodic",
                        to="hrdepartment_app.periodicwork",
                        verbose_name="Периодические работы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта-наряд",
                "verbose_name_plural": "Карты-наряды",
                "ordering": ("-outfit_card_date",),
            },
        ),
    ]
