# Generated by Django 5.0.6 on 2024-09-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0110_reportcard_outfit_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfitcard",
            name="outfit_card_number",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Номер"
            ),
        ),
    ]
