# Generated by Django 5.0.6 on 2024-09-27 10:52

import hrdepartment_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0112_alter_reportcard_place_report_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfitcard",
            name="scan_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=hrdepartment_app.models.outfit_directory_path,
                verbose_name="Скан документа",
            ),
        ),
    ]
