# Generated by Django 5.0.6 on 2024-10-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hrdepartment_app",
            "0114_alter_documentsjobdescription_previous_document_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="outfitcard",
            name="outfit_card_date_end",
            field=models.DateField(blank=True, null=True, verbose_name="Дата"),
        ),
    ]
