# Generated by Django 5.0.6 on 2024-10-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0115_outfitcard_outfit_card_date_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outfitcard",
            name="outfit_card_date_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
    ]
