# Generated by Django 5.0.6 on 2024-11-26 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("hrdepartment_app", "0116_alter_outfitcard_outfit_card_date_end"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAcknowledgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_id", models.PositiveIntegerField()),
                ("acknowledgment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "document_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": (
                                "documentsorder",
                                "creatingteam",
                                "documentsjobdescription",
                                "provisions",
                                "guidancedocuments",
                                "companyevent",
                            )
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_acknowledgments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
