# Generated by Django 5.0.6 on 2024-12-01 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0117_documentacknowledgment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentacknowledgment",
            options={
                "verbose_name": "Подтверждение документа",
                "verbose_name_plural": "Подтверждения документов",
            },
        ),
    ]
