# Generated by Django 5.0.6 on 2024-12-02 13:08

import django.core.validators
import hrdepartment_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0118_alter_documentacknowledgment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsjobdescription",
            name="doc_file",
            field=models.FileField(
                blank=True,
                upload_to=hrdepartment_app.models.jds_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["doc", "docx"]
                    )
                ],
                verbose_name="Файл документа",
            ),
        ),
        migrations.AlterField(
            model_name="documentsjobdescription",
            name="scan_file",
            field=models.FileField(
                blank=True,
                upload_to=hrdepartment_app.models.jds_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Скан документа",
            ),
        ),
    ]
