# Generated by Django 5.0.6 on 2024-12-02 13:22

import django.core.validators
import hrdepartment_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0119_alter_documentsjobdescription_doc_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidancedocuments",
            name="doc_file",
            field=models.FileField(
                blank=True,
                upload_to=hrdepartment_app.models.prv_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["doc", "docx"]
                    )
                ],
                verbose_name="Файл документа",
            ),
        ),
        migrations.AlterField(
            model_name="guidancedocuments",
            name="scan_file",
            field=models.FileField(
                blank=True,
                upload_to=hrdepartment_app.models.prv_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Скан документа",
            ),
        ),
        migrations.AlterField(
            model_name="provisions",
            name="doc_file",
            field=models.FileField(
                blank=True,
                upload_to=hrdepartment_app.models.prv_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["doc", "docx"]
                    )
                ],
                verbose_name="Файл документа",
            ),
        ),
        migrations.AlterField(
            model_name="provisions",
            name="scan_file",
            field=models.FileField(
                blank=True,
                upload_to=hrdepartment_app.models.prv_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Скан документа",
            ),
        ),
    ]
