# Generated by Django 5.0.6 on 2025-02-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0120_alter_guidancedocuments_doc_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeproductionactivity",
            name="work_email_password",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Пароль от корпоративной почты",
            ),
        ),
    ]
