# Generated by Django 5.0.6 on 2025-04-04 08:31

import datetime
import django.core.validators
import django.db.models.deletion
import hrdepartment_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0057_databaseuser_is_ppa"),
        ("hrdepartment_app", "0123_briefings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Operational",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref_key",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="Уникальный номер"
                    ),
                ),
                (
                    "date_entry",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата ввода информации"
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        default="",
                        max_length=200,
                        verbose_name="Наименование документа",
                    ),
                ),
                (
                    "allowed_placed",
                    models.BooleanField(
                        default=False, verbose_name="Разрешение на публикацию"
                    ),
                ),
                (
                    "validity_period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Документ действует с"
                    ),
                ),
                (
                    "validity_period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Документ действует по"
                    ),
                ),
                (
                    "actuality",
                    models.BooleanField(default=False, verbose_name="Актуальность"),
                ),
                (
                    "applying_for_job",
                    models.BooleanField(
                        default=False,
                        verbose_name="Обязательно к ознакомлению при приеме на работу",
                    ),
                ),
                (
                    "document_date",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="Дата документа",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=18,
                        null=True,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "scan_file",
                    models.FileField(
                        blank=True,
                        upload_to=hrdepartment_app.models.opr_directory_path_scan,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                        verbose_name="Скан документа",
                    ),
                ),
                (
                    "document_division",
                    models.ManyToManyField(
                        related_name="operational_document_division",
                        to="customers_app.division",
                        verbose_name="Подразделения",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_executor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "parent_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hrdepartment_app.operational",
                        verbose_name="Предшествующий документ",
                    ),
                ),
                (
                    "storage_location_division",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operational_location_division",
                        to="customers_app.division",
                        verbose_name="Подразделение где хранится оригинал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Нормативный акт",
                "verbose_name_plural": "Нормативные акты",
                "ordering": ["-document_date"],
            },
        ),
    ]
