# Generated by Django 5.0.6 on 2025-07-10 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0124_operational"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataBaseUserEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_marks",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата отметки"
                    ),
                ),
                (
                    "checked",
                    models.BooleanField(default=False, verbose_name="Проверено"),
                ),
                ("road", models.BooleanField(default=False, verbose_name="В дороге")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hrdepartment_app.placeproductionactivity",
                        verbose_name="Место",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отметка",
                "verbose_name_plural": "Отметки",
            },
        ),
    ]
