# Generated by Django 5.0.6 on 2025-07-11 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0125_databaseuserevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="databaseuserevent",
            index=models.Index(
                fields=["person", "date_marks"], name="hrdepartmen_person__3eae3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="databaseuserevent",
            index=models.Index(
                fields=["checked"], name="hrdepartmen_checked_72ffc4_idx"
            ),
        ),
    ]
