# Generated by Django 5.0.6 on 2025-07-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hrdepartment_app",
            "0126_databaseuserevent_hrdepartmen_person__3eae3f_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="briefings",
            name="document_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="documentsjobdescription",
            name="document_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="documentsorder",
            name="document_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="guidancedocuments",
            name="document_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="instructions",
            name="document_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="operational",
            name="document_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="provisions",
            name="document_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
