# Generated by Django 5.0.6 on 2025-07-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0127_briefings_document_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatingteam",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="medical",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="outfitcard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
