# Generated by Django 5.0.6 on 2025-07-14 14:42

import django.core.validators
import hrdepartment_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hrdepartment_app",
            "0128_creatingteam_updated_at_medical_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidancedocuments",
            name="doc_file",
            field=models.FileField(
                blank=True,
                upload_to=hrdepartment_app.models.gdc_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["doc", "docx"]
                    )
                ],
                verbose_name="Файл документа",
            ),
        ),
        migrations.AlterField(
            model_name="guidancedocuments",
            name="scan_file",
            field=models.FileField(
                blank=True,
                upload_to=hrdepartment_app.models.gdc_directory_path_scan,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Скан документа",
            ),
        ),
        migrations.AlterField(
            model_name="instructions",
            name="scan_file",
            field=models.FileField(
                blank=True,
                upload_to=hrdepartment_app.models.ins_directory_path_scan,
                verbose_name="Скан документа",
            ),
        ),
        migrations.AlterField(
            model_name="medical",
            name="medical_direction",
            field=models.FileField(blank=True, upload_to="", verbose_name="Файл ПМО"),
        ),
        migrations.AlterField(
            model_name="medical",
            name="medical_direction2",
            field=models.FileField(blank=True, upload_to="", verbose_name="Файл ПО"),
        ),
        migrations.AlterField(
            model_name="provisions",
            name="scan_file",
            field=models.FileField(
                blank=True,
                upload_to=hrdepartment_app.models.prv_directory_path_scan,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Скан документа",
            ),
        ),
    ]
