# Generated by Django 5.0.6 on 2025-11-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0130_alter_businessprocessdirection_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsorder",
            name="custom_file",
            field=models.BooleanField(
                default=False, verbose_name="Ручная загрузка приказа"
            ),
        ),
    ]
