# Generated by Django 5.0.6 on 2025-11-13 13:15

import datetime
import django.db.models.deletion
import hrdepartment_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0060_databaseuser_updated_at"),
        ("hrdepartment_app", "0131_documentsorder_custom_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LaborProtectionInstructions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref_key",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="Уникальный номер"
                    ),
                ),
                (
                    "date_entry",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата ввода информации"
                    ),
                ),
                (
                    "document_date",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Дата документа"
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        default="",
                        max_length=200,
                        verbose_name="Наименование документа",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        default="", max_length=18, verbose_name="Номер документа"
                    ),
                ),
                (
                    "allowed_placed",
                    models.BooleanField(
                        default=False, verbose_name="Разрешение на публикацию"
                    ),
                ),
                (
                    "validity_period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Документ действует с"
                    ),
                ),
                (
                    "validity_period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Документ действует по"
                    ),
                ),
                (
                    "actuality",
                    models.BooleanField(default=False, verbose_name="Актуальность"),
                ),
                (
                    "previous_document",
                    models.URLField(
                        blank=True,
                        verbose_name="Примечание к предшествующему документу",
                    ),
                ),
                ("document_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_file",
                    models.FileField(
                        blank=True,
                        upload_to=hrdepartment_app.models.lpi_directory_path,
                        verbose_name="Файл документа",
                    ),
                ),
                (
                    "scan_file",
                    models.FileField(
                        blank=True,
                        upload_to=hrdepartment_app.models.lpi_directory_path_scan,
                        verbose_name="Скан документа",
                    ),
                ),
                (
                    "access",
                    models.ForeignKey(
                        default=5,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers_app.accesslevel",
                        verbose_name="Уровень доступа к документу",
                    ),
                ),
                (
                    "document_division",
                    models.ManyToManyField(
                        related_name="lp_instruction_document_division",
                        to="customers_app.division",
                        verbose_name="Подразделения",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_executor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "parent_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hrdepartment_app.laborprotectioninstructions",
                        verbose_name="Предшествующий документ",
                    ),
                ),
                (
                    "storage_location_division",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lp_instruction_location_division",
                        to="customers_app.division",
                        verbose_name="Подразделение где хранится оригинал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инструкция по охране труда",
                "verbose_name_plural": "Инструкции по охране труда",
            },
        ),
    ]
