# Generated by Django 5.0.6 on 2025-11-13 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0132_laborprotectioninstructions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="laborprotectioninstructions",
            options={
                "verbose_name": "Инструкция по ТО ВС",
                "verbose_name_plural": "Инструкции по ТО ВС",
            },
        ),
    ]
