# Generated by Django 5.0.6 on 2026-01-21 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0062_alter_apartments_place"),
        ("hrdepartment_app", "0133_alter_laborprotectioninstructions_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_name",
                    models.CharField(max_length=300, verbose_name="Наименование"),
                ),
            ],
            options={
                "verbose_name": "Программа обучения",
                "verbose_name_plural": "Программы обучения",
            },
        ),
        migrations.CreateModel(
            name="TrainingUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_name",
                    models.CharField(max_length=350, verbose_name="Наименование"),
                ),
                (
                    "program_units",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hrdepartment_app.trainingprogram",
                        verbose_name="Программа обучения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модуль",
                "verbose_name_plural": "Модули",
            },
        ),
        migrations.CreateModel(
            name="StudentAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_agreement_number",
                    models.CharField(
                        max_length=100,
                        verbose_name="№ ученического договора с работником",
                    ),
                ),
                (
                    "student_agreement_date",
                    models.DateField(verbose_name="Дата ученического договора"),
                ),
                (
                    "contract_number",
                    models.CharField(max_length=100, verbose_name="№ договора"),
                ),
                ("contract_date", models.DateField(verbose_name="Дата договора")),
                (
                    "training_place",
                    models.CharField(
                        max_length=255, verbose_name="Место оказания услуг"
                    ),
                ),
                (
                    "training_start_date",
                    models.DateField(verbose_name="Дата начала обучения"),
                ),
                (
                    "training_end_date",
                    models.DateField(verbose_name="Дата окончания обучения"),
                ),
                (
                    "training_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сумма обучения, руб.",
                    ),
                ),
                (
                    "work_period_years",
                    models.PositiveSmallIntegerField(
                        verbose_name="Срок отработки (года)"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "full_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ф.И.О.",
                    ),
                ),
                (
                    "training_center_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers_app.counteragent",
                        verbose_name="Наименование АУЦ",
                    ),
                ),
                (
                    "training_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hrdepartment_app.trainingprogram",
                        verbose_name="Программа обучения",
                    ),
                ),
                (
                    "training_unit",
                    models.ManyToManyField(
                        to="hrdepartment_app.trainingunit", verbose_name="Модули"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ученический договор",
                "verbose_name_plural": "Ученические договоры",
            },
        ),
    ]
