# Generated by Django 5.0.6 on 2026-01-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0134_trainingprogram_trainingunit_studentagreement"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvaloficialmemoprocess",
            name="accommodation_expense",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Дополнительное проживание",
            ),
        ),
        migrations.AddField(
            model_name="approvaloficialmemoprocess",
            name="daily_allowance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Суточные"
            ),
        ),
        migrations.AddField(
            model_name="approvaloficialmemoprocess",
            name="other_expense",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Прочие расходы",
            ),
        ),
        migrations.AddField(
            model_name="approvaloficialmemoprocess",
            name="travel_expense",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Проезд"
            ),
        ),
    ]
