# Generated by Django 5.0.6 on 2026-03-11 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0067_counteragent_educational_organization"),
        ("hrdepartment_app", "0136_alter_studentagreement_training_center_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingprogram",
            name="counteragent_name",
            field=models.ForeignKey(
                limit_choices_to={"educational_organization": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="customers_app.counteragent",
                verbose_name="Наименование АУЦ",
            ),
        ),
    ]
