# Generated by Django 5.0.6 on 2026-03-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0137_alter_trainingprogram_counteragent_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentagreement",
            name="training_unit",
            field=models.ManyToManyField(
                blank=True, to="hrdepartment_app.trainingunit", verbose_name="Модули"
            ),
        ),
    ]
