# Generated by Django 5.0.6 on 2026-03-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0138_alter_studentagreement_training_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentagreement",
            name="academic_hours",
            field=models.IntegerField(default=0, verbose_name="академических часа"),
        ),
        migrations.AddField(
            model_name="studentagreement",
            name="form_education",
            field=models.CharField(
                choices=[
                    ("full_time", "очная"),
                    ("part_time", "заочная"),
                    ("distance", "дистанционно"),
                ],
                default="full_time",
                max_length=20,
                verbose_name="Форма обучения",
            ),
        ),
    ]
