# Generated by Django 5.0.6 on 2026-03-13 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_app", "0016_contract_updated_at"),
        ("hrdepartment_app", "0139_studentagreement_academic_hours_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentagreement",
            name="contract_date",
        ),
        migrations.RemoveField(
            model_name="studentagreement",
            name="contract_number",
        ),
        migrations.AddField(
            model_name="studentagreement",
            name="counteragent_contract",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите договор из системы",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_counteragent_contract",
                to="contracts_app.contract",
                verbose_name="Договор",
            ),
        ),
    ]
