# Generated by Django 5.0.6 on 2026-03-18 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0140_remove_studentagreement_contract_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentagreement",
            options={
                "ordering": ["-student_agreement_number"],
                "verbose_name": "Ученический договор",
                "verbose_name_plural": "Ученические договоры",
            },
        ),
    ]
