# Generated by Django 5.0.6 on 2026-03-18 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0143_alter_studentagreement_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentagreement",
            options={
                "ordering": ["student_agreement_number", "-student_agreement_date"],
                "verbose_name": "Ученический договор",
                "verbose_name_plural": "Ученические договоры",
            },
        ),
    ]
