# Generated by Django 5.0.6 on 2026-03-18 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0144_alter_studentagreement_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentagreement",
            options={
                "ordering": [
                    "-student_agreement_date__year",
                    "-student_agreement_number",
                ],
                "verbose_name": "Ученический договор",
                "verbose_name_plural": "Ученические договоры",
            },
        ),
    ]
