# Generated by Django 5.0.6 on 2026-03-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0145_alter_studentagreement_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentagreement",
            name="remotely",
            field=models.BooleanField(
                default=False, verbose_name="С отрывом от работы"
            ),
        ),
    ]
