# Generated by Django 5.0.6 on 2026-03-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0146_studentagreement_remotely"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentagreement",
            name="remotely",
            field=models.BooleanField(default=True, verbose_name="С отрывом от работы"),
        ),
    ]
