# Generated by Django 5.0.6 on 2026-03-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0147_alter_studentagreement_remotely"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingunit",
            name="unit_name_short",
            field=models.CharField(
                default="", max_length=30, verbose_name="Краткое наименование"
            ),
        ),
        migrations.AlterField(
            model_name="trainingunit",
            name="unit_name",
            field=models.CharField(max_length=350, verbose_name="Полное наименование"),
        ),
    ]
