# Generated by Django 5.0.6 on 2026-03-19 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0071_alter_apartmentbooking_date_created"),
        ("hrdepartment_app", "0148_trainingunit_unit_name_short_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvaloficialmemoprocess",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers_app.apartments",
            ),
        ),
    ]
