# Generated by Django 5.2.12 on 2026-03-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0149_approvaloficialmemoprocess_apartment"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentagreement",
            name="signed",
            field=models.BooleanField(default=False, verbose_name="Подписан"),
        ),
    ]
