# Generated by Django 5.2.12 on 2026-04-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0150_studentagreement_signed"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeproductionactivity",
            name="in_planning",
            field=models.BooleanField(
                default=False, verbose_name="Используется в планировании"
            ),
        ),
    ]
