# Generated by Django 5.2.12 on 2026-04-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0151_placeproductionactivity_in_planning"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvaloficialmemoprocess",
            name="check_apart",
            field=models.BooleanField(
                default=True, verbose_name="Не проверять квартиру"
            ),
        ),
    ]
