# Generated by Django 5.2.12 on 2026-06-09 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0152_approvaloficialmemoprocess_check_apart"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="trainingunit",
            unique_together={("program_units", "unit_name_short")},
        ),
    ]
