# Generated by Django 5.2.12 on 2026-06-11 14:19

import datetime
import django.core.validators
import django.db.models.deletion
import hrdepartment_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0153_alter_trainingunit_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PowerOfAttorney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Уникальный номер доверенности",
                        max_length=50,
                        verbose_name="Номер доверенности",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Дата выдачи"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(verbose_name="Дата окончания действия"),
                ),
                (
                    "initiator_name",
                    models.CharField(max_length=255, verbose_name="ФИО инициатора"),
                ),
                (
                    "initiator_position",
                    models.CharField(
                        max_length=255, verbose_name="Должность инициатора"
                    ),
                ),
                (
                    "grantee_name",
                    models.CharField(max_length=255, verbose_name="ФИО поверенного"),
                ),
                (
                    "grantee_position",
                    models.CharField(
                        max_length=255, verbose_name="Должность поверенного"
                    ),
                ),
                (
                    "organization_target",
                    models.CharField(
                        help_text="Наименование организации, для которой выдана доверенность",
                        max_length=255,
                        verbose_name="Организация/Орган",
                    ),
                ),
                (
                    "cancellation_date",
                    models.DateField(
                        blank=True,
                        help_text="Заполняется в случае досрочного отзыва",
                        null=True,
                        verbose_name="Дата отмены",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=hrdepartment_app.models.custom_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Скан документа",
                    ),
                ),
                (
                    "is_received",
                    models.BooleanField(default=False, verbose_name="Получена подпись"),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата и время получения"
                    ),
                ),
                (
                    "date_entry",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата ввода информации"
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="poa_executor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "received_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_poas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто зафиксировал получение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доверенность",
                "verbose_name_plural": "Доверенности",
                "ordering": ["-issue_date", "-number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("number", "issue_date"),
                        name="unique_poa_number_per_date",
                    )
                ],
            },
        ),
    ]
