# Generated by Django 5.2.12 on 2026-06-15 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers_app", "0078_consenttype_biometricconsent_consent_type_and_more"),
        ("hrdepartment_app", "0154_powerofattorney"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="powerofattorney",
            name="grantee_name_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grantee_poas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто зафиксировал получение",
            ),
        ),
        migrations.AddField(
            model_name="powerofattorney",
            name="initiator_name_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiator_poas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто зафиксировал получение",
            ),
        ),
        migrations.AddField(
            model_name="powerofattorney",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_poas",
                to="customers_app.counteragent",
                verbose_name="Организация/Орган",
            ),
        ),
    ]
