# Generated by Django 5.2.12 on 2026-06-15 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0155_powerofattorney_grantee_name_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="powerofattorney",
            name="grantee_name",
        ),
        migrations.RemoveField(
            model_name="powerofattorney",
            name="grantee_position",
        ),
        migrations.RemoveField(
            model_name="powerofattorney",
            name="initiator_name",
        ),
        migrations.RemoveField(
            model_name="powerofattorney",
            name="initiator_position",
        ),
        migrations.RemoveField(
            model_name="powerofattorney",
            name="organization_target",
        ),
        migrations.AlterField(
            model_name="powerofattorney",
            name="grantee_name_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grantee_poas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ФИО поверенного",
            ),
        ),
        migrations.AlterField(
            model_name="powerofattorney",
            name="initiator_name_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiator_poas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ФИО инициатора",
            ),
        ),
    ]
