# Generated by Django 5.2.12 on 2026-06-15 08:00

import django.core.validators
import hrdepartment_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0156_remove_powerofattorney_grantee_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="powerofattorney",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=hrdepartment_app.models.poa_directory_path_scan,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="Скан документа",
            ),
        ),
    ]
