# Generated by Django 5.2.12 on 2026-06-15 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0157_alter_powerofattorney_document"),
    ]

    operations = [
        migrations.RenameField(
            model_name="powerofattorney",
            old_name="document",
            new_name="scan_file",
        ),
    ]
