# Generated by Django 5.2.12 on 2026-06-15 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0158_rename_document_powerofattorney_scan_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprocessroutes",
            name="business_process_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Служебная поездка"),
                    ("2", "Приказы о старших бригадах"),
                    ("3", "Доверенности"),
                ],
                default="",
                max_length=5,
                verbose_name="Тип бизнес процесса",
            ),
        ),
        migrations.AlterField(
            model_name="businessprocessroutes",
            name="person_clerk",
            field=models.ManyToManyField(
                blank=True,
                related_name="bp_person_clerk",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Делопроизводитель/Инициатор",
            ),
        ),
    ]
