# Generated by Django 5.2.12 on 2026-08-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hrdepartment_app",
            "0159_alter_businessprocessroutes_business_process_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="studentagreement",
            name="work_period_month",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Срок отработки (месяцы)"
            ),
        ),
    ]
