# Generated by Django 5.2.12 on 2026-08-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0160_studentagreement_work_period_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentagreement",
            name="work_period_years",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Срок отработки (года)"
            ),
        ),
    ]
