# Generated by Django 5.2.12 on 2026-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0161_alter_studentagreement_work_period_years"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvaloficialmemoprocess",
            name="date_of_arrival",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата приезда на МПД"
            ),
        ),
        migrations.AddField(
            model_name="approvaloficialmemoprocess",
            name="date_of_departure",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата отъезда с МПД"
            ),
        ),
        migrations.AddField(
            model_name="placeproductionactivity",
            name="ticket_control",
            field=models.BooleanField(
                default=False, verbose_name="Вести контроль билетов"
            ),
        ),
    ]
