# Generated by Django on 2026-09-08
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0162_approvaloficialmemoprocess_date_of_arrival_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheet",
            name="is_draft",
            field=models.BooleanField(default=True, verbose_name="Черновик"),
        ),
    ]
