# Generated by Django 5.2.12 on 2026-09-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0163_timesheet_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalorganisation",
            name="alternative_name",
            field=models.CharField(
                default="", max_length=300, verbose_name="Наименование"
            ),
        ),
        migrations.AlterField(
            model_name="medicalorganisation",
            name="description",
            field=models.CharField(
                default="", max_length=250, verbose_name="Наименование"
            ),
        ),
    ]
