# Generated by Django 5.2.12 on 2026-09-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrdepartment_app", "0164_medicalorganisation_alternative_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeproductionactivity",
            name="icao_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="4-буквенный ICAO код ближайшего аэродрома/метеостанции (например, UNNT, USRR, ULLI, UUEE)",
                max_length=4,
                verbose_name="Код ICAO метеостанции",
            ),
        ),
        migrations.AddField(
            model_name="placeproductionactivity",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="Географическая широта объекта в градусах",
                null=True,
                verbose_name="Широта",
            ),
        ),
        migrations.AddField(
            model_name="placeproductionactivity",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="Географическая долгота объекта в градусах",
                null=True,
                verbose_name="Долгота",
            ),
        ),
        migrations.AddField(
            model_name="placeproductionactivity",
            name="weather_monitoring_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Автоматический сбор и архивирование METAR/TAF сводок",
                verbose_name="Мониторинг погоды",
            ),
        ),
    ]
