# Generated by Django 6.1.1 on 2026-09-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0165_placeproductionactivity_icao_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeproductionactivity',
            name='elevation_msl_m',
            field=models.FloatField(blank=True, help_text='Абсолютная высота площадки над средним уровнем моря (MSL) в метрах', null=True, verbose_name='Высота над уровнем моря (MSL, м)'),
        ),
        migrations.AddField(
            model_name='placeproductionactivity',
            name='elevation_source',
            field=models.CharField(choices=[('MANUAL', 'Ручной ввод'), ('DEM', 'Цифровая модель рельефа (DEM)'), ('AERODROME', 'Аэродромная съемка'), ('IMPORTED', 'Импорт из 1С')], default='MANUAL', help_text='Метод определения высотной отметки площадки', max_length=20, verbose_name='Источник высоты'),
        ),
        migrations.AddField(
            model_name='placeproductionactivity',
            name='weather_source_preference',
            field=models.CharField(choices=[('AUTO', 'Авто (METAR при наличии, иначе координаты)'), ('METAR_ONLY', 'Только METAR'), ('COORDINATES_ONLY', 'Только расчёт по координатам')], default='AUTO', help_text='Правило выбора источника метеоданных для МПД', max_length=20, verbose_name='Приоритет источника погоды'),
        ),
    ]
