# Generated by Django 6.1.1 on 2026-09-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0166_placeproductionactivity_elevation_msl_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeproductionactivity',
            name='weather_last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время последнего успешного опроса метеоданных (UTC)', null=True, verbose_name='Время последней синхронизации погоды'),
        ),
        migrations.AddField(
            model_name='placeproductionactivity',
            name='weather_sync_status',
            field=models.CharField(blank=True, default='', help_text='Результат последней синхронизации (например, OK, NO_DATA, ERROR)', max_length=50, verbose_name='Статус последней синхронизации'),
        ),
    ]
