# Generated by Django 6.1.1 on 2026-09-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0017_estate_decommission_date'),
        ('hrdepartment_app', '0167_placeproductionactivity_weather_last_sync_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodicwork',
            options={'ordering': ('air_bord_type', 'ratio', 'name'), 'verbose_name': 'Периодическая работа', 'verbose_name_plural': 'Периодические работы'},
        ),
        migrations.AddField(
            model_name='periodicwork',
            name='color',
            field=models.CharField(blank=True, choices=[('yellow', 'желтый'), ('green', 'зеленый'), ('red', 'красный')], default='green', help_text='Цветовая индикация периодической работы (желтый, зеленый, красный)', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='periodicwork',
            name='lag_minus',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Число часов отклонения (минус)', verbose_name='Лаг минус'),
        ),
        migrations.AddField(
            model_name='periodicwork',
            name='lag_plus',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Число часов отклонения (плюс)', verbose_name='Лаг плюс'),
        ),
        migrations.AlterField(
            model_name='periodicwork',
            name='air_bord_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_works', to='contracts_app.typeproperty', verbose_name='Тип ВС'),
        ),
        migrations.AlterField(
            model_name='periodicwork',
            name='ratio',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Норма-часы'),
        ),
    ]
