# Generated by Django 6.1.1 on 2026-10-01 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0017_estate_decommission_date'),
        ('hrdepartment_app', '0168_alter_periodicwork_options_periodicwork_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationalwork',
            options={'ordering': ('air_bord_type', 'name'), 'verbose_name': 'Оперативная работа', 'verbose_name_plural': 'Оперативные работы'},
        ),
        migrations.AlterField(
            model_name='operationalwork',
            name='air_bord_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_works', to='contracts_app.typeproperty', verbose_name='Тип ВС'),
        ),
    ]
