# Generated by Django 6.1.1 on 2026-10-01 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0169_alter_operationalwork_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitcard',
            name='certifying_staff',
            field=models.ForeignKey(blank=True, help_text='Специалист подтверждающего персонала, выпустивший ВС', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_outfit_cards', to=settings.AUTH_USER_MODEL, verbose_name='Подтверждающий персонал'),
        ),
        migrations.AddField(
            model_name='outfitcard',
            name='crs_number',
            field=models.CharField(blank=True, default='', help_text='Порядковый номер Свидетельства о выполненном ТО ВС', max_length=50, verbose_name='Номер свидетельства о ТО (CRS)'),
        ),
        migrations.AddField(
            model_name='outfitcard',
            name='deferred_defects',
            field=models.TextField(blank=True, default='', help_text='Перечень дефектов, перенесенных по процедурам MEL/CDL/РЭ', verbose_name='Перенесенные дефекты'),
        ),
        migrations.AddField(
            model_name='outfitcard',
            name='deferred_defects_agreed',
            field=models.BooleanField(default=False, help_text='Отметка о согласовании переноса срока устранения дефектов с эксплуатантом ВС', verbose_name='Перенос согласован с эксплуатантом'),
        ),
        migrations.AddField(
            model_name='outfitcard',
            name='flight_cycles',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Количество посадок/циклов с начала эксплуатации', null=True, verbose_name='Посадки / циклы'),
        ),
        migrations.AddField(
            model_name='outfitcard',
            name='flight_hours',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='Наработка планера с начала эксплуатации в часах', max_digits=9, null=True, verbose_name='Наработка СНЭ (ч)'),
        ),
        migrations.AddField(
            model_name='outfitcard',
            name='flight_hours_tsor',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='Наработка планера после последнего ремонта в часах', max_digits=9, null=True, verbose_name='Наработка ППР (ч)'),
        ),
        migrations.AddField(
            model_name='outfitcard',
            name='is_signed',
            field=models.BooleanField(db_index=True, default=False, help_text='Флаг закрытия наряда и выпуска Свидетельства о ТО', verbose_name='Наряд закрыт и подписан'),
        ),
        migrations.AddField(
            model_name='outfitcard',
            name='signature_hash',
            field=models.CharField(blank=True, default='', help_text='Контрольная сумма SHA-256 для гарантии неизменяемости по п. 40 ФАП-367', max_length=64, verbose_name='Хэш неизменяемости (SHA-256)'),
        ),
        migrations.AddField(
            model_name='outfitcard',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время подписания'),
        ),
    ]
