# Generated by Django 6.1.1 on 2026-10-01 14:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0017_estate_decommission_date'),
        ('hrdepartment_app', '0170_outfitcard_certifying_staff_outfitcard_crs_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftHoursTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(db_index=True, help_text='Календарная дата среза наработки', verbose_name='Дата фиксации наработки')),
                ('flight_hours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Наработка планера ВС с начала эксплуатации в часах', max_digits=9, verbose_name='Наработка СНЭ (ч)')),
                ('flight_hours_tsor', models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), help_text='Наработка планера ВС после последнего ремонта (ППР) в часах', max_digits=9, null=True, verbose_name='Наработка ППР (ч)')),
                ('flight_cycles', models.PositiveIntegerField(blank=True, default=0, help_text='Количество посадок/циклов с начала эксплуатации', null=True, verbose_name='Количество посадок / циклов')),
                ('source', models.CharField(choices=[('manual', 'Ручной ввод'), ('import', 'Импорт из файла (Excel/CSV)'), ('outfit_card', 'Карта-наряд на ТО')], default='manual', help_text='Способ внесения данных: ручной ввод, импорт из Excel или карта-наряд', max_length=20, verbose_name='Источник данных')),
                ('notes', models.TextField(blank=True, default='', help_text='Служебные примечания к записи наработки', verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('air_board', models.ForeignKey(help_text='Воздушное судно, для которого фиксируется наработка', on_delete=django.db.models.deletion.CASCADE, related_name='hours_tracking_records', to='contracts_app.estate', verbose_name='Воздушное судно')),
                ('created_by', models.ForeignKey(blank=True, help_text='Сотрудник, зафиксировавший показатели наработки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hours_tracking', to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('outfit_card', models.ForeignKey(blank=True, help_text='Связанная карта-наряд на ТО (если запись создана автоматически)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hours_tracking_entries', to='hrdepartment_app.outfitcard', verbose_name='Карта-наряд')),
            ],
            options={
                'verbose_name': 'Учет наработки ВС',
                'verbose_name_plural': 'Учет наработки ВС',
                'ordering': ('-record_date', '-created_at'),
                'indexes': [models.Index(fields=['air_board', '-record_date'], name='idx_hours_aircraft_date'), models.Index(fields=['record_date'], name='idx_hours_record_date')],
            },
        ),
    ]
