# Generated by Django 6.1.1 on 2026-10-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0171_aircrafthourstracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitcard',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Время окончания ТО в формате ЧЧ:ММ (UTC)', null=True, verbose_name='Время окончания (UTC)'),
        ),
        migrations.AddField(
            model_name='outfitcard',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Время начала ТО в формате ЧЧ:ММ (UTC)', null=True, verbose_name='Время начала (UTC)'),
        ),
    ]
