# Generated by Django 6.1.1 on 2026-10-02 10:11

import django.db.models.deletion
import hrdepartment_app.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0017_estate_decommission_date'),
        ('customers_app', '0088_databaseuser_personal_groups'),
        ('hrdepartment_app', '0172_outfitcard_end_time_outfitcard_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMaintenanceOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Официальное наименование авиаремонтного завода или организации по ТО', max_length=255, verbose_name='Полное наименование')),
                ('short_name', models.CharField(help_text="Сокращенное наименование (например, АО 'СПАРК', АО '218 АРЗ')", max_length=150, verbose_name='Краткое наименование')),
                ('certificate_number', models.CharField(db_index=True, help_text='Номер действующего сертификата организации по ТО (напр., СПАС-ТО-145-2023-01)', max_length=100, verbose_name='Номер сертификата ТО')),
                ('certificate_agency', models.CharField(default='Федеральное агентство воздушного транспорта (Росавиация)', help_text='Наименование уполномоченного органа в области гражданской авиации', max_length=150, verbose_name='Орган, выдавший сертификат')),
                ('certificate_issue_date', models.DateField(help_text='Дата первоначальной выдачи или последнего продления сертификата', verbose_name='Дата выдачи сертификата')),
                ('certificate_valid_until', models.DateField(blank=True, help_text='Оставьте пустым, если сертификат действует бессрочно с периодическим контролем', null=True, verbose_name='Срок действия сертификата')),
                ('approved_categories', models.TextField(help_text='Область деятельности по сертификату: категории B1, B2, B3, C1-C20, конкретные типы компонентов', verbose_name='Разрешенные категории и компоненты')),
                ('contract_number', models.CharField(blank=True, default='', help_text='Реквизиты действующего договора на ТО и ремонт компонентов', max_length=150, verbose_name='Номер и дата договора')),
                ('contract_file', models.FileField(blank=True, help_text='Электронная копия договора с привлекаемой организацией', null=True, upload_to='subcontractors/contracts/', verbose_name='Скан договора')),
                ('certificate_scan', models.FileField(blank=True, help_text='Электронная копия действующего сертификата организации по ТО', null=True, upload_to=hrdepartment_app.models.subcontractor_certificate_upload_path, verbose_name='Скан сертификата ТО')),
                ('is_active', models.BooleanField(default=True, help_text='Флаг активного допуска привлекаемой организации к выполнению работ', verbose_name='Одобренный статус (активен)')),
                ('notes', models.TextField(blank=True, default='', help_text='Дополнительные условия, контакты ОТК, ограничения', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('counteragent', models.ForeignKey(blank=True, help_text='Связанная карточка контрагента из 1С:Предприятие', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_subcontractor_profiles', to='customers_app.counteragent', verbose_name='Контрагент 1С')),
            ],
            options={
                'verbose_name': 'Привлеченная организация по ТО',
                'verbose_name_plural': 'Привлеченные организации по ТО (ФАП-367)',
                'ordering': ('short_name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AviationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование агрегата (напр., Двигатель ТВ2-117А, Редуктор ВР-8А, Насос НШ-39М)', max_length=200, verbose_name='Наименование компонента')),
                ('part_number', models.CharField(db_index=True, help_text='Чертежный номер детали/агрегата по каталогу', max_length=100, verbose_name='Чертежный номер (P/N)')),
                ('serial_number', models.CharField(db_index=True, help_text='Серийный или заводской номер экземпляра компонента', max_length=100, verbose_name='Заводской номер (S/N)')),
                ('status', models.CharField(choices=[('stock', 'На складе (годен к установке)'), ('installed', 'Установлен на ВС'), ('repair', 'В ремонте у сторонней организации'), ('scrapped', 'Списан / Брак / Ресурс исчерпан')], default='stock', help_text='Текущее физическое состояние и местонахождение компонента', max_length=20, verbose_name='Статус годности')),
                ('release_doc_type', models.CharField(choices=[('form_1', 'Талон годности компонента (Приложение № 2 к ФАП-367 / Form 1)'), ('passport', 'Паспорт / Формуляр агрегата завода'), ('label', 'Этикетка / Талон завода-изготовителя'), ('other', 'Иной входящий документ о годности')], default='form_1', help_text='Вид документа, подтверждающего годность компонента перед установкой (п. 28 ФАП-367)', max_length=20, verbose_name='Вид входящего документа')),
                ('release_doc_number', models.CharField(blank=True, default='', help_text='Номер Талона годности по Приложению № 2, паспорта или этикетки', max_length=100, verbose_name='Номер документа о годности')),
                ('release_doc_date', models.DateField(blank=True, help_text='Дата оформления входящего документа о годности сторонней организацией', null=True, verbose_name='Дата документа о годности')),
                ('release_doc_file', models.FileField(blank=True, help_text='Электронная скан-копия входящего Талона годности или паспорта агрегата', null=True, upload_to=hrdepartment_app.models.component_release_doc_upload_path, verbose_name='Скан документа о годности')),
                ('hours_since_new', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Наработка компонента с начала эксплуатации в часах', max_digits=9, verbose_name='Наработка СНЭ (ч)')),
                ('hours_since_overhaul', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Наработка компонента после последнего ремонта в часах', max_digits=9, verbose_name='Наработка ППР (ч)')),
                ('resource_limit_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Полный назначенный ресурс компонента в часах', max_digits=9, null=True, verbose_name='Назначенный ресурс (ч)')),
                ('remaining_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Остаток ресурса до очередного ТО или списания', max_digits=9, null=True, verbose_name='Остаток ресурса (ч)')),
                ('notes', models.TextField(blank=True, default='', help_text='Особые отметки, консервация, рекламации', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('aircraft_type', models.ForeignKey(blank=True, help_text='Тип воздушного судна, на котором применяется компонент', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aviation_components', to='contracts_app.typeproperty', verbose_name='Тип ВС')),
                ('current_aircraft', models.ForeignKey(blank=True, help_text="Воздушное судно, на котором смонтирован компонент (при статусе 'Установлен')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_components', to='contracts_app.estate', verbose_name='Установлен на ВС')),
                ('last_repair_org', models.ForeignKey(blank=True, help_text='Сторонняя сертифицированная организация (АРЗ), выполнившая последнее ТО или оверхол', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repaired_components', to='hrdepartment_app.externalmaintenanceorganization', verbose_name='Привлеченная организация (последнее ТО)')),
            ],
            options={
                'verbose_name': 'Авиационный компонент',
                'verbose_name_plural': 'Авиационные компоненты (ФАП-367)',
                'ordering': ('name', 'part_number', 'serial_number'),
            },
        ),
        migrations.CreateModel(
            name='OutfitCardComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('install', 'Установка компонента'), ('remove', 'Демонтаж (снятие) компонента'), ('replace', 'Замена (снятие и установка)')], default='replace', help_text='Характер выполняемой операции с компонентом', max_length=20, verbose_name='Тип операции')),
                ('removed_component_name', models.CharField(blank=True, default='', help_text='Наименование демонтированного с ВС компонента', max_length=200, verbose_name='Наименование снятого агрегата')),
                ('removed_part_number', models.CharField(blank=True, default='', help_text='Чертежный номер снятого агрегата', max_length=100, verbose_name='Чертежный номер снятого (P/N)')),
                ('removed_serial_number', models.CharField(blank=True, default='', help_text='Заводской/серийный номер снятого агрегата', max_length=100, verbose_name='Заводской номер снятого (S/N)')),
                ('removal_reason', models.CharField(blank=True, default='Плановая замена по выработке ресурса', help_text='Причина демонтажа: выработка ресурса, отказ, плановое ТО, бюллетень', max_length=255, verbose_name='Причина снятия')),
                ('operating_hours_on_install', models.DecimalField(blank=True, decimal_places=1, help_text='Показания наработки планера ВС на дату проведения операции', max_digits=9, null=True, verbose_name='Наработка ВС на момент установки (ч)')),
                ('installed_position', models.CharField(blank=True, default='', help_text='Позиция агрегата на борту (напр., Двигатель левый, Рулевой винт)', max_length=150, verbose_name='Место установки на ВС')),
                ('notes', models.TextField(blank=True, default='', help_text='Дополнительные сведения о монтаже', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('installed_component', models.ForeignKey(blank=True, help_text='Устанавливаемый агрегат с действующим входящим документом о годности', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_installations', to='hrdepartment_app.aviationcomponent', verbose_name='Устанавливаемый агрегат')),
                ('outfit_card', models.ForeignKey(help_text='Карта-наряд, в рамках которой выполняются работы с компонентом', on_delete=django.db.models.deletion.CASCADE, related_name='component_operations', to='hrdepartment_app.outfitcard', verbose_name='Карта-наряд')),
            ],
            options={
                'verbose_name': 'Движение компонента при ТО',
                'verbose_name_plural': 'Движение компонентов при ТО (ФАП-367)',
                'ordering': ('outfit_card', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='externalmaintenanceorganization',
            index=models.Index(fields=['certificate_number'], name='idx_subcontractor_cert'),
        ),
        migrations.AddIndex(
            model_name='externalmaintenanceorganization',
            index=models.Index(fields=['is_active'], name='idx_subcontractor_active'),
        ),
        migrations.AddIndex(
            model_name='aviationcomponent',
            index=models.Index(fields=['part_number', 'serial_number'], name='idx_comp_pn_sn'),
        ),
        migrations.AddIndex(
            model_name='aviationcomponent',
            index=models.Index(fields=['status'], name='idx_comp_status'),
        ),
        migrations.AddIndex(
            model_name='aviationcomponent',
            index=models.Index(fields=['current_aircraft'], name='idx_comp_aircraft'),
        ),
        migrations.AddIndex(
            model_name='outfitcardcomponent',
            index=models.Index(fields=['outfit_card'], name='idx_outfit_comp_card'),
        ),
        migrations.AddIndex(
            model_name='outfitcardcomponent',
            index=models.Index(fields=['installed_component'], name='idx_outfit_comp_installed'),
        ),
    ]
