# Generated by Django 6.1.1 on 2026-10-02 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0173_externalmaintenanceorganization_aviationcomponent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaintenanceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(default='145-25-108', help_text="Официальный номер сертификата по ФАП-145 (например, '145-25-108')", max_length=100, verbose_name='Номер сертификата организации')),
                ('issue_date', models.DateField(help_text='Дата решения уполномоченного органа о выдаче сертификата', verbose_name='Дата выдачи')),
                ('valid_until', models.DateField(blank=True, help_text='Оставьте пустым, если сертификат бессрочный', null=True, verbose_name='Действителен до')),
                ('organization_name_ru', models.CharField(default='ООО АВИАКОМПАНИЯ «БАРКОЛ»', help_text='Официальное наименование организации на русском языке', max_length=255, verbose_name='Наименование организации (RU)')),
                ('organization_name_en', models.CharField(default='AVIACOMPANY «BARKOL» ltd', help_text='Официальное наименование организации на английском языке', max_length=255, verbose_name='Наименование организации (EN)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Использовать данный сертификат по умолчанию для новых свидетельств CRS', verbose_name='Действующий основной сертификат')),
                ('scan_file', models.FileField(blank=True, help_text='Электронная скан-копия бланка сертификата с приложениями', null=True, upload_to='company_certificates/', verbose_name='Скан-копия сертификата')),
                ('notes', models.TextField(blank=True, default='', help_text='Особые отметки, разрешенные рейтинги и типы ВС', verbose_name='Примечания / Область действия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Сертификат организации по ТО (ФАП-145)',
                'verbose_name_plural': 'Сертификаты организации по ТО (ФАП-145)',
                'ordering': ('-issue_date',),
            },
        ),
        migrations.AddField(
            model_name='outfitcard',
            name='test_flight_required',
            field=models.BooleanField(default=False, help_text='Отметка о необходимости выполнения контрольного облета после ТО (п. 17 CRS / ФАП-145)', verbose_name='Контрольный облет требуется'),
        ),
        migrations.CreateModel(
            name='MaintenanceReleaseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_seq', models.PositiveIntegerField(db_index=True, help_text='Порядковый номер свидетельства в текущем году (без ведущих нулей)', verbose_name='№ п/п (в году)')),
                ('year', models.PositiveIntegerField(db_index=True, help_text='Календарный год оформления свидетельства', verbose_name='Год')),
                ('certificate_number', models.CharField(db_index=True, help_text="Уникальный номер свидетельства в формате '<seq>/<YY>' (например, 1/26)", max_length=50, unique=True, verbose_name='Номер свидетельства')),
                ('maintenance_date', models.DateField(help_text='Фактическая дата выполнения работ по ТО', verbose_name='Дата выполнения ТО ВС')),
                ('aircraft_type', models.CharField(help_text='Тип воздушного судна (например, Ми-8Т, Ан-2)', max_length=100, verbose_name='Тип ВС')),
                ('tail_number', models.CharField(help_text='Государственный регистрационный номер ВС', max_length=50, verbose_name='Рег. № ВС (бортовой)')),
                ('factory_number', models.CharField(blank=True, default='', help_text='Заводской (серийный) номер планера ВС', max_length=50, verbose_name='Зав. № ВС')),
                ('operating_hours', models.CharField(blank=True, default='', help_text='Наработка ВС на момент ТО (например, 693 ч. 53 м.)', max_length=100, verbose_name='Наработка ВС')),
                ('maintenance_work_scope', models.TextField(help_text='Перечень регламентов, оперативных и дополнительных работ', verbose_name='Вид ТО (выполненные работы)')),
                ('certifying_staff_name', models.CharField(blank=True, default='', help_text='Фамилия, имя и отчество специалиста', max_length=255, verbose_name='ФИО специалиста')),
                ('certifying_staff_license', models.CharField(blank=True, default='', help_text='Номер бессрочного свидетельства специалиста по ТО ВС', max_length=100, verbose_name='Свидетельство специалиста')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text='Дата подписания и выдачи Свидетельства CRS', verbose_name='Дата свидетельства')),
                ('signature_stamp', models.CharField(blank=True, default='', help_text='Отметка об электронной подписи или штамп подтверждающего персонала', max_length=255, verbose_name='Подпись / ПЭП')),
                ('scan_file', models.FileField(blank=True, help_text='Электронная скан-копия оформленного свидетельства', null=True, upload_to='crs_certificates/', verbose_name='Скан свидетельства')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('certifying_staff', models.ForeignKey(help_text='Специалист подтверждающего персонала, выпустивший ВС', on_delete=django.db.models.deletion.PROTECT, related_name='crs_release_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Подтверждающий персонал')),
                ('outfit_card', models.ForeignKey(blank=True, help_text='Карта-наряд, на основании которой выписано свидетельство о ТО', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crs_certificates', to='hrdepartment_app.outfitcard', verbose_name='Карта-наряд (основание)')),
            ],
            options={
                'verbose_name': 'Свидетельство о ТО ВС (CRS)',
                'verbose_name_plural': 'Журнал свидетельств о ТО ВС (CRS)',
                'ordering': ('-year', '-number_seq'),
                'indexes': [models.Index(fields=['year', 'number_seq'], name='idx_crs_year_seq'), models.Index(fields=['certificate_number'], name='idx_crs_cert_num'), models.Index(fields=['outfit_card'], name='idx_crs_outfit_card')],
                'unique_together': {('year', 'number_seq')},
            },
        ),
    ]
