# Generated by Django 6.1.1 on 2026-10-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdepartment_app', '0174_companymaintenancecertificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereleasecertificate',
            name='aircraft_type',
            field=models.CharField(blank=True, default='', help_text='Тип воздушного судна (например, Ми-8Т, Ан-2)', max_length=100, verbose_name='Тип ВС'),
        ),
        migrations.AlterField(
            model_name='maintenancereleasecertificate',
            name='certificate_number',
            field=models.CharField(blank=True, db_index=True, help_text="Уникальный номер свидетельства в формате '<seq>/<YY>' (например, 1/26)", max_length=50, unique=True, verbose_name='Номер свидетельства'),
        ),
        migrations.AlterField(
            model_name='maintenancereleasecertificate',
            name='maintenance_date',
            field=models.DateField(blank=True, help_text='Фактическая дата выполнения работ по ТО', null=True, verbose_name='Дата выполнения ТО ВС'),
        ),
        migrations.AlterField(
            model_name='maintenancereleasecertificate',
            name='maintenance_work_scope',
            field=models.TextField(blank=True, default='', help_text='Перечень регламентов, оперативных и дополнительных работ', verbose_name='Вид ТО (выполненные работы)'),
        ),
        migrations.AlterField(
            model_name='maintenancereleasecertificate',
            name='number_seq',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, help_text='Порядковый номер свидетельства в текущем году (без ведущих нулей)', verbose_name='№ п/п (в году)'),
        ),
        migrations.AlterField(
            model_name='maintenancereleasecertificate',
            name='tail_number',
            field=models.CharField(blank=True, default='', help_text='Государственный регистрационный номер ВС', max_length=50, verbose_name='Рег. № ВС (бортовой)'),
        ),
        migrations.AlterField(
            model_name='maintenancereleasecertificate',
            name='year',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, help_text='Календарный год оформления свидетельства', verbose_name='Год'),
        ),
    ]
