# Generated by Django 6.1.1 on 2026-10-05 11:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0017_estate_decommission_date'),
        ('hrdepartment_app', '0175_alter_maintenancereleasecertificate_aircraft_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное наименование оборудования, прибора или специального инструмента', max_length=255, verbose_name='Наименование оборудования / инструмента')),
                ('equipment_type', models.CharField(choices=[('measuring', 'Средство измерений (СИ, 102-ФЗ)'), ('control_test', 'Контрольно-поверочная аппаратура (КПА)'), ('special_tool', 'Специальный инструмент'), ('standard_reference', 'Эталон / калибр / контрольный образец'), ('ground_equipment', 'Наземное оборудование ТО'), ('general_tool', 'Общий инструмент')], db_index=True, default='special_tool', help_text='Категория оборудования по классификации п. 22 ФАП-145', max_length=30, verbose_name='Категория оборудования')),
                ('part_number', models.CharField(blank=True, default='', help_text='Part Number по каталогу изготовителя или маркировке', max_length=100, verbose_name='Чертежный номер / модель (P/N)')),
                ('serial_number', models.CharField(blank=True, db_index=True, default='', help_text='Заводской или серийный номер изделия (при наличии)', max_length=100, verbose_name='Заводской / серийный номер (S/N)')),
                ('inventory_number', models.CharField(blank=True, default='', help_text='Бухгалтерский или складской инвентарный номер', max_length=100, verbose_name='Инвентарный номер')),
                ('marking_code', models.CharField(blank=True, default='', help_text='Индивидуальный идентификационный код маркировки согласно п. 23 ФАП-145', max_length=100, verbose_name='Код маркировки (п. 23 ФАП-145)')),
                ('operational_status', models.CharField(choices=[('serviceable', 'Исправен (годен к применению)'), ('defective', 'Неисправен (п. 24 ФАП-145)'), ('in_repair', 'В ремонте / на ТО'), ('quarantined', 'В изоляторе брака (карантин, п. 25 ФАП-145)'), ('scrapped', 'Списан')], db_index=True, default='serviceable', help_text='Физическое состояние оборудования по пп. 19, 24, 25 ФАП-145', max_length=30, verbose_name='Эксплуатационный статус')),
                ('verification_type', models.CharField(choices=[('verification', 'Поверка (102-ФЗ)'), ('calibration', 'Калибровка'), ('inspection', 'Проверка технического состояния'), ('not_required', 'Метрологический контроль не требуется')], db_index=True, default='not_required', help_text='Вид обязательного метрологического подтверждения по п. 19, 20 ФАП-145', max_length=30, verbose_name='Вид метрологического контроля')),
                ('last_verification_date', models.DateField(blank=True, help_text='Дата проведения последней поверки, калибровки или проверки состояния', null=True, verbose_name='Дата последней поверки/калибровки')),
                ('next_verification_date', models.DateField(blank=True, db_index=True, help_text='Срок окончания действия текущей поверки/калибровки', null=True, verbose_name='Дата очередной поверки/калибровки')),
                ('interval_value', models.PositiveIntegerField(blank=True, help_text='Периодичность проведения поверки/калибровки', null=True, verbose_name='Межповерочный / контрольный интервал')),
                ('interval_unit', models.CharField(choices=[('days', 'дней'), ('months', 'месяцев'), ('years', 'лет')], default='months', max_length=10, verbose_name='Единица интервала')),
                ('interval_source', models.CharField(blank=True, default='', help_text='Эксплуатационная документация изготовителя, методика поверки или регламент организации', max_length=255, verbose_name='Основание интервала')),
                ('arshin_verification_number', models.CharField(blank=True, default='', help_text='Регистрационный номер свидетельства о поверке или записи в реестре ФГИС «АРШИН» (102-ФЗ)', max_length=100, verbose_name='Номер во ФГИС «АРШИН» / Свидетельства')),
                ('verification_organization', models.CharField(blank=True, default='', help_text='Наименование аккредитованной метрологической службы / поверителя', max_length=255, verbose_name='Организация-поверитель')),
                ('certificate_scan', models.FileField(blank=True, help_text='Электронный скан документа о поверке/калибровке', null=True, upload_to='equipment_certificates/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Скан свидетельства / сертификата')),
                ('location', models.CharField(blank=True, default='', help_text='Инструментальная кладовая, борт ВС, контейнер, участок ТО', max_length=255, verbose_name='Место хранения / нахождения')),
                ('notes', models.TextField(blank=True, default='', help_text='Особые условия эксплуатации, поверки или хранения', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('applicable_aircraft_types', models.ManyToManyField(blank=True, help_text='Типы воздушных судов, для ТО которых предназначен прибор/инструмент', related_name='maintenance_equipments', to='contracts_app.typeproperty', verbose_name='Применимость к типам ВС')),
                ('production_place', models.ForeignKey(blank=True, help_text='Место производственной деятельности постоянного базирования', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='hrdepartment_app.placeproductionactivity', verbose_name='МПД приписки')),
                ('responsible_person', models.ForeignKey(blank=True, help_text='Сотрудник, ответственный за сохранность и метрологический контроль', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_equipments', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Оборудование и инструмент ТО (ФАП-145)',
                'verbose_name_plural': 'Реестр оборудования и инструментов ТО (ФАП-145)',
                'ordering': ('name', 'serial_number'),
            },
        ),
        migrations.CreateModel(
            name='EquipmentVerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('verification', 'Поверка (102-ФЗ)'), ('calibration', 'Калибровка'), ('inspection', 'Проверка технического состояния'), ('not_required', 'Метрологический контроль не требуется')], default='verification', max_length=30, verbose_name='Вид контроля')),
                ('verification_date', models.DateField(help_text='Дата фактического выполнения поверки / калибровки', verbose_name='Дата проведения')),
                ('valid_until', models.DateField(blank=True, help_text='Дата окончания действия свидетельства о поверке', null=True, verbose_name='Действительно до')),
                ('arshin_number', models.CharField(blank=True, default='', help_text='Номер свидетельства или записи в реестре ФГИС «АРШИН» (102-ФЗ)', max_length=100, verbose_name='Номер во ФГИС «АРШИН» / Свидетельства')),
                ('organization', models.CharField(blank=True, default='', help_text='Наименование аккредитованной метрологической службы / поверителя', max_length=255, verbose_name='Организация, проводившая поверку')),
                ('result_serviceable', models.BooleanField(default=True, help_text='Флаг успешного прохождения поверки (если False — прибор забракован)', verbose_name='Годен к применению')),
                ('certificate_scan', models.FileField(blank=True, help_text='Скан свидетельства о поверке или извещения о непригодности', null=True, upload_to='equipment_verifications/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Скан свидетельства')),
                ('notes', models.TextField(blank=True, default='', help_text='Параметры погрешности, замечания поверителя', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Кто внес запись')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='hrdepartment_app.maintenanceequipment', verbose_name='Оборудование / прибор')),
            ],
            options={
                'verbose_name': 'Запись о поверке оборудования',
                'verbose_name_plural': 'Журнал поверок и калибровок оборудования',
                'ordering': ('-verification_date',),
            },
        ),
        migrations.CreateModel(
            name='OutfitCardEquipmentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(blank=True, default='', help_text='Наименование инструмента на дату проведения ТО', max_length=255, verbose_name='Наименование (снимок)')),
                ('part_number', models.CharField(blank=True, default='', max_length=100, verbose_name='P/N (снимок)')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='S/N (снимок)')),
                ('inventory_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Инв. № (снимок)')),
                ('marking_code', models.CharField(blank=True, default='', max_length=100, verbose_name='Код маркировки (снимок)')),
                ('equipment_type', models.CharField(blank=True, default='', max_length=30, verbose_name='Категория (снимок)')),
                ('verification_type', models.CharField(blank=True, default='', max_length=30, verbose_name='Вид контроля (снимок)')),
                ('last_verification_date', models.DateField(blank=True, null=True, verbose_name='Дата поверки (снимок)')),
                ('next_verification_date', models.DateField(blank=True, null=True, verbose_name='Действительно до (снимок)')),
                ('arshin_number', models.CharField(blank=True, default='', max_length=100, verbose_name='ФГИС АРШИН (снимок)')),
                ('is_valid_at_usage', models.BooleanField(default=True, help_text='Флаг пригодности прибора на дату проведения ТО', verbose_name='Годен на момент применения')),
                ('validation_message', models.CharField(blank=True, default='', max_length=255, verbose_name='Результат проверки метрологии')),
                ('attached_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время фиксации')),
                ('notes', models.CharField(blank=True, default='', help_text='Этап или технологическая операция применения инструмента', max_length=255, verbose_name='Примечания')),
                ('attached_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_equipment_usages', to=settings.AUTH_USER_MODEL, verbose_name='Специалист, зафиксировавший применение')),
                ('equipment', models.ForeignKey(help_text='Использованная единица оборудования из реестра', on_delete=django.db.models.deletion.PROTECT, related_name='outfit_usages', to='hrdepartment_app.maintenanceequipment', verbose_name='Оборудование / прибор')),
                ('outfit_card', models.ForeignKey(help_text='Карта-наряд, при выполнении которой использовался прибор/инструмент', on_delete=django.db.models.deletion.CASCADE, related_name='used_equipment_records', to='hrdepartment_app.outfitcard', verbose_name='Карта-наряд')),
            ],
            options={
                'verbose_name': 'Применение оборудования в наряде',
                'verbose_name_plural': 'Применение оборудования в картах-нарядах (ФАП-145)',
                'ordering': ('outfit_card', '-attached_at'),
            },
        ),
        migrations.AddField(
            model_name='outfitcard',
            name='used_equipment',
            field=models.ManyToManyField(blank=True, help_text='Оборудование, КПА и специнструмент, использованные при выполнении ТО (ФАП-145, пп. 19-25)', related_name='outfit_cards', through='hrdepartment_app.OutfitCardEquipmentUsage', to='hrdepartment_app.maintenanceequipment', verbose_name='Использованное оборудование и инструмент'),
        ),
        migrations.AddIndex(
            model_name='maintenanceequipment',
            index=models.Index(fields=['operational_status'], name='idx_eq_oper_status'),
        ),
        migrations.AddIndex(
            model_name='maintenanceequipment',
            index=models.Index(fields=['equipment_type'], name='idx_eq_type'),
        ),
        migrations.AddIndex(
            model_name='maintenanceequipment',
            index=models.Index(fields=['next_verification_date'], name='idx_eq_next_verif'),
        ),
        migrations.AddIndex(
            model_name='maintenanceequipment',
            index=models.Index(fields=['serial_number'], name='idx_eq_serial'),
        ),
        migrations.AddIndex(
            model_name='maintenanceequipment',
            index=models.Index(fields=['part_number'], name='idx_eq_part_num'),
        ),
        migrations.AddIndex(
            model_name='equipmentverificationrecord',
            index=models.Index(fields=['equipment', '-verification_date'], name='idx_verif_eq_date'),
        ),
        migrations.AddIndex(
            model_name='equipmentverificationrecord',
            index=models.Index(fields=['verification_date'], name='idx_verif_date'),
        ),
        migrations.AddIndex(
            model_name='outfitcardequipmentusage',
            index=models.Index(fields=['outfit_card'], name='idx_outfit_eq_card'),
        ),
        migrations.AddIndex(
            model_name='outfitcardequipmentusage',
            index=models.Index(fields=['equipment'], name='idx_outfit_eq_inst'),
        ),
    ]
