# Generated by Django 6.1.1 on 2026-10-05 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0017_estate_decommission_date'),
        ('hrdepartment_app', '0176_maintenanceequipment_equipmentverificationrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Обобщенное наименование прибора или инструмента (напр. 'Ареометр', 'Амперметр')", max_length=150, unique=True, verbose_name='Наименование оборудования / СИ')),
                ('category', models.CharField(choices=[('measuring', 'Средство измерений (СИ, 102-ФЗ)'), ('control_test', 'Контрольно-поверочная аппаратура (КПА)'), ('special_tool', 'Специальный инструмент'), ('standard_reference', 'Эталон / калибр / контрольный образец'), ('ground_equipment', 'Наземное оборудование ТО'), ('general_tool', 'Общий инструмент')], db_index=True, default='special_tool', help_text='Категория оборудования по классификации п. 22 ФАП-145', max_length=30, verbose_name='Категория оборудования')),
                ('is_measuring_instrument', models.BooleanField(default=True, help_text='Признак отнесения к средствам измерений, требующим поверки/калибровки', verbose_name='СИ по 102-ФЗ')),
                ('description', models.TextField(blank=True, default='', help_text='Общие требования к условиям применения, консервации и хранения', verbose_name='Описание и правила хранения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Наименование оборудования и СИ',
                'verbose_name_plural': 'Справочник наименований оборудования и СИ (ФАП-145)',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Обозначение типа/модели (напр. 'АЭ-1', 'АНТ-2', 'М42300')", max_length=100, verbose_name='Тип / модель СИ')),
                ('part_number', models.CharField(blank=True, default='', help_text='P/N по каталогу изготовителя или ГОСТ', max_length=100, verbose_name='Чертежный номер / модель (P/N)')),
                ('arshin_type_number', models.CharField(blank=True, default='', help_text='Номер записи типа СИ в реестре ФГИС «АРШИН»', max_length=50, verbose_name='Номер Госреестра СИ РФ')),
                ('measurement_range', models.CharField(blank=True, default='', help_text="Диапазон измерений (напр. '1000...1060 кг/м³', '0...100 А')", max_length=150, verbose_name='Диапазон измерений')),
                ('accuracy_class', models.CharField(blank=True, default='', help_text='Класс точности по ГОСТ или предел допускаемой погрешности', max_length=100, verbose_name='Класс точности / Погрешность')),
                ('default_interval_months', models.PositiveIntegerField(default=12, help_text='Утвержденный межповерочный интервал в месяцах по методике поверки', verbose_name='Межповерочный интервал (мес.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('applicable_aircraft_types', models.ManyToManyField(blank=True, help_text='Типы воздушных судов. Если список пуст — прибор применим ко всем типам ВС компании', related_name='equipment_type_models', to='contracts_app.typeproperty', verbose_name='Применимость к типам ВС')),
                ('equipment_name', models.ForeignKey(help_text='Обобщенное наименование прибора/инструмента', on_delete=django.db.models.deletion.PROTECT, related_name='type_models', to='hrdepartment_app.equipmentname', verbose_name='Наименование оборудования')),
            ],
            options={
                'verbose_name': 'Тип / модель оборудования и СИ',
                'verbose_name_plural': 'Справочник типов и моделей оборудования и СИ (ФАП-145)',
                'ordering': ('equipment_name__name', 'name'),
            },
        ),
        migrations.AddField(
            model_name='maintenanceequipment',
            name='type_model',
            field=models.ForeignKey(blank=True, help_text='Ссылка на тип/модель из нормализованного справочника НСИ (ФАП-145)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='hrdepartment_app.equipmenttypemodel', verbose_name='Тип / модель СИ'),
        ),
        migrations.CreateModel(
            name='MaintenanceWorkEquipmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Минимальное необходимое количество исправных единиц на МПД', verbose_name='Требуемое количество (шт.)')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Без данного инструмента выполнение ТО и выпуск ВС категорически запрещены (п. 40 ФАП-145)', verbose_name='Критически обязательный инструмент')),
                ('task_reference', models.CharField(blank=True, default='', help_text='Ссылка на пункт регламента ТО или технологической карты РО', max_length=150, verbose_name='Пункт РО / техкарты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('allowed_substitutes', models.ManyToManyField(blank=True, help_text='Список утвержденных типов СИ, которые разрешено применять взамен основного', related_name='substitute_for_requirements', to='hrdepartment_app.equipmenttypemodel', verbose_name='Допустимые взаимозаменяемые аналоги (типы)')),
                ('equipment_name', models.ForeignKey(help_text="Обобщенное наименование прибора (напр. 'Ареометр', 'Манометр')", on_delete=django.db.models.deletion.PROTECT, related_name='work_requirements', to='hrdepartment_app.equipmentname', verbose_name='Наименование оборудования / СИ')),
                ('operational_work', models.ForeignKey(blank=True, help_text="Оперативное обслуживание (напр. 'Встречное', 'Предполетное')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_requirements', to='hrdepartment_app.operationalwork', verbose_name='Форма оперативного ТО (ОТО)')),
                ('periodic_work', models.ForeignKey(blank=True, help_text="Регламентная форма ТО (напр. 'Ф-1', '100 ч', '300 ч')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_requirements', to='hrdepartment_app.periodicwork', verbose_name='Форма периодического ТО (ПТО)')),
                ('required_type', models.ForeignKey(blank=True, help_text='Если пусто — допускается любой исправный тип данного наименования', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_in_works', to='hrdepartment_app.equipmenttypemodel', verbose_name='Требуемый тип / модель (если строго)')),
            ],
            options={
                'verbose_name': 'Требование работы ТО к оборудованию',
                'verbose_name_plural': 'Табель оснащения работ ТО оборудованием (ФАП-145)',
                'ordering': ('periodic_work', 'operational_work', 'equipment_name__name'),
            },
        ),
        migrations.CreateModel(
            name='EquipmentTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_date', models.DateField(help_text='Планируемая дата начала ТО, к которой инструмент должен быть на месте', verbose_name='Требуемая дата доставки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('requested', 'Запрошено (ожидает отправки)'), ('in_transit', 'В пути (отправлено с МПД-донора)'), ('delivered', 'Доставлено на целевое МПД'), ('returned', 'Возвращено на МПД базирования'), ('canceled', 'Отменено')], db_index=True, default='requested', max_length=20, verbose_name='Статус логистики')),
                ('tracking_number', models.CharField(blank=True, default='', help_text='Номер экспресс-накладной, борт рейса или сопроводительного документа', max_length=100, verbose_name='Номер накладной / трек')),
                ('notes', models.TextField(blank=True, default='', help_text='Служебные пометки (условия транспортировки, габариты и т.д.)', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(help_text='Специалист, оформивший заявку на меж-МПД доставку', on_delete=django.db.models.deletion.PROTECT, related_name='created_equipment_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('equipment', models.ForeignKey(help_text='Конкретная единица прибора/инструмента из реестра ТО', on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='hrdepartment_app.maintenanceequipment', verbose_name='Оборудование / прибор')),
                ('from_mpd', models.ForeignKey(help_text='Точка базирования, откуда перемещается прибор', on_delete=django.db.models.deletion.PROTECT, related_name='equipment_transfers_out', to='hrdepartment_app.placeproductionactivity', verbose_name='МПД отправления (донор)')),
                ('target_operational_work', models.ForeignKey(blank=True, help_text='Планируемая оперативная работа ТО ВС', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_transfers', to='hrdepartment_app.operationalwork', verbose_name='Форма ОТО')),
                ('target_periodic_work', models.ForeignKey(blank=True, help_text='Планируемая периодическая работа ТО ВС', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_transfers', to='hrdepartment_app.periodicwork', verbose_name='Форма ПТО')),
                ('to_mpd', models.ForeignKey(help_text='МПД, где запланировано выполнение технического обслуживания', on_delete=django.db.models.deletion.PROTECT, related_name='equipment_transfers_in', to='hrdepartment_app.placeproductionactivity', verbose_name='Целевое МПД (получатель)')),
            ],
            options={
                'verbose_name': 'Заявка на перемещение оборудования',
                'verbose_name_plural': 'Реестр перемещений оборудования между МПД (ФАП-145)',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='idx_eq_transfer_status'), models.Index(fields=['required_date'], name='idx_eq_transfer_req_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='equipmenttypemodel',
            constraint=models.UniqueConstraint(fields=('equipment_name', 'name'), name='uq_equipment_name_type_model'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceworkequipmentrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('periodic_work__isnull', False)), fields=('periodic_work', 'equipment_name', 'required_type'), name='uq_req_periodic_work_name_type'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceworkequipmentrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('operational_work__isnull', False)), fields=('operational_work', 'equipment_name', 'required_type'), name='uq_req_operational_work_name_type'),
        ),
    ]
