# Generated by Django 5.2.12 on 2026-09-03 12:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing_app", "0002_create_manager_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testingattempt",
            name="certificate_uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                unique=True,
                verbose_name="Уникальный UUID уведомления",
            ),
        ),
    ]
