# Generated by Django for testing_app

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import testing_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testing_app", "0003_alter_testingattempt_certificate_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureMaterial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(db_index=True, max_length=255, verbose_name="Наименование лекции")),
                ("doc_file", models.FileField(blank=True, help_text="Исходный редактируемый файл лекции в формате .doc или .docx", null=True, upload_to=testing_app.models.lecture_doc_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["doc", "docx"])], verbose_name="Файл документа (doc, docx)")),
                ("scan_file", models.FileField(blank=True, help_text="Электронный образ или скан документа в формате PDF для встроенного просмотра", null=True, upload_to=testing_app.models.lecture_scan_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["pdf"])], verbose_name="Скан документа (pdf)")),
                ("is_actual", models.BooleanField(db_index=True, default=True, help_text="Признак актуальности материала (неактуальные скрываются от сотрудников)", verbose_name="Актуальность")),
                ("description", models.TextField(blank=True, default="", help_text="Краткое содержание или методические указания к лекционному материалу", verbose_name="Описание / Аннотация")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Дата добавления")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_lectures", to=settings.AUTH_USER_MODEL, verbose_name="Создал")),
            ],
            options={
                "verbose_name": "Лекционный материал",
                "verbose_name_plural": "Лекционные материалы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoLecture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(db_index=True, max_length=255, verbose_name="Наименование видеолекции")),
                ("video_file", models.FileField(help_text="Видеозапись в формате MP4", upload_to=testing_app.models.video_lecture_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["mp4"])], verbose_name="Видеофайл (mp4)")),
                ("is_actual", models.BooleanField(db_index=True, default=True, help_text="Признак актуальности видеоматериала (неактуальные скрываются от сотрудников)", verbose_name="Актуальность")),
                ("description", models.TextField(blank=True, default="", help_text="Краткое содержание или таймкоды видеолекции", verbose_name="Описание / Аннотация")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Дата добавления")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_video_lectures", to=settings.AUTH_USER_MODEL, verbose_name="Создал")),
            ],
            options={
                "verbose_name": "Видеолекция",
                "verbose_name_plural": "Видеолекции",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialViewLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("material_type", models.CharField(choices=[("lecture", "Лекционный материал"), ("video", "Видеолекция")], db_index=True, max_length=20, verbose_name="Тип материала")),
                ("first_viewed_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Первое обращение")),
                ("last_viewed_at", models.DateTimeField(auto_now=True, db_index=True, verbose_name="Последнее обращение")),
                ("views_count", models.PositiveIntegerField(default=1, verbose_name="Количество обращений")),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP-адрес")),
                ("lecture", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="view_logs", to="testing_app.lecturematerial", verbose_name="Лекционный материал")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="material_views", to=settings.AUTH_USER_MODEL, verbose_name="Сотрудник")),
                ("video_lecture", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="view_logs", to="testing_app.videolecture", verbose_name="Видеолекция")),
            ],
            options={
                "verbose_name": "Запись журнала обращений к материалам",
                "verbose_name_plural": "Журнал обращений к материалам",
                "ordering": ["-last_viewed_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="materialviewlog",
            constraint=models.UniqueConstraint(fields=("user", "lecture"), name="unique_user_lecture_view"),
        ),
        migrations.AddConstraint(
            model_name="materialviewlog",
            constraint=models.UniqueConstraint(fields=("user", "video_lecture"), name="unique_user_video_view"),
        ),
    ]
