# Generated by Django 5.2.12 on 2026-09-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing_app", "0006_testing_event_start_datetime_and_required_lectures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testing",
            name="end_datetime",
            field=models.DateTimeField(
                verbose_name="Дата и время окончания тестирования"
            ),
        ),
    ]
